### ISSUE TITLE
Brine processing leaves empty bucket in machine input 

### ISSUE THREAD

**Issue by quasarea** [EnigmaticaModpacks/Enigmatica9#1001]
### Modpack Version

1.22.1

### Describe your issue.

When processing bucket of brine in centrifugal separator, following:
![image](https://github.com/user-attachments/assets/c2c9fbd8-982c-4330-8b90-35274980acf8)

machine ends up with empty bucket in the input slot
![image](https://github.com/user-attachments/assets/755ff06a-fcb6-45bb-b246-8446492b0ba1)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

QuasaRea

**Comment by quasarea** [comment]
Workaround by opening side to `hole` mode and setting import bus with empty bucket filter
![image](https://github.com/user-attachments/assets/8c901278-0902-4779-b13f-81152702562a)

**Comment by SeooY** [comment]
This is not a bug, that's just how the machine works. You are supposed to take the bucket out yourself.

**Comment by MuteTiefling** [comment]
You can use pipes or whatever to pull it from the input slot too. Doesn't need to be manual extraction. A very simple setup is to have the bucket filling machine pushing and pulling on a side.
