### ISSUE TITLE
Items stuck in vacuum pressure chamber interface

### ISSUE THREAD

**Issue by jamaa** [EnigmaticaModpacks/Enigmatica9#1008]
### Modpack Version

1.23.1

### Describe your issue.

Trying to insert 16 bottles into a 1x1 internal volume vacuum pressure chamber (pneumaticraft). Items are stuck in the pressure chamber interface with message "Not enough pressure". Pressure is at -0.99. I have added 16 volume upgrades to the vacuum pump but it doesn't help.

I guess this is similar to https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4630 but the suggested volume upgrades did not resolve it. Unless I have to max out volume upgrades up to 25?

Playing E9 Expert if it matters,

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SeooY** [comment]
The Volume Upgrades are supposed to go in the Pressure Chamber, not in the Vacuum Pump. This is also not a bug, it's intended mechanics of the mod.

**Comment by jamaa** [comment]
@SeooY thanks! I didn't realize the pressure chamber can also have upgrades. A single volume upgrade did the trick!
