### ISSUE TITLE
Tree of life not matching the pentacle it is supposed to match

### ISSUE THREAD

**Issue by Arehmin** [EnigmaticaModpacks/Enigmatica9#1009]
### Modpack Version

1.23.1

### Describe your issue.

the stage 1 of tree of life does not match the pentacle used for rituals and because of that cannot be used for rituals.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll take a look at this.
