### ISSUE TITLE
game crashed due to some villiger i believe 

### ISSUE THREAD

**Issue by JASE1980** [EnigmaticaModpacks/Enigmatica9#1015]
### Modpack Version

enigmatica9 version 1.19

### Describe your issue.

game crashed due to some villiger i believe i quit playing cause it always keeps crashing i love the game and all the hard work that goes into it
[my mod minecraft crash file.txt](https://github.com/user-attachments/files/17610204/my.mod.minecraft.crash.file.txt)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

AngelsofDoom#5667

**Comment by MuteTiefling** [comment]
You should be able to resolve this by editing your `forge-server.toml` file.

`.\world\serverconfig\forge-server.toml`

change `removeErroringEntities = true` to `false` and start the game again.

remember to undo this change after you've loaded into the world once.
