### ISSUE TITLE
Exception in server tick loop when making auto source generation..

### ISSUE THREAD

**Issue by Mankotako** [EnigmaticaModpacks/Enigmatica9#1016]
### Modpack Version

1.19.2

### Describe your issue.

Yesterday I worked on an auto source system.
  amethyst with goloms > source gems > source gem blocks > 2 conjuration essence spots > awkward potions > torch barries with turrets > night vision potions > alchemist source links > source.
everything was fine for the 4 hours I played after making this system and before I stopped playing I turned off the turrets just incase and downloaded a back up since I do that every week, today when I tried to start the server it kept crashing, first thing that came to mind was the system I made, so I used the backup I had to try it in singleplayer, but it just loads for 30 min with nothing happening and my laptop fan going nuts, I tried the: worldsave/serverconfig/forge-server.toml , but the same thing happens no respond for half an hour it doesn't even crash it just stays that way but luckly I found that there was a crash report this time even though it was still trying to load the world with the no respond at the top, I really hope there is a way to save it because in the past week me and my friend done a lot of progress from half of chapter 1 to 2 things left on chapter 2 and over 30 hours of playing...

thank you for your time <3

Server log (using aternos.org) :
https://mclo.gs/ffKcBpG
singleplayer log:
<script src="https://gist.github.com/Mankotako/28dbd8cfbae3e87dbf67046bd746606c.js"></script>

### Crash Report

<script src="https://gist.github.com/Mankotako/28dbd8cfbae3e87dbf67046bd746606c.js"></script>

### Latest Log

<script src="https://gist.github.com/Mankotako/28dbd8cfbae3e87dbf67046bd746606c.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

manko555

**Comment by NielsPilgaard** [comment]
Could you please re-upload your logs?

**Comment by Mankotako** [comment]
[crash-2024-11-08_13.10.31-server.txt](https://github.com/user-attachments/files/17692060/crash-2024-11-08_13.10.31-server.txt)

**Comment by Mankotako** [comment]
> Could you please re-upload your logs?

https://mclo.gs/ffKcBpG

I think the server one has more info..

**Comment by NielsPilgaard** [comment]
Your server ran out of RAM, 3GB is not a lot 😬 There's nothing we can do about that I'm afraid.
If you can download the world and get a server with more memory, that ought to help.

**Comment by Mankotako** [comment]
> Your server ran out of RAM, 3GB is not a lot 😬 There's nothing we can do about that I'm afraid. If you can download the world and get a server with more memory, that ought to help.

sadge :'(
