### ISSUE TITLE
[Mod Suggestion] ME Requester

### ISSUE THREAD

**Issue by DAmNRelentless** [EnigmaticaModpacks/Enigmatica9#102]
### URL

https://www.curseforge.com/minecraft/mc-mods/merequester

### Why would you like the mod added?

I decoupled this feature from my other mod Lazier AE2 because a lot of people really liked the Requester to automatically keep things in stock in their Applied Energistics 2 ME-System but they found it too expensive so here it is as a standalone, completely redone with a custom terminal to manage all requests and fluid support.

**Comment by NielsPilgaard** [comment]
I'm not sure, I'll give it some thought 🤔

**Comment by jlfree12** [comment]
There are tons of ways to passively stock items (level emitters, drawers with downgrades and storage busses etc.). This mod feels like it just makes something that isn't difficult and is kinda fun trivial.

**Comment by DAmNRelentless** [comment]
Feel free to have your opinion but there are a lot of people who liked it when it was a part of LazierAE2 because it's way easier and now with the terminally, it can be remotely controlled. It's also not limited to a stack per slot and you can configure the batch size which you can't for other methods. It will always craft one by one which is far more intensive for the system than crafting a whole batch. :)

**Comment by NielsPilgaard** [comment]
I'm gonna go with yes on this one. 
We'll make sure it's super expensive so the hand built methods are more ressource efficient. A server friendly variant of a setup is always nice to have 👍

**Comment by NielsPilgaard** [comment]
So it turns out... this mod causes a crash when used in combination with Supplementaries + Moonlight Lib, possibly due to the mixin plugin in ME Requester. https://github.com/MehVahdJukaar/Moonlight/issues/51

**Comment by DAmNRelentless** [comment]
I talked to the author of Moonlight and we found the reason for this niche issue. It's fixed and the update should be available in a bit. Thanks for the report and sorry for the time you had to invest to find this. 💚

**Comment by NielsPilgaard** [comment]
No worries, thanks for the fix 😀
