### ISSUE TITLE
While carrying an armoured jetpack and wearing a second if you impact a tree top and die you lose one jetpack

### ISSUE THREAD

**Issue by gzcwnk** [EnigmaticaModpacks/Enigmatica9#108]
### Modpack Version

1.0.2

### Describe your issue.

As above, lost a jetpack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

merchantofdeath

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Did one of them have soul bound on it, by chance?

**Comment by gzcwnk** [comment]
No as I dont think you can add soulbound to a jetpack?  or I couldnt add enhancements to it when I tried.

What was a bit odd was I did see I still had my compressed iron boots on but these are totally un-enchanted so head scratch.

**Comment by MuteTiefling** [comment]
Ok. I can't seem to reproduce this in Dev, but I've updated a lot of the mods there, notably both Mekanism and Enigmatic Graves. So it's possible this is already fixed. 

I'll mark as resolved next update tentatively.
