### ISSUE TITLE
Superior Shields 

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#11]
### URL

https://www.curseforge.com/minecraft/mc-mods/superior-shields

### Why would you like the mod added?

Energy/cooldown based shields that slowly regen between hits. Could be a cool addition.

**Comment by MuteTiefling** [comment]
There, that went to the right spot

**Comment by NielsPilgaard** [comment]
Not yet marked as 1.19.2 compatible, but I'll add it when it is.
