### ISSUE TITLE
Dragon Slaying Bug

### ISSUE THREAD

**Issue by DeaLLet** [EnigmaticaModpacks/Enigmatica9#114]
### Modpack Version

Enigmatica 9 1.0.2

### Describe your issue.

After killing the dragon, game crashes. And after restart, dragon cannot disappear, as a result of which the egg and portal distant lands do not appear.

### Crash Report

https://gist.github.com/DeaLLet/b7a7b0bfc7814e0aaaae079e9d42d141 

### Latest Log

https://gist.github.com/DeaLLet/1cc401eb992a3350ee7778ca80769bfc

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by Darkere** [comment]
this one seems to be on me

**Comment by Darkere** [comment]
Not 100% certain that the issue is caused by me, but regardless the feature was broken anyway, and I've released a fix :)
