### ISSUE TITLE
Add Tempad

### ISSUE THREAD

**Issue by CodexAdrian** [EnigmaticaModpacks/Enigmatica9#12]
### URL

https://www.curseforge.com/minecraft/mc-mods/tempad

### Why would you like the mod added?

Tempad is a tech teleportation mod. Its super configurable, allowing you as a pack maker to chose between what kind of fuel the tempad requires to teleport the player. You can store any amount of locations on the device and teleporting to the location will summon a doorway you have to walk through in order to get there, very much like the Loki timedoors that the mod was inspired by. Its pretty balanced and works well alongside waystones. It also features a late game alternative whose fuel is also configurable with completely different config options, so the 2 devices can use different kinds of fuel or different amounts of the same fuel. 

(This is just a duplicate of my suggestion in Enigmatica 8)

**Comment by NielsPilgaard** [comment]
I can't get it to work on 1.19.2 😅 
I'm also not a fan of the placeholder wiki button, players new to the mod are likely to press that first, and having it do nothing is a bad player experience, imo.
