### ISSUE TITLE
Server files seem to be missing PolyLib

### ISSUE THREAD

**Issue by Babbie** [EnigmaticaModpacks/Enigmatica9#121]
### Modpack Version

1.1.0

### Describe your issue.

Trying to create a fresh server causes an early crash due to ftbbackups2 requiring polylib, which is not included.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Bab#6123

**Comment by NielsPilgaard** [comment]
Oh that's embarrassing, I'll get that fixed asap :)

**Comment by NielsPilgaard** [comment]
I've pushed a fix to CurseForge, it should be available shortly :)
