### ISSUE TITLE
[Mod Suggestion] Creeper Overhaul

### ISSUE THREAD

**Issue by ThatGravyBoat** [EnigmaticaModpacks/Enigmatica9#122]
### URL

https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul

### Why would you like the mod added?

It would be nice to see some variety when having creepers sneak up on me.

**Comment by NielsPilgaard** [comment]
I'm unsure to be honest, might be nice to have - @MuteTiefling thoughts?

**Comment by MuteTiefling** [comment]
They are *very* cute. Will give them a closer look and see what they're like.

**Comment by MuteTiefling** [comment]
Yeah, I love them. Very cute.

Will very likely end up tweaking the loot tables. The cave creepert drops gold and iron ore, as well as diamonds and emeralds, which seems a bit much in a mob spawner. But otherwise, super cool.

**Comment by NielsPilgaard** [comment]
Cool, adding it!
