### ISSUE TITLE
[Mod suggestion] Enigmatic legacy

### ISSUE THREAD

**Issue by TruePureGold** [EnigmaticaModpacks/Enigmatica9#128]
### URL

https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy

### Why would you like the mod added?

Firstly id like to say that its NOT because the name of the mod is similar to the pack name
Enigmatic legacy adds a bunch of useful items, including one with voice acting and a lot of curios equipment, most loot being found within loot chests, you will spawn with 2 items, an amulet which has will have a random colour with a stat increase, and the ring of seven curses, an item made to make the game harder but providing benefits for equipping it, its a very fun mod and I like it a lot.
also fun fact: the dev of this mod made no chat reports

**Comment by MuteTiefling** [comment]
Not really interested in this one.

**Comment by NielsPilgaard** [comment]
Me neither, not a fan 😄
