### ISSUE TITLE
upgrade from 1.0.2 server to 1.1.1 server breaks purification chamber in mekanism for ore trippling

### ISSUE THREAD

**Issue by gzcwnk** [EnigmaticaModpacks/Enigmatica9#129]
### Modpack Version

Enigmatica9Server-1.1.1.zip

### Describe your issue.

upgrade from 1.0.2 server to 1.1.1 server breaks purification chamber in mekanism for ore trippling. Cannot put mined metals into it any longer.'

"use raw ore blocks , its a known mistake with script location (assuming its the issue im thinking of) "

Tried this but it didnt work and without silk touch not easy

### Crash Report

na

### Latest Log

https://gist.github.com/gzcwnk/448f42b822756b313e7ab59a575c77a7

### Have you modified the modpack?

No

### User Modifications

none

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

merchantofdeath#2094

**Comment by Kanzaji** [comment]
Already fixed in-dev ^^

**Comment by gzcwnk** [comment]
So 1.1.2 or something?

**Comment by Kanzaji** [comment]
Yea, but it is not released yet.
Temporary fix would be to just remove lines 15-17 in remove.js script.not sure if clients joining the server would need to do the same however.
https://github.com/EnigmaticaModpacks/Enigmatica9/blob/master/kubejs/server_scripts/base/recipes/enigmatica/remove.js#L15-L17

**Comment by gzcwnk** [comment]
its ok I'll go back to 1.0.2
