### ISSUE TITLE
Book Wyrms

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica9#13]
### URL

https://www.curseforge.com/minecraft/mc-mods/book-wyrms

### Why would you like the mod added?

~~I think the curseforge is still awaiting approval but~~ it's up on [Modrinth](https://modrinth.com/mod/book-wyrms) ~~if you need to test it in the mean time~~. Anyway:

It's a fresh new mod that adds colorful lizards (Book Wyrms) that you can feed enchanted books to have them reroll them into new ones. They also have stats and species and you can breed them together to improve their stats to get a better deal out of your trashed books.

I tried my best to make them quite configurable so I'm curious to see how it goes. But also I think it's neat.

**Comment by NielsPilgaard** [comment]
Looks cool!
