### ISSUE TITLE
Productive Bees

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica9#131]
### URL

https://www.curseforge.com/minecraft/mc-mods/productivebees

### Why would you like the mod added?

Originally i was just going to suggest it on order to bring attention to it, but it doesn't look like e9 has resourceful bees yet,
here are some key differences:

- simulation upgrade, bees not having to physically exit their hives
- honey treats, being able to lure natural bees without exploring excessively
- no multiblock apiary, saves space and sanity
- no multiblock centrifuge, though there is an upgrade (draconic egg) that is "3x as fast and can process comb blocks"
- bees don't pollinate/mutate entities/bees into other things (imo that was annoying), but you can mutate via feeding
- a genetics system, just a few traits so its not that overwhelming (nor required), but it would be an nice sidequest
- a handful of upgrades you can put in hives/machines
- a vanilla-ish hive you can shear without the bees becoming angry (since there's a campfire in its recipe)
- you can expand a hive's slots from 3 to 5 by placing an expansion block ontop (though i wouldn't call it multiblock)
- you can even ride a (bumble) bee with a saddle and a treat on a stick, basically a hovercraft when it comes to flight
- also, resourcefulbees appears stuck on .16, no .18 or .19 visible on their curseforge homepage
- probably some more stuff i have missed

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. If Resourceful Bees is coming, I'd prefer to wait for that, but if it's not then, maybe 😄

**Comment by MuteTiefling** [comment]
Resourceful Bees should be getting close: https://resourcefulbees.com/blog/development-update
