### ISSUE TITLE
Cyan dye missing vanilla recipe

### ISSUE THREAD

**Issue by DJteaCosy** [EnigmaticaModpacks/Enigmatica9#138]
### Modpack Version

1.2.0

### Describe your issue.

Cyan dye is missing the vanilla shapeless recipe of blue dye + green dye - JEI only shows recipes of how to obtain from various plants.

TO REPRODUCE: join world, search 'cyan dye' in JEI, click to preview recipes and note blue + green recipe is missing

### Have you modified the modpack?

Yes

### User Modifications

Added Rubidium

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

dj_teaCosy#8331

**Comment by DJteaCosy** [comment]
I noted on discord that I didn't try crafting the dye manually, I plan to test that when I get home later today (+-4 hours from this post)

**Comment by MuteTiefling** [comment]
Can confirm, it's broken. Forgot to account for these in the dye unification
