### ISSUE TITLE
Simple inventory sorter scroll feature overrides Mouse Tweaks scroll

### ISSUE THREAD

**Issue by DJteaCosy** [EnigmaticaModpacks/Enigmatica9#144]
### Modpack Version

1.2.0

### Describe your issue.

Simple Inventory Sorter mod provides a 'scroll mouse wheel to move items' feature, which overrides the one provided by Mouse Tweaks, meaning the config/settings of Mouse Tweaks is ignored.

Steps to reproduce: load instance, edit Mouse Tweaks config settings, enter game and attempt to move items between inventories via scroll wheel, and notice that the MT config settings are ignored.

### Have you modified the modpack?

Yes

### User Modifications

Added Rubidium, removed Simple Rich Discord Presence

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

dj_teaCosy#8331

**Comment by NielsPilgaard** [comment]
Thanks for the report. The consequence of this issue is that the scroll direction cannot be changed, correct?

**Comment by DJteaCosy** [comment]
essentially, yes. I messed around with the MouseTweaks configs multiple times with no effect until I realised something else was interfering
