### ISSUE TITLE
Kubejs script error

### ISSUE THREAD

**Issue by blacksythe** [EnigmaticaModpacks/Enigmatica9#147]
### Modpack Version

1.2

### Describe your issue.

Kubejs Script error spams console

! #31: Error occurred while handling event 'EntityEvents.spawned': TypeError: Cannot find function split in object entity.minecraft.squid. (server_scripts:base/entity/spawned/equipment.js#31)

This happens for almost every mob type not just the squid.

Disabling it obviously weakens the mobs in the pack, but completely stops the console spam.

### Have you modified the modpack?

Yes

### User Modifications

Chunky-1.3.38.jar
crashutilities-6.1.jar
ftb-essentials-1902.1.10-build.47.jar
ftb-ranks-forge-1902.1.11-build.46.jar
kotlinforforge-3.7.1-obf.jar
LuckPerms-Forge-5.4.46.jar
observable-3.3.0.jar
worldedit-mod-7.2.12.jar

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Kanzaji** [comment]
Thank you for the report. Already fixed in dev :)
