### ISSUE TITLE
Creatures and Beasts

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica9#15]
### URL

https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts

### Why would you like the mod added?

A very nice-looking creatures/mob mod with a mix of cool critters and useful ones (either through taming (works with Domestication Innovation), bartering, or a flying End mount). Would make for a nice change of creatures/fresh batch after Alex's Mobs on Enigmatica 6.

**Comment by MuteTiefling** [comment]
I've had my eye on this too. Definitely wish a look. Could be a nice change from Alex's mobs
