### ISSUE TITLE
Vanilla crafting recipes for dyes missing

### ISSUE THREAD

**Issue by DJteaCosy** [EnigmaticaModpacks/Enigmatica9#153]
### Modpack Version

1.3.0

### Describe your issue.

All manual crafting recipes for vanilla dyes are missing. All secondary colour recipes have been restored, however.

Missing (from my testing):
-Blue dye from lapis
-Black dye from ink sacs
-Red dye from roses, poppies, and beetroot
-Yellow dye from sunflowers, dandelions
-Brown dye from cocoa beens
-Crafting recipes for all other flowers

Steps to reproduce; join game, search for "dye" in JEI, checking each primary dye or dye-from-flower/source recipe is missing and not craftable in the crafting grid

### Have you modified the modpack?

No

### User Modifications

Added rubidium

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

dj_teaCosy#8331

**Comment by MuteTiefling** [comment]
Could you send a long you `.\logs\kubejs\server.txt` log? I'm betting that the tag scripts are failing. All of those recipes are based on custom tags, and if the script fails to create the tag, no recipe :(
