### ISSUE TITLE
Bring back full Engineers' Decor and RFTools

### ISSUE THREAD

**Issue by PeaceIsBliss** [EnigmaticaModpacks/Enigmatica9#157]
### Describe your suggestion

The blocked item lists make no sense to me. Not sure what you are trying to force players to do here. Especially considering so many other utility mods are absent currently. I prefer ED's Dropper's and Hoppers for better management and reduced tickrates for server performance. Also appreciate using RFTools Modular Storage for early game adventure, and its Sensor for various tasks.

Is the idea to force people into AE2 for all storage / collection related tasks? Or magic mods? I'm just lost in the reasoning behind these choices. And I'm sure I haven't discovered all effected mods.

### Why would you like this added/changed?

The game is less appealing to me with so many wild restrictions.

**Comment by NielsPilgaard** [comment]
> The blocked item lists make no sense to me. Not sure what you are trying to force players to do here. Especially considering so many other utility mods are absent currently. I prefer ED's Dropper's and Hoppers for better management and reduced tickrates for server performance. Also appreciate using RFTools Modular Storage for early game adventure, and its Sensor for various tasks.

We're trying to limit options so there's less ground to cover when making cross-mod compatibility.
In the case of RFTools Storage, we've simply encountered too many bugs with it to want to use it at this point.

I hope that helps explain our decisions, and thank you for making this issue :)
