### ISSUE TITLE
[Mod Suggestion] Hexerei

### ISSUE THREAD

**Issue by FyreAlchemage** [EnigmaticaModpacks/Enigmatica9#160]
### URL

https://www.curseforge.com/minecraft/mc-mods/hexerei

### Why would you like the mod added?

Hexerei is a very pretty mod, offering several decorative blocks and a few functional ones, flying brooms, and a neat armor set. I mainly suggest it for its decorative potential, as it doesn't have too many actual features still, but some of its additions could be neat such as the brooms (a form of flight), coffers (a form of portable storage), and sage-burning plate (a way to stop mob spawns around an area).

**Comment by MuteTiefling** [comment]
It's on the list! Unfortunately it was causing a server crash and had to be pulled. It'll be back as soon as it gets fixed.

**Comment by FyreAlchemage** [comment]
Under what conditions does a crash occur? I installed it to my instance of the pack about a day ago and haven't seen any crashing from it yet.

**Comment by FyreAlchemage** [comment]
Ah, no wonder I hadn't encountered it. That's a very major issue by the sound of it.

**Comment by NielsPilgaard** [comment]
Are you sure? Seems super unstable still:
- https://github.com/JoeFoxe/Hexerei-1.18/issues/68
- https://github.com/JoeFoxe/Hexerei-1.18/issues/48
- https://github.com/JoeFoxe/Hexerei-1.18/issues/56

**Comment by Darkere** [comment]
Not saying it is stable, just the issue that prevented it from loading on servers at all was resolved...

Just checked that was in Oktober.... time flies
