### ISSUE TITLE
Bumblezone 1.19.2

### ISSUE THREAD

**Issue by TelepathicGrunt** [EnigmaticaModpacks/Enigmatica9#17]
### URL

https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

### Why would you like the mod added?

While Bumblezone has been turned down in the past due to not enough content: https://github.com/EnigmaticaModpacks/Enigmatica8/issues/28#issuecomment-1002435237

The latest 1.19.2 version of Bumblezone has more content than previous versions and better performance too! Some extra content includes a Bee Queen to do trades with (datapackable https://github.com/TelepathicGrunt/Bumblezone/tree/latest-released-Forge/src/main/resources/data/the_bumblezone/bz_bee_queen_trades), more blocks and a new biome, advancements that act like a quest for good rewards, and has incense candles that can be quite powerful for end game usage. 

![88AD66FD-F513-4D77-9AEE-E6F1787D4D72](https://user-images.githubusercontent.com/40846040/185831825-bbdc471e-a4d4-4bf9-9c75-72381789a9e6.png)

There’s lots of tags and datapackable and configurable stuff in Bumblezone. If there’s any issue with balance or missing configurations, let me know and I’ll try and do adjustments/new configs or datapackable jsons. 

Note: I am the dev for the mod. Just fyi so yes this is a shameless self-plug lol

**Comment by NielsPilgaard** [comment]
I'll have a look in-game 👍
