### ISSUE TITLE
RFTools Utility

### ISSUE THREAD

**Issue by TheAnimaDust** [EnigmaticaModpacks/Enigmatica9#171]
### URL

https://www.curseforge.com/minecraft/mc-mods/rftools-utility

### Why would you like the mod added?

I love the redstone logic in this and i don't think we have any counterpart in the modpack right now.

**Comment by MuteTiefling** [comment]
Thanks for the suggestion. 

Immersive Engineering, PneumaticCraft, Create, and Redstone Pen all have comprehensive redstone components that cover most anything RFTools Utility has to offer.

The crafter, spawner, tanks, and teleportation system are all covered by other mods as well.

**Comment by jlfree12** [comment]
The RFTools crafter is really unique with features like the keep mode, putting items back into the crafting inventory and being able to lock output slots. Maybe something that would be bad to lose?

**Comment by MuteTiefling** [comment]
Thermal's crafter is smart enough to leave re-usable items in the input and also only allows items required for the configured craft in the input. It quite handily covered crafting Books of Binding for Occultism here without issue. 

As a bonus, it also has a fluid tank so you can do bucket recipes without actually filling a bucket.

Mekanism's crafter similarly has stocking mode, but does not automatically handle re-usable items intelligently, so you'd have to build your own system with that as you would with any other crafters.
