### ISSUE TITLE
New early mod farm tools

### ISSUE THREAD

**Issue by TheAnimaDust** [EnigmaticaModpacks/Enigmatica9#172]
### URL

https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils

### Why would you like the mod added?

I like mob grinding and it can have a nice place in early mob farms but i think dark utilities can be used too.
I don't think the mob crusher can be considered early.

**Comment by NielsPilgaard** [comment]
I'm fairly certain we have alternatives already, Spikes come to mind. I don't think we have a need for Mob Grinding Utils.

**Comment by MuteTiefling** [comment]
A create deployer works wonders for this. PNC drones too, or ars nouveau drygmies.
