### ISSUE TITLE
Ancient slabs not craftable

### ISSUE THREAD

**Issue by wunderfitzig** [EnigmaticaModpacks/Enigmatica9#173]
### Modpack Version

1.3.0

### Describe your issue.

Ancient slabs are not craftable. The only recipe available for them is their vertical counterpart.  Slabs are also needed to create ancient rods to be able to create tools, which are all blocked by the slabs not being craftable.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Wunderfitzig#0474

**Comment by MuteTiefling** [comment]
Thanks for the report. We'll get that fixed up.
