### ISSUE TITLE
[Mod Suggestion] Integrated Dynamics

### ISSUE THREAD

**Issue by LemonShaped** [EnigmaticaModpacks/Enigmatica9#178]
### URL

https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics

### Why would you like the mod added?

(Along with [Integrated tunnels](https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels), [Integrated nbt](https://www.curseforge.com/minecraft/mc-mods/integrated-nbt), and maybe [Integrated Terminals](https://www.curseforge.com/minecraft/mc-mods/integrated-terminals) and [Crafting](https://www.curseforge.com/minecraft/mc-mods/integrated-crafting))

Allows you to build complex networks for incredible automation and stuff.
Addmittedly its a bit hard to get into, but I love this mod and would be happy to see it make it in to this modpack!

**Comment by MuteTiefling** [comment]
No thank you.
