### ISSUE TITLE
Frozen Up

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica9#18]
### URL

https://www.curseforge.com/minecraft/mc-mods/frozen-up

### Why would you like the mod added?

It adds a very cute snow animal (the Chiloo) that can be tamed (it can use the Domestication Innovation collar and beds) and left to wander for Truffles. It also adds a few ice decorative blocks.

It doesn't add much to be perfectly honest, but the Chiloos are very cute.

**Comment by NielsPilgaard** [comment]
I recall saying no to this in the past, due to lack of content maybe? Either way, it's a no :)

**Comment by Lykrast** [comment]
Understandable.
