### ISSUE TITLE
Witch Hazel slabs not craftable

### ISSUE THREAD

**Issue by wunderfitzig** [EnigmaticaModpacks/Enigmatica9#180]
### Modpack Version

1.3.0

### Describe your issue.

Like with Ancient wood, witch hazel slabs are not craftable.  Only able to convert from horizontal slabs to vertical slabs and vice versa.  Cannot be created with wood.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Wunderfitzig#0474

**Comment by MuteTiefling** [comment]
Weird. Guess I'll need to take a pass over all the slabs.

**Comment by MuteTiefling** [comment]
Looks like it's every single BYG and BlueSkies wooden slab...
Seems like it might be an EveryCompat bug. Needs more investigation.

**Comment by MuteTiefling** [comment]
Yep: https://github.com/MehVahdJukaar/WoodGood/issues/97

**Comment by wunderfitzig** [comment]
Ahhh yeah that'll do it

**Comment by MuteTiefling** [comment]
Right, so we're one version behind here, which is the crux of the issue. 

Vertical Slabs were removed from EveryCompat in the very next version. That has all been moved over to [VerticalSlabsCompat](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat). Updating and adding that should fix the issue.

**Comment by NielsPilgaard** [comment]
Fixed in-dev then :D
