### ISSUE TITLE
Starbuncle Mania

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#187]
### URL

https://www.curseforge.com/minecraft/mc-mods/starbunclemania

### Why would you like the mod added?

Greatly expands the functionality of Starbuncles in ways that I think will be quite useful such as 

- Mekanism gas transport
- FE transport
- Fluid transport
- Potion transport from things like Create brewing to potion jars (currently only possible with Wixie brewing or silly machines to right click potions on jars)

Can't test it out currently, so leaving this as a reminder to myself to take a look when I can.

**Comment by MuteTiefling** [comment]
Seems pretty solid aside from one small bug which I'm sure will be cleared up soon enough: https://github.com/Alexthw46/StarbuncleMania/issues/1

I think this would be a nice add for folks looking to have a more magical themed base as starbuncles would be able to handle a lot of basic logistics for them.

**Comment by theboo** [comment]
My dream mod
