### ISSUE TITLE
Local modpack suddenly unaligned with server pack

### ISSUE THREAD

**Issue by PurplePickard** [EnigmaticaModpacks/Enigmatica9#197]
### Modpack Version

Enigmatica 9 v1.3.0

### Describe your issue.

Was on my server running this pack yesterday, completely fine. Try to connect today, and it tells me that the Thermal Series is a different version even though it shows it as the same version and won't let me connect. 
I've changed nothing in the 12 hours since last being on the server. I've restarted the server, didn't fix it. 

![image](https://user-images.githubusercontent.com/91899052/211039388-636f3b94-6cda-4a47-b3b9-e20854a86847.png)
 I've attached the image of the error it shows when trying to connect.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

Could you please provide your `latest.log` from the login attempt? Preferably from both client and server.

**Comment by CrystalSpore** [comment]
I'm not the OP, but I'm running into this issue as well. Here is the latest.log: https://pastebin.com/4n6AQb91

Hope this is helpful

**Comment by CrystalSpore** [comment]
Just realized you asked for both client & server. The above is for the client, & attached is for the server:
[server_latest.log](https://github.com/EnigmaticaModpacks/Enigmatica9/files/10738786/server_latest.log)

**Comment by NielsPilgaard** [comment]
Strange, it seems `thermal:fluid_reservoir` is missing from server or client. Please update to 1.4.0 and see if the issue persists, we're quite a few Thermal updates behind on 1.3.0

**Comment by CrystalSpore** [comment]
I'm running a Bisect Hosting server, which doesn't have 1.4.0 available yet. I also tried manually updating the server files to no avail.

As soon as Bisect Hosting has updated, I'll be testing it out & report back if I run into any issues.

Thanks for your time!

**Comment by NielsPilgaard** [comment]
It should be available on Bisect Hosting now :)
