### ISSUE TITLE
cc-tweaked-1.19-1.100.7.jar

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica9#2]
### URL

https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

### Why would you like the mod added?

It got removed because of https://github.com/cc-tweaked/CC-Tweaked/issues/1108 (which is now fixed, i would really appreciate it being added back)

**Comment by NielsPilgaard** [comment]
We're gonna leave ComputerCraft and addons out this time around :)
