### ISSUE TITLE
Chunk loading doesn't work properly, `limitedchunks` seems to be to blame.

### ISSUE THREAD

**Issue by sniggyfigbat** [EnigmaticaModpacks/Enigmatica9#205]
### Modpack Version

1.3.0

### Describe your issue.

I've been running a dedicated server on a friend's machine, and we've been encountering some very weird behaviour with chunk loading. Chunks don't stay loaded consistently, which is particularly noticeable when moving from our lava-based power setup in the Nether to our base in the Overworld: sometimes the power will keep flowing for a bit, but often it just cuts off immediately. This definitely happens because the Nether chunks are getting unloaded, as the power restarts as soon as someone reenters the Nether and the chunks get reloaded.

This *does not* appear to be the intended LimitedChunks behaviour, and has nothing to do with my logging off or anything. However, the behaviour replicates when chunks are supposed to be loaded with FTBUtilities, or Mekanism anchor upgrades, or both, suggesting that it very likely to be something interfering with the core Forge chunk loading API.

(Obviously, I've checked all the config files, and chunk-loading is configured correctly in both `ftbchunks.sntb` (I **have** modified `force_load_mode: "always"`, which didn't help) and Mekanism's `general.toml`. Aside from `ftbchunks.sntb`, I have changed no config files.)

While checking all the config files, I noticed that `limitedchunks` existed, and was immediately suspicious of it. I disabled it by removing the `.jar` and setting `"required":  false` in the manifest, and upon rebooting the server the issues seemed to be immediately resolved (including the Nether chunks loading automatically before anyone visited the Nether).

As such, I think `limitedchunks` is buggered.

This is particularly annoying given that, as an operator of a small private server, there is **no** situation in which I would `limitedchunks` to be running; it adds no value to me and is extremely dangerous when using Mekanism nuclear reactors (which REALLY don't like having bits of their loop get arbitrarily unloaded). Please could this mod be removed or disabled by default? From my perspective, it's bad even when working correctly.

### Latest Log

https://gist.github.com/sniggyfigbat/740be46957ec92d226eb2b28cd12f2c4

### Have you modified the modpack?

Yes

### User Modifications

I've changed `ftbchunks.sntb` as follows:
```
{
	# Forced modes won't let players change their ally settings
	# Default: "default"
	# Valid values: "default", "forced_all", "forced_none"
	ally_mode: "default"
	
	# Allow players to force-load chunks while they are offline. This may not take effect until each player re-logs in server, for immediate effect use 'force_load_mode'
	# Default: true
	chunk_load_offline: true
	
	# Blacklist for dimensions where chunks can't be claimed. Add "minecraft:the_end" to this list if you want to disable chunk claiming in The End
	# Default: []
	claim_dimension_blacklist: [ ]
	
	# Disables all land protection. Useful for private servers where everyone is trusted and claims are only used for forceloading
	# Default: false
	disable_protection: true
	
	# Override to disable/enable fake players like miners and auto-clickers globally. Default will check this setting for each team
	# Default: "check"
	# Valid values: "check", "deny", "allow"
	fake_players: "allow"
	
	# Minimap for clients connecting to this server will be disabled
	# Default: false
	force_disable_minimap: false
	
	# Control how force-loaded chunks work
	# Default: "default"
	# Valid values: "default", "always", "never"
	force_load_mode: "always"
	
	# Max claimed chunks.
	# You can override this with FTB Ranks 'ftbchunks.max_claimed' permission
	# Default: 500
	# Range: -∞ ~ +∞
	max_claimed_chunks: 500
	
	# Max force loaded chunks.
	# You can override this with FTB Ranks 'ftbchunks.max_force_loaded' permission
	# Default: 25
	# Range: -∞ ~ +∞
	max_force_loaded_chunks: 500
	
	# Requires you to claim chunks in order to edit and interact with blocks
	# Default: false
	no_wilderness: false
}
```

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report.

Limited Chunks should be unloading chunks when the player that owns the chunkload ticket is offline, were you both online during the error?

**Comment by sniggyfigbat** [comment]
I was the one who claimed the chunks, and yes, I was online. HOWEVER, we are using an FTBUtils team or whatever they're called, so we can all access the same chunks, and the person who founded the team hasn't been online much - possibly that might be related to the issue?

**Comment by theboo** [comment]
In 1.16 ftb chunks of the team owner is offline, the whole team's chunks are unloaded even if a teammate is online.. id hoped they changed that by now but I guess not

**Comment by NielsPilgaard** [comment]
Reported :)

**Comment by NielsPilgaard** [comment]
Desht answered my report with a great explaination, and I think the best solution here is to simply remove Limited Chunks, so that's what I'll do :)
