### ISSUE TITLE
[Mod Suggestion] FTB: IC

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#21]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge/files

### Why would you like the mod added?

*It's still not ported onto 1.19.2, but port is being made looking at the fact 1.19 version is out*

FTB:IC is a mod from FTB team inspired by good old IC2. Ads most of IC2 machines, gives back EU (well differently named, but works the same), new textures, new content as well :D

Was already in E8 😉

**Comment by NielsPilgaard** [comment]
I'd rather not have it in, we're trying to keep E9 light, and FTB:IC has no role to play in expert progression.

**Comment by Kanzaji** [comment]
Yea, same told me Motoko 😅 Well sad, I would love to have IC2 back in some expert modpack at some point, but it is what it is.
