### ISSUE TITLE
Eccentric Tome should not have the Blue Skies Book

### ISSUE THREAD

**Issue by Pipeline929** [EnigmaticaModpacks/Enigmatica9#212]
### Describe your suggestion

Upon getting the Eccentric Tome from the quests it has the Blue Skies manual in it, but when you open the Blue Skies book it is added to your inventory as a tab and the entire Eccentric Tome book is consumed in the process leaving the player without the other manuals. Granted you can always craft the manuals for the other mods but being given a book with them in it only to have a miss click or not having the forethought/knowledge that this outcome can happen can leave the player without the other manuals that they just received.

### Why would you like this added/changed?

newer players as well as players who are just unfamiliar with Blue Skies, or perhaps a misclick (as I just did before writing this) will leave the player without the other manuals that they just received from the quest book. If not to remove the Blue Skies manual but to add a "hint" to the player in the quest book entry, I see it shows how to "throw" a book out that you have selected so maybe just add a "you should try it with the "blue journal". " or something of the sort.

**Comment by MuteTiefling** [comment]
Opening the blue skies book the first time destroys it and adds it to your inventory screen.

This would destroy all of your books.

**Comment by MuteTiefling** [comment]
Thanks. Clarifying the title, however, as it should simply be removed from it.
