### ISSUE TITLE
Nomadic Tents

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#217]
### URL

https://www.curseforge.com/minecraft/mc-mods/nomadic-tents

### Why would you like the mod added?

Would be extremely useful for early game exploration as it creates pocket dimensions where one can safely store their stuff.

One kinda major issue right now that I hope can be fixed quickly: https://github.com/skyjay1/Nomadic-Tents/issues/73

If not, it would be simple to prevent bed placement/use in the dimension.

**Comment by NielsPilgaard** [comment]
I'm all for it, we've not added it in the past due to bugs. Fingers crossed that one can be fixed so we can add it 👍

**Comment by MuteTiefling** [comment]
Death bug actually appears to be on our end. Was just play testing some changes and died and had it happen without nomadic tents...

Also can reproduce without enigmatic graves.

**Comment by NielsPilgaard** [comment]
Oh, shit 😅

**Comment by MuteTiefling** [comment]
Seems to be an issue with Login Protection and the way it's handling dimension changes. Could use some extra confirmation as I'm on cold meds and lacking sleep, so it's very possible I'm overlooking something

**Comment by NielsPilgaard** [comment]
I was unable to reproduce this issue with Login Protection.
