### ISSUE TITLE
[Mod Suggestion] Tetra 

### ISSUE THREAD

**Issue by ToxinZangoose** [EnigmaticaModpacks/Enigmatica9#221]
### URL

https://www.curseforge.com/minecraft/mc-mods/tetra/files/4370833

### Why would you like the mod added?

Since it has been in previous Enigmatica modpacks, I'd love to use Tetra again since it has been updated to 1.19.2. I know it says it's in Alpha stage, but it runs perfectly from what I've tested.

Love the Enigmatica packs to bits, hope to see more in the future!

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion.

We've decided not to include Tetra this time around, we're trying to keep the modpack slim :)
