### ISSUE TITLE
Mekanism craft fails if an item has NBT data

### ISSUE THREAD

**Issue by wardenplays** [EnigmaticaModpacks/Enigmatica9#228]
### Modpack Version

1.3.0

### Describe your issue.

Trying to craft the Basic Smeltery factory with the Energized Smelter I had already used for a bit did not work. The only thing I could see that would have stopped it is the Smelter having energy still in the block. I spawned in a fresh Smelter without energy and the craft worked.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Warden#9639

**Comment by NielsPilgaard** [comment]
Please update to 1.4.0 and see if the issue persists :)

**Comment by MuteTiefling** [comment]
Closing as this is very stale.
