### ISSUE TITLE
Cannot connect to server on version 1.4.0

### ISSUE THREAD

**Issue by CrystalSpore** [EnigmaticaModpacks/Enigmatica9#229]
### Modpack Version

1.4.0

### Describe your issue.

After upgrading from 1.3.0 to 1.4.0 myself & my server teammate started running into an issue that prevented connection. Every time we tried to connect, we would receive
```
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class cofh.lib.util.crafting.IngredientWithCount cannot be cast to class dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient (cofh.lib.util.crafting.IngredientWithCount is in module cofh_core@10.2.1 of loader 'TRANSFORMER' @26c7b1c6; dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient is in module kubejs@1902.6.0-build.142 of loader 'TRANSFORMER' @26c7b1c6)
```
when trying to connect to the server. We were using a modified pack, so I tested with a clean server install both on Bisect Hosting & from localhost, & in both cases with a clean install of server & client I'm still running into these issues.

Steps to reproduce:
1) install fresh 1.4.0 client
2) install fresh 1.4.0 server
3) try to connect to 1.4.0 server
4) fail due to above mentioned error

Client & Server latest.log included below for debugging purposes.

[client_latest.log](https://github.com/EnigmaticaModpacks/Enigmatica9/files/10750828/client_latest.log)
[server_latest.log](https://github.com/EnigmaticaModpacks/Enigmatica9/files/10750824/server_latest.log)

### Latest Log

Included both client & server in post above

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

SNReloaded#0001

**Comment by NielsPilgaard** [comment]
Oh boy, we'll get that fixed asap 😅

**Comment by Kanzaji** [comment]
So update on this for anyone curious 😅
We found out the cause of the issue, temporary fix is to remove two files in `kubejs\server_scripts\base\recipes\thermal` called `refinery.js` and `smelter.js`, and more pernament fix is on the way, we are just waiting for Thermal Devs to release a fix 😄

Also yes, ignore the PR above, that didn't fully work, and Thermal devs are working on this >.>

**Comment by astridos2go** [comment]
Worked like a charm! Thanks for the fix!
