### ISSUE TITLE
Market is Missing Necessary Seeds (1.4.0)

### ISSUE THREAD

**Issue by anivlys** [EnigmaticaModpacks/Enigmatica9#230]
### Modpack Version

1.4.0

### Describe your issue.

The Farming for Blockhead's Market does not contain all of the modded seeds. It appears to be missing Thermal's, IE's, and most importantly, Occultism's Demon's Dream Seeds.

The market currently has seeds from Vanilla, Blue Skies, and Farmer's Delight. If BYG saplings are supposed to be in the market, they are not there as well. Saplings are Vanilla, Blue Skies, and Quark.

A small recommendation as well, if it is intended for Demon's Dream Seeds to be obtained from the market it might be best to make a note of that in the first quest. As the quest just mentions using Occultism's book, but the book just says to break grass.

*Issue is on a new world with a clean install of 1.4.0.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report, should be all fixed up for next release.
