### ISSUE TITLE
Crimson altar fails to convert gold to tainted gold

### ISSUE THREAD

**Issue by arisgoun** [EnigmaticaModpacks/Enigmatica9#240]
### Modpack Version

1.19.2

### Describe your issue.

The altar is built correctly in the nether and particles are shown from the four pillars.

But placing a gold ingot does not convert it. I waited for 3 minutes minimum... 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
The altar I just put in the nether is working fine.

Make sure that the altar has turned red as shown and has Aura in it
![image](https://user-images.githubusercontent.com/9543430/221247350-1b45c1a3-f196-4ded-a0ac-319b2fea6134.png)
you need an Environmental Eye or Ocular to see this.

**Comment by arisgoun** [comment]
I checked again, with the Environmental Eye. Aura level is at 25% approx., The altar is red. 

My Overworld altar is also at aura 25% and works fine.

Is the biome affecting it? In the nether I have it at a Quartz Desert biome.

**Comment by MuteTiefling** [comment]
When you look at the altar, how much does it show though? That's what's important.

![image](https://user-images.githubusercontent.com/9543430/221257681-7f3fedf0-41f7-4f98-b14d-e73f055fd8a6.png)


Otherwise the only advice I can offer is to break the main altar block and re-place it.

**Comment by arisgoun** [comment]
To fix a mistake, my version is 1.3.0

I tried breaking and replacing the altar block, no success.

This is what I see:
![2023-02-25_10 59 53](https://user-images.githubusercontent.com/70166657/221351132-200ef484-5d31-4b86-b9d7-2815d757d2e8.png)

**Comment by MuteTiefling** [comment]
Ok. We recently released a major update. I'd suggest updating and trying again because that version is very old

**Comment by arisgoun** [comment]
I am using the latest release version ...
![version](https://user-images.githubusercontent.com/70166657/221362204-ffa64cd1-f531-41c2-ac2d-d53a07b7e4c1.png)

**Comment by MuteTiefling** [comment]
Yes, please update to 1.4.1 and see if the issue persists.

**Comment by arisgoun** [comment]
The update fixed the issue :-)
