### ISSUE TITLE
Cannot create Transmutation Catalyst

### ISSUE THREAD

**Issue by arisgoun** [EnigmaticaModpacks/Enigmatica9#243]
### Modpack Version

1.4.2 Beta

### Describe your issue.

Using Ritual of the Forest, I am trying to create the Transmutation Catalyst.

It fails, whether I grow the tree using bonemeal or wait for it to grow naturally.
The ritual items stay on the pillars and they are not consumed.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report.

I'm unfortunately unable to reproduce the issue.

Double check your inputs:

- Infused Rock
- Glowstone (Block)
- Ingot of the Skies
- _Golden_ Stone Bricks
- Gold Leaf
- Brewing Stand

And be sure the sapling is correct. It requires a Jungle Sapling.

Also, double check that your Gold Powder is set correctly

![image](https://user-images.githubusercontent.com/9543430/221432228-fbebed22-9399-47b6-8674-b9042d52ac78.png)

**Comment by arisgoun** [comment]
Ido it exactly like this.

![2023-02-27_17 52 06](https://user-images.githubusercontent.com/70166657/221628075-51637c2b-957e-409d-9204-b82efbd6e7fc.png)
(Minus the sapling at the centre)

**Comment by MuteTiefling** [comment]
What sapling?

**Comment by arisgoun** [comment]
?

To do the Ritual of the Forest, a sapling is needed in the middle.
When the tree grows, the ritual completes by consuming the items on the pillars and dropping the expected item.

I use oak saplings.

**Comment by Darkere** [comment]
> And be sure the sapling is correct. It requires a Jungle Sapling.
