### ISSUE TITLE
No recipe for Immersive Engineering Item Silo 

### ISSUE THREAD

**Issue by arisgoun** [EnigmaticaModpacks/Enigmatica9#244]
### Modpack Version

1.4.2 Beta

### Describe your issue.

Immersive Engineering Item Silo cannot be crafted, no recipe in JEI

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
IE multiblocks have never shown in jei. They're listed in the engineers manual.
