### ISSUE TITLE
Mob Depawn Timers

### ISSUE THREAD

**Issue by Shadows-of-Fire** [EnigmaticaModpacks/Enigmatica9#245]
### URL

https://beta.curseforge.com/minecraft/mc-mods/mob-despawn-timers

### Why would you like the mod added?

MDT fixes the issue where mobs instantly despawn if there are no players in the area, which breaks farms that should normally operate without players.

There's a 1.18 version as well, so this can go into E8 and E9, but I'm not sure if I should bother making a separate post on the E8 repo.

**Comment by NielsPilgaard** [comment]
Added to both in-dev, thanks 👍
