### ISSUE TITLE
Add Botany Pot and Botany Trees

### ISSUE THREAD

**Issue by BMK2** [EnigmaticaModpacks/Enigmatica9#246]
### URL

https://www.curseforge.com/minecraft/mc-mods/botany-pots

### Why would you like the mod added?

Second mod here: https://www.curseforge.com/minecraft/mc-mods/botany-trees

I would like this mod added because the automation of plants is nice but specifically trees. Chopping down entire forests to fund some of my larger projects becomes visually destructive and time-consuming.

**Comment by MuteTiefling** [comment]
We already have plenty of methods for automating these tasks. No thank you.
