### ISSUE TITLE
Anthill Inside

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica9#248]
### URL

https://www.curseforge.com/minecraft/mc-mods/anthill-inside

### Why would you like the mod added?

**A N T S**` `**F A C T O R Y**

**Comment by MuteTiefling** [comment]
Amusing, but could you expand on why you want it? It looks to me like a pretty limited auto crafting and logistics mod on the order of what several mods in the pack can already do.
