### ISSUE TITLE
Add Snowy Spirt 

### ISSUE THREAD

**Issue by yoyotam3** [EnigmaticaModpacks/Enigmatica9#250]
### URL

https://www.curseforge.com/minecraft/mc-mods/snowy-spirit

### Why would you like the mod added?

Just a fun mod that adds sleds. It also adds some christmas-themed stuff but I believe that can all be disabled.
EDIT: I forgot to mention that I believe mobs form other mods can also be allowed to pull sleds which is cool.

**Comment by NielsPilgaard** [comment]
Very cute, but we have no need for it in the pack I'm afraid.
