### ISSUE TITLE
[DISABLED ITEM] Raw Pendorite

### ISSUE THREAD

**Issue by Juknum** [EnigmaticaModpacks/Enigmatica9#256]
### Modpack Version

1.5.0

### Describe your issue.

I just got raw pendorite from mining it in the nether.

![image](https://user-images.githubusercontent.com/49886317/222984461-3f84757e-bcc8-47d7-8fd2-9b10882f6a4c.png)
![image](https://user-images.githubusercontent.com/49886317/222984467-d222c741-727b-41ac-8f61-5572d819c961.png)

### Crash Report

No crash

### Latest Log

Not needed

### Have you modified the modpack?

No

### User Modifications

Nope, default settings

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Juknum#0021

**Comment by MuteTiefling** [comment]
Thanks for the report. This should get properly disabled when @Kanzaji finishes the ore unification PR they're working on.
