### ISSUE TITLE
Candle quest in occultism requires disabled item 

### ISSUE THREAD

**Issue by zLc362** [EnigmaticaModpacks/Enigmatica9#258]
### Modpack Version

1.5.0

### Describe your issue.

As the title says, the candle quest in the occultism chapter requires a disabled item to complete

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. I'll get that fixed up soon.
