### ISSUE TITLE
To be removed: schematics references in questbook

### ISSUE THREAD

**Issue by Nidaelie** [EnigmaticaModpacks/Enigmatica9#259]
### Modpack Version

Quest: harnessiga aura in natures aura section

### Describe your issue.

that quest refers to schematics inside the folder in the last pargraph of the quest text

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report. I'll get this fixed up
