### ISSUE TITLE
[Mod Suggestion] FTB Ultimine!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#26]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge/files/all?filter-game-version=2020709689%3A9366

### Why would you like the mod added?

FTB Ultimine was ported recently onto 1.19.2!

**Comment by TemperedFool** [comment]
No chance we give Ultimine a miss and let all those awesome tools breath?

**Comment by Kanzaji** [comment]
Why not :smile:
However im pretty sure people will ask about it for some time :sweat_smile:

**Comment by MuteTiefling** [comment]
> No chance we give Ultimine a miss and let all those awesome tools breath?

This is where I'm leaning, personally.

**Comment by NielsPilgaard** [comment]
Yeah let's try without this time around. We have easy to make hammers and excavators for early game, and we'll have plenty of options for mid-late.

**Comment by Kanzaji** [comment]
Alrighty :smile:
