### ISSUE TITLE
Emerldite Ore Spawning in Nether

### ISSUE THREAD

**Issue by legionpete** [EnigmaticaModpacks/Enigmatica9#260]
### Modpack Version

1.5.0 / 1.19.2

### Describe your issue.

Found emeraldite in nether and it said disabled but please report

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

legionpete#0477

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
