### ISSUE TITLE
Adjust Mekanism wind generator height

### ISSUE THREAD

**Issue by shadydeath** [EnigmaticaModpacks/Enigmatica9#262]
### Describe your suggestion

The current configuration for Mekanism Wind Turbine is set to 2031 y for max efficiency.
My suggestion would be to tone it down within Minecraft 1.19.2's build limit (320 y)

### Why would you like this added/changed?

More logical adjustment for wind power generation to be able to reach peak efficiency rather then having it be impossible.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. @MuteTiefling bug or intentional? 😅

**Comment by MuteTiefling** [comment]
Pretty sure it's just an odd default, but I wanted to adjust it anyway
