### ISSUE TITLE
Terralith

### ISSUE THREAD

**Issue by Zarrexx** [EnigmaticaModpacks/Enigmatica9#266]
### URL

https://www.curseforge.com/minecraft/mc-mods/terralith

### Why would you like the mod added?

I know the pack already has BYG, but I can't help but keep thinking of this mod. The biomes look incredible and give the game a whole new look compared to the BYG/BoP style biomes. I was told that there may have been performance issues with the mod (or you guys just don't want to change biome mods), but I figured I would make a suggestion for it anyway because it just looks so cool.

**Comment by NielsPilgaard** [comment]
Terralith is amazing, but worldgen load is awful as it is, I don't want to make it worse :P
