### ISSUE TITLE
Enigmatic 9 - Lava Bucket Dupe

### ISSUE THREAD

**Issue by legionpete** [EnigmaticaModpacks/Enigmatica9#269]
### Modpack Version

1.5.0

### Describe your issue.

Found a lava bucket dupe that needs to be addressed.
1. Using lava above drip stone to drip lava into cauldrons.
2. Using create fluid pump to pump lava into functional storage fluid drawer from the cauldrons. (Storage drawer has diamond upgrade but I don't believe that is relevant)
3. Attempted to take bucket and transfer lava from Mekenism Basic fluid tank into functional storage fluid drawer.
4.  Bucket empties, then, empty bucket overrides shields (lost my shield in this exchange)  But then gives me a full lava bucket back in the same hand I had when I started the process. 
5. Moving the newly created empty bucket from the shield box alllows for another empty bucket to be placed in the shield slot when you again empty the new full lava bucket into the fluid box. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

legionpete#0477

**Comment by MuteTiefling** [comment]
Thanks for the report. 

I'm unfortunately unable to produce this, so I'm thinking there must be some other trigger involved.

The part that feels critical is

1. Pump Lava into Fluid Drawer using Create pipes.
2. Get a bucket of lava from some other source
3. Attempt to manually put bucket of lava into Fluid Drawer from step 1
4. Dupe?

I've tried with and without a shield equipped. In both cases, I can insert a bucket of lava into the Fluid Drawer without fault.

Perhaps some screenshots could help? Or if you're able to record a short clip and put it on something like Streamable, Gyazo, or Youtube

**Comment by MuteTiefling** [comment]
And of course, right as I type that it starts happening!

**Comment by MuteTiefling** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/165
