### ISSUE TITLE
Radium causes Blue Skies portals to not function

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#27]
### Modpack Version

indev

### Describe your issue.

Noticed these portals stopped working recently (you step in and go to 'loading' forever, no crash). Turns out it's a known issue. https://www.curseforge.com/minecraft/mc-mods/blue-skies/pages/faq

Issue went away when I removed Radium. https://github.com/Asek3/Radium/issues/1

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Replaced with Canary, let's see how that works out :P

**Comment by brucethemoose** [comment]
Found a fix for BlueSkies + Radiium: add `mixin.ai.poi=false` to the radium config file. 

I can't replicate the everdawn issue in Radium. I placed a bunch of portals close to each other and far away, and they all seem to send me to the right spot.

**Comment by NielsPilgaard** [comment]
Disabling Radium functionality isn't really a fix, it's similar to just removing the mod :P
