### ISSUE TITLE
Deadlock when blocking Piercing Crossbow shots

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#270]
### Modpack Version

1.5 dev

### Describe your issue.

Same issue as https://github.com/EnigmaticaModpacks/Enigmatica8/issues/222 persists. Creating issue for tracking purposes. 

Already reported to Parry: https://github.com/Drullkus/Shield-Parry/issues/11

Have been able to confirm this is still an issue in 1.19 and removing Parry resolves the issue. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by dineev-vd** [comment]
Seems fixed in 2.4.3
https://github.com/Drullkus/Shield-Parry/issues/11#issuecomment-1494996209
