### ISSUE TITLE
Add recipe to turn soul steel block into ingots

### ISSUE THREAD

**Issue by telomar** [EnigmaticaModpacks/Enigmatica9#273]
### Describe your suggestion

Currently you can craft 9 soul steel ingots into a block, but you cannot craft the block back into ingots.

### Why would you like this added/changed?

Being able to bulk make the soul steel blocks and then craft them down to ingots would be convenient.

**Comment by MuteTiefling** [comment]
Fixed in dev already :D Thanks for the report!
![image](https://user-images.githubusercontent.com/9543430/226766792-6735782c-f930-40ad-b115-3ffacd0b5f30.png)
