### ISSUE TITLE
tomato sauce is craftable

### ISSUE THREAD

**Issue by telomar** [EnigmaticaModpacks/Enigmatica9#280]
### Modpack Version

1.5

### Describe your issue.

JEI says tomato sauce from thermal should be disabled:
![image](https://user-images.githubusercontent.com/128550940/227064118-039b8e8a-d9a3-4809-b9e6-65a7867099b1.png)

I crafted it with farmer's delight tomatoes, grown from farmer's delight seeds I got from the market.
![image](https://user-images.githubusercontent.com/128550940/227064402-a3c96ff0-1c0f-4592-9eb8-c60a1c4c572b.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

telomar#6925

**Comment by MuteTiefling** [comment]
Thanks for the report. We'll get that fixed up soon
