### ISSUE TITLE
Hexerei infused fabric block recipe producing fewer blocks than stated

### ISSUE THREAD

**Issue by ArcaneDefence** [EnigmaticaModpacks/Enigmatica9#284]
### Modpack Version

1.5.0

### Describe your issue.

JEI says the recipe produces 8 blocks, but crafting it produces one.
![image](https://user-images.githubusercontent.com/51932756/228019215-cd01cc66-e094-4f0d-b7fe-2f26e006fad6.png)
![image](https://user-images.githubusercontent.com/51932756/228019570-ad3f0d7a-f33c-453d-9d81-ba8241b54522.png)
![image](https://user-images.githubusercontent.com/51932756/228019653-c1645d70-6053-4053-98d3-ca9d4437cb01.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
https://github.com/JoeFoxe/Hexerei-1.18/issues/90

**Comment by MuteTiefling** [comment]
Thanks for the report!

**Comment by MuteTiefling** [comment]
Wrong tracker! https://github.com/JoeFoxe/Hexerei-1.19/issues/30

**Comment by MuteTiefling** [comment]
Issue has been fixed in hexerei-0.3.0. We'll get that in the next release
