### ISSUE TITLE
ManyIdeas Doors

### ISSUE THREAD

**Issue by BMK2** [EnigmaticaModpacks/Enigmatica9#285]
### URL

https://www.curseforge.com/minecraft/mc-mods/manyideas-doors

### Why would you like the mod added?

As a lover of tall ceilings for my buildings, it often feels weird to have such a small entrance. I usually end up having to design a 4-block-high "door" out of other materials but this leads to me having to worry about mobs walking into my buildings. Adding this mod would allow the use of taller doors and a wider variety of doors than already exists.

**Comment by NielsPilgaard** [comment]
If it was just doors then I'd be inclined to say yes, but it looks like it's core mod adds a ton as well. 
I'll have a look, but I think it's gonna end as a no.

**Comment by NielsPilgaard** [comment]
I can't get double doors to open 😅 so that's.. a deal breaker. If it gets resolved we can add it, I like it in it's current state.
https://github.com/GeheimagentNr1/ManyIdeasDoors/issues/3

**Comment by GeheimagentNr1** [comment]
The issue [GeheimagentNr1/ManyIdeasDoors#3](https://github.com/GeheimagentNr1/ManyIdeasDoors/issues/3) with the double door feature of Quark is fixed with version 1.2.3 and the deployment to CurseForge is running.

**Comment by NielsPilgaard** [comment]
Sweet, thanks for the heads up!
