### ISSUE TITLE
Ars nouveau update to 3.13.0 for the next update of Enigmatica 9

### ISSUE THREAD

**Issue by peisach** [EnigmaticaModpacks/Enigmatica9#288]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4468989

### Why would you like the mod added?

The latest version of Ars Nouveau supposedly adds a new storage system that I would like to try in Enigmatica 9.  Would it be possible to add it to the next update to the modpack?

Thank you.

**Comment by MuteTiefling** [comment]
Don't worry, it will be. Quests are already updated for it.

**Comment by MuteTiefling** [comment]
https://github.com/EnigmaticaModpacks/Enigmatica9/pull/287

**Comment by peisach** [comment]
> Don't worry, it will be. Quests are already updated for it.

Thanks.
