### ISSUE TITLE
Soul gem can duplicate mobs from containment jars

### ISSUE THREAD

**Issue by telomar** [EnigmaticaModpacks/Enigmatica9#294]
### Modpack Version

1.5

### Describe your issue.

**Description**

When using an occultism soul gem on an occupied containment jar, it spawns the contained entity into the world.  The jar continues to house the originally contained entity, and if you break and replace the jar you can repeat the process.  

**How to reproduce**

1. Use the ritual of containment to capture a mob in a containment jar
2. Use a soul gem on the occupied containment jar - this spawns a duplicate of the contained entity into the world

The jar can then be broken and replaced to repeat the process.  

I tried this with endermen and the air mage found in the end.  The air mages become non-apotheoisis versions except for the most recently spawned.  It cannot be used on any captured entities which the soul gem does not work on, such as the wither or non-mobs such as a captured egg or soul gem.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

telomar#6925

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
I've made a blacklist to prevent this using Lychee in the meantime. Hopefully a fix can be implemented in Ars Nouveau in the form of an item blacklist, however.
