### ISSUE TITLE
FTB Essentials

### ISSUE THREAD

**Issue by hezamu** [EnigmaticaModpacks/Enigmatica9#296]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge

### Why would you like the mod added?

Add this for /home and /trashcan QoL and /leaderboard coolness.

Note that the mod page says 1.18 but this is clearly incorrect as the latest release is for 1.19.

**Comment by NielsPilgaard** [comment]
We've decided not to include it, because that way server owners can choose which QoL command mod they want, and people who don't want it don't have to do anything 😄

**Comment by hezamu** [comment]
Ok, reasonable 👍
