### ISSUE TITLE
[Mod Suggestion] Advanced Peripherals

### ISSUE THREAD

**Issue by new-3** [EnigmaticaModpacks/Enigmatica9#298]
### URL

https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals

### Why would you like the mod added?

Currently I'm playing E9 especially focusing CC:Tweaked, 
I want to mess around with various kinds of gears generated by Apotheosis with CC,
but the problem is in CC you are not allowed to read NBT so there is not so much I can do with looted items, 
like sorting gears by tiers, checking their enchantments, etc.

Fortunately Advanced Peripherals gives a way to read NBT and other features plus to CC, 
so I suggest adding this mod it in the pack. Sorry if I'm being too personal. 😅

**Comment by NielsPilgaard** [comment]
Sorry but no, it's too niche, not enough players would play with it to warrant adding it.

**Comment by new-3** [comment]
Alright, I thought it could work as replacement for Integrated Dynamics but I understand.
