### ISSUE TITLE
The server hangs silently if you block a Pillager's attack with an shield while you have anything in your main hand

### ISSUE THREAD

**Issue by hezamu** [EnigmaticaModpacks/Enigmatica9#299]
### Modpack Version

1.5.0

## Steps to reproduce:
1. Create a new world (I don't think the parameters matter, but I used seed `0` and allow cheats.)
2. /gamemode creative
3. Get a shield, a sword and a Pillager spawn egg. 
4. /gamemode survival
5. Equip shield in offhand, sword in mainhand
6. Spawn the pillager
7. Block the pillager's attack with your shield --> server freezes.

## Some notes
- Noticed on a survival server but easy to reproduce in singleplayer.
- Tried with a Skeleton as well, no issues, the problem is with Pillagers.
- Any shield offhand and any item in main hand will work.
- The problem does not crash the server, everything stays frozen until the tick watchdog kills the server. 
- A multiplayer server does not report anything into `latest.log`, You may see `[spark-asyncsampler-worker-thread/WARN] [spark/]: Timed out waiting for world statistics` in the logs at some point before the watchdog kicks in, but this is not the cause of the problem.
-  You can't even exit the single player game afterwards normally as the "Saving world" phase will freeze the client permanently, you have to kill the client with the task manager.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

hezamu

**Comment by MuteTiefling** [comment]
Thanks for the report. This is the same as #270.
