### ISSUE TITLE
Fast leaf decay

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica9#3]
### URL

https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay

### Why would you like the mod added?

It was in e6, and is now updated to 1.19

**Comment by Gcat101** [comment]
Also a couple of mods I found that were in e6 but not here (yet):

* [Emojiful](https://www.curseforge.com/minecraft/mc-mods/emojiful)
* [Trash Cans](https://www.curseforge.com/minecraft/mc-mods/trash-cans)
* [Simple Discord Rich Presence](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence)
* [Dark Utilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
* [Macaw's Bridges](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
* [Macaw's Fences and Walls](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)

If anyone finds more, send them here!

**Comment by Gcat101** [comment]
[Iron chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests) have been ported, although in beta

**Comment by Gcat101** [comment]
[Kubejs](https://www.curseforge.com/minecraft/mc-mods/kubejs) also in beta

**Comment by MuteTiefling** [comment]
> [Iron chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests) have been ported, although in beta

I'd personally much rather forgo this and stick to something like sophisticated storage and/or functional storage.

**Comment by Gcat101** [comment]
[Building Gadgets](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)

**Comment by Gcat101** [comment]
A lot of FTB stuff got ported:

* [Chunks](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
* [Library](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge) (Beta)
* [Essentials](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge)
* [Teams](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
* [Ultimine](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)

**Comment by MuteTiefling** [comment]
Ok, I get the excitement, but we really don't need a reminder for every library and utility mod. :D
