### ISSUE TITLE
Simple Qol mod for villagers

### ISSUE THREAD

**Issue by Revelates** [EnigmaticaModpacks/Enigmatica9#300]
### URL

https://www.curseforge.com/minecraft/mc-mods/retraining

### Why would you like the mod added?

Just removes the unnecessary stress of having to break and replace workstations over and over again for the starter trades, the mod adds a "reroll" button only for villagers without any experience.

**Comment by NielsPilgaard** [comment]
Even though it's super tedious, I don't think we should make villager rerolling easier.
There needs to be a "price" of rerolling - it being annoying very much counts :D
