### ISSUE TITLE
Ars Scalaes and Pekhui

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica9#301]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-scalaes/files/4459241 https://www.curseforge.com/minecraft/mc-mods/pehkui/files/4461979

### Why would you like the mod added?

As discussed in discord awhile back.

Both of these mods together add shrinking and embiggening mobs using ars spells... It comes with the bonus of working with geckolib mobs(shrink does not).

With adding these I believe the shrink mod could be removed as the only other thing shrink adds is mob capturing which is covered by multiple other mods.

We could even make custom craftable tomes for normal mode if we want to let players have access to shrinking/growing without fully getting in to ars.

Soon scalaes will also have compat with hexerei for stuff like brooms made from archwood which is pretty neat.

**Comment by MuteTiefling** [comment]
The broom compat in particular seems really nice.
