### ISSUE TITLE
Decoration and Furniture Mod

### ISSUE THREAD

**Issue by BMK2** [EnigmaticaModpacks/Enigmatica9#303]
### URL

https://www.curseforge.com/minecraft/mc-mods/decoration-and-furniture

### Why would you like the mod added?

Having the ability to further decorate our bases would allow some of my players who are more inclined to basically play Sims to enjoy being on the server.

**Comment by NielsPilgaard** [comment]
I'm afraid you'll have to make use of blocks to make furniture, we've had multiple furniture mods in the modpack in the past, and they led to bad performance issues when paired with the mod EveryCompat.
