### ISSUE TITLE
Flux Networks

### ISSUE THREAD

**Issue by serratedhalo** [EnigmaticaModpacks/Enigmatica9#304]
### URL

https://www.curseforge.com/minecraft/mc-mods/flux-networks

### Why would you like the mod added?

Flux Networks has been in older versions of Enigmatica.  It's very nice to not have to run long power lines everywhere and also be able to see how much power your network is using.

**Comment by MuteTiefling** [comment]
Mekanism and Powah both have wireless options.

Energy Meters can tell you what you're using in terms of power.
