### ISSUE TITLE
Sophisticated Storage Un-Stack Item voiding

### ISSUE THREAD

**Issue by PremiumRush** [EnigmaticaModpacks/Enigmatica9#313]
### Modpack Version

Enigmatica 9 - 1.5.0

### Describe your issue.

Sophisticated Storage has a feature (Default: CTRL + Middle Mouse Button) which Un-Stacks slots affected by Stack Upgrades. That in itself is a useful feature, though it has a major issue.
If the selected storage unit (Chest or Barrel) runs out of space while un-stacking the affected slots, it voids any excess items in selected sorting order of the storage unit. This can not be un-done except one loads a backup of the save.
This is most likely a Mod-Side issue and not a Pack-Side one but it is important to note it exists.

~Rush

### Latest Log

https://gist.github.com/PremiumRush/ad228b05d33d5e8153a6c08f8d33075a

### Have you modified the modpack?

Yes

### User Modifications

Added Mods:
- Rubidium
- Magnesium/Rubidium Extras

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

PremiumRush#7040

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Having trouble with this one, as I can't even replicate the unstacking behavior.

Below, I have a barrel with a stack upgrade in it. Each slot can go to 128.

Ctrl + Middle Mouse Button does nothing, either in empty slots or full slots.

![image](https://user-images.githubusercontent.com/9543430/234270460-f39532a8-6226-4d0c-9d38-9bd23e59d590.png)

This is in a limited instance, so none of the other fancy mouse tweaks we have in the pack. Is it possible this unstack feature is from a different mod?

**Comment by PremiumRush** [comment]
Appears odd to me, 
unfortunately I am not home for the next week so I won't be able to take footage of the issue, though I am sure I can reproduce it.
My only assumption currently is that I tweaked in the controls to use MMB as a sorting option in-inventory. 
I really don't know which setting exactly that is, but I will be sure to update you here as soon as I can!

~Rush

**Comment by MuteTiefling** [comment]
Awesome, thanks! Maybe send along a copy of your `options.txt` file too. If it's a keybind difference, I can compare ours to see if there's any difference in what's bound that might explain this.

**Comment by PremiumRush** [comment]
I'll send in a copy of the options indeed!
Good luck until then,

~Rush

**Comment by P3pp3rF1y** [comment]
Just to add a bit of info I am not aware of any feature in sophisticated storage that would do unstacking or keybind that would use ctrl middle mouse so this is some other mod doing that.
