### ISSUE TITLE
Towers of the Wild

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#316]
### URL

https://legacy.curseforge.com/minecraft/texture-packs/towers-of-the-wild-reworked-datapack

### Why would you like the mod added?

More structures! :D

**Comment by NielsPilgaard** [comment]
Hmm it's a datapack. I'm not sure 🤔

**Comment by MuteTiefling** [comment]
At this point, I'm not certain a full mod is actually required for this to function well.

Is it difficult to include a datapack through curseforge? I don't remember what we needed to do for the data packs we had for the end in e6

**Comment by theboo** [comment]
Pretty sure the OG mod was just a datapack in a jar..

We have shipped datapack structures but we got permission from the author to do so(like the better end end cities and desert village in e6) we just ship them with kubejs global datapacks

**Comment by MuteTiefling** [comment]
Ooh, there's a nether/end addon to it as well: https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild-additions

**Comment by theboo** [comment]
Here's how we've shipped them in the past 

https://github.com/EnigmaticaModpacks/Enigmatica6/tree/master/kubejs/data/minecraft/structures

**Comment by NielsPilgaard** [comment]
There's a licensing issue I'm afraid: I would have to put a MIT License file in `kubejs/data` to comply with the licensing of TotW Reworked. I don't want to do that :P

**Comment by MuteTiefling** [comment]
Oh, that's icky. Fair enough!
