### ISSUE TITLE
Vanilla Raw Ores Found As Loot

### ISSUE THREAD

**Issue by anivlys** [EnigmaticaModpacks/Enigmatica9#323]
### Modpack Version

1.6.0

### Describe your issue.

When looting an Integrated Dungeons castle I found vanilla raw copper ore, raw iron ore, and raw gold ore in some of the Lootr chests.

### Have you modified the modpack?

Yes

### User Modifications

Added InventoryHUD+, this is the only change I've done.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report! @Kanzaji wanna take a crack at this? :)

**Comment by Kanzaji** [comment]
Already reworking the script 😄 Should be ready for testing in like another hour if I didn't mess up something badly

**Comment by NielsPilgaard** [comment]
I found Raw Copper still :/ it was in a Spruce Chest though, I think maybe those are hardcoded?

**Comment by Kanzaji** [comment]
Ouch >.> They have to be hard-coded then, I tested today all loot tables that are possible to find in-game, and they all worked perfectly.

**Comment by theboo** [comment]
Im guessing they're not hard coded, rather they were accidentally opened before saving the structure so they were just saved as normal chests with items in them(if for some reason the dev/builders had ToP or Jade active while building these structures, some of the chests may have been "opened" without them knowing)... We could go through all these and fix them ourself but that's a ton of structures and chests/barrels to go through, may be better to put it on their GitHub? 

The majority of chests should be good to go now, just these few that aren't actual loot chests so it's not the end of the world tbh, plus there's still many structures with vanilla ore blocks as well... At least these can all be processed the same as ee ore.

**Comment by NielsPilgaard** [comment]
> Im guessing they're not hard coded, rather they were accidentally opened before saving the structure so they were just saved as normal chests with items in them(if for some reason the dev/builders had ToP or Jade active while building these structures, some of the chests may have been "opened" without them knowing)... We could go through all these and fix them ourself but that's a ton of structures and chests/barrels to go through, may be better to put it on their GitHub?

Would you mind making that issue? :D

**Comment by theboo** [comment]
I can when I get home tonight in like 4hr, yes!

**Comment by MuteTiefling** [comment]
The ones that aren't lootr chests all have a 'lore' book in them. These books don't appear in any loot tables that I can see. That's why I'm thinking they're just stored as part of the structure data

**Comment by theboo** [comment]
Talked to the dev of the mod, it is not intentional and he had thought he had fixed most of them already but there's still a lot left. He asked for a list of chests and barrels in structures so he can do another pass. 

I'll get as many as I can but I could use some help finding them all and generating a list, don't have the time I used to have, and the time I do have I would rather play with the fam than track down bugs haha.

**Comment by MuteTiefling** [comment]
I'd bet we can just parse the structure files with kube and spit out a list. Will see what I can find.
