### ISSUE TITLE
Structures Generate With Disabled Blocks (Integrated Dungeons)

### ISSUE THREAD

**Issue by anivlys** [EnigmaticaModpacks/Enigmatica9#324]
### Modpack Version

1.6.0

### Describe your issue.

I found quark storage crates as part of the generation of an Integrated Dungeons castle. The tool tip states "Disabled. Install quarkoddities to enable."

This is the structure I found them in.
![2023-04-28_17 38 42](https://user-images.githubusercontent.com/41839144/235259296-975c8ccd-0e80-49a7-a563-f2fda748feb0.png)

### Have you modified the modpack?

Yes

### User Modifications

Added InventoryHUD+, this is the only change I've done.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by anivlys** [comment]
Also this same structure has quite a few normal, i.e. not Lootr, chests inside of it, in addition to Lootr chests.

**Comment by MuteTiefling** [comment]
from what I can tell, the chests that aren't lootr contain hard coded contents rather than loot tables.
