### ISSUE TITLE
Integrated Stronghold

### ISSUE THREAD

**Issue by pyroAvatar91** [EnigmaticaModpacks/Enigmatica9#327]
### URL

https://www.curseforge.com/minecraft/mc-mods/integrated-stronghold

### Why would you like the mod added?

In line with the IDAS mod that was implemented in [ticket 315](https://github.com/EnigmaticaModpacks/Enigmatica9/issues/315#issue-1681201508), I think this mod should replace Yung's Better Strongholds mod, for pretty much all the same reasons.

The mod says it's compatible with Yung's Better Strongholds, but I see no point of having both since anyone only ever needs to find one stronghold. Based on the preview video, the scale, quality, and details would give a tremendous boost to the exploration aspect of the modpack.

**Comment by NielsPilgaard** [comment]
Damn that looks cool. Tempting!

**Comment by Zarrexx** [comment]
This looks cool as hell, I think it would be cool to replace Yung's with this. Yung's is cool but this just has more of a "grand" feel to it
