### ISSUE TITLE
Ars Elemental Recipes Using Wrong Ingots

### ISSUE THREAD

**Issue by anivlys** [EnigmaticaModpacks/Enigmatica9#328]
### Modpack Version

1.6.0

### Describe your issue.

Unable to craft recipes that require vanilla ingots (gold, netherite) because Ars Elemental does not accept the unified ingots as valid. I ran across this trying to craft a Lesser Focus and only figured it out after seeing that the gold ingots I cheated in to test did work, but my actual gold ingots did not.

minecraft:gold_ingot is valid; emendatusenigmatica:gold_ingot is not
minecraft:netherite_ingot is valid; emendatusenigmatica:netherite_ingot is not

If you were to use JEI to view recipes it becomes apparent that the vanilla gold ingot has more recipes than the unified one.

### Have you modified the modpack?

Yes

### User Modifications

Added InventoryHUD+, this is the only change.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, we're looking into it :)

**Comment by MuteTiefling** [comment]
https://github.com/AlmostReliable/almostunified/issues/45
