### ISSUE TITLE
E9 1.6.0:  IE Treated Stick, No Recipe

### ISSUE THREAD

**Issue by Ashrahl** [EnigmaticaModpacks/Enigmatica9#333]
### Modpack Version

1.6.0

### Describe your issue.

JEI Doesn't show a recipe for Treated Sticks.  Unable to craft.  Normal recipe makes nothing.  

Note:  I just updated the pack and didn't start a fresh world, though I doubt that relates to this at all.  

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Ashrahl#9428

**Comment by MuteTiefling** [comment]
Thanks for the report. That's an odd one for sure, but we'll get it fixed up here.

**Comment by Kanzaji** [comment]
Found the cause, while removing recipes for Rods from IE, it seems like the regex also removed the treated stick recipe 😅
