### ISSUE TITLE
Blue Skies Quests

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica9#337]
### Describe your suggestion

Blue skies has some slightly confusing mechanics like needing certain tools from within their mod to hurt bosses and it isnt necessarily all intuitive... also there is a bit of progression as to which dungeons you can do when that isnt super clear in the docs. Some quests covering these might be nice.

### Why would you like this added/changed?

clarity in the mod

**Comment by MuteTiefling** [comment]
I think we won't be needing this after all :D
