### ISSUE TITLE
More Minecarts and Rails mod

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica9#347]
### URL

https://www.curseforge.com/minecraft/mc-mods/more-minecarts

### Why would you like the mod added?

It was too late for e6, but maybe not too late for e9?

Original justification:
> E6 has some train mods, but those are criminally underutilized. Most rail mods we have only provide some extra rail types, but when you try to build any kind of automation with rails, you quickly realize that in the end our rail situation is not very different from vanilla. We have no sane way to route minecart trains, and what carts can do is severely limited, to the point where I haven't seen anyone use any minecart systems in Enigmatica discord. I suggest adding this mod to provide some more options for minecart automation via:
> - **Color Detector Rails and signal minecarts:** this allows for actual minecart routing without using insane chest minecart filtering setups, while still being complicated enough to be interesting. This is my main point why I want this mod
> - **Cart chunk loader:** Allows long-distance item travels via minecarts without having to chunk load whole path
> - **Carts with fluid/energy storage:** self-explanatory

While it's true that we have Create Trains for long range transportation, this mod would still be useful for smaller setups

**Comment by NielsPilgaard** [comment]
I'll test it out, thanks for the suggestion 😊

**Comment by MuteTiefling** [comment]
Create with Create Additions already allows all of this. 

Create Trains at a base can transport liquids and solids. They do not require chunkloading by their nature. The rail network is 'known' to the mod and the trains are simulated along the path in unloaded chunks. 

With Create Additions, energy can also be transported by train with accumulators and portable energy interfaces

For something smaller and with less setup, there's Little Logistics already. Similar to Create, it has storage cars for items and fluids. It self chunk loads, and comes with a variety of rails to help with routing. The trains themselves operate on waypoints, so they can auto switch rails as necessary to reach their destination. 

As for transporting power with them, it's not natively supported, but nothing is stopping you from charging batteries and storing them as items. Powah has some useful blocks for charging/discharging items, and Mekanism batteries can do it too.

**Comment by NielsPilgaard** [comment]
Based on Mute's comment and our wish to keep E9 trim, I'm afraid it's a no. I hope the available methods are enough :)
