### ISSUE TITLE
Create: Steam & Rails addon

### ISSUE THREAD

**Issue by Zarrexx** [EnigmaticaModpacks/Enigmatica9#348]
### URL

https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails

### Why would you like the mod added?

Me and a friend decided to try Create for the first time during our last playthrough and had a blast with the trains. I think this mod adds some cool additions like being able to couple and de-couple train cars without having to rebuild them every single time

**Comment by NielsPilgaard** [comment]
This looks pretty cool, thoughts @MuteTiefling?

**Comment by MuteTiefling** [comment]
That actually does sound pretty cool. All in

**Comment by theboo** [comment]
This mod has now been updated to work with latest create!
