### ISSUE TITLE
Enigmatica Gems not working with Ars Table

### ISSUE THREAD

**Issue by Micaxs** [EnigmaticaModpacks/Enigmatica9#350]
### Modpack Version

1.6.0

### Describe your issue.

The enigmatica gem doesn't work with the Ars Table:

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/14205312/25fb2f05-df32-4780-b4d9-ea65e4fa313a)

Missing recipe?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Mica#0001

**Comment by MuteTiefling** [comment]
Thanks for the report.

I do believe this is fixed next update, but I'll double check later to be sure.
