### ISSUE TITLE
No osmium

### ISSUE THREAD

**Issue by gzcwnk** [EnigmaticaModpacks/Enigmatica9#351]
### Modpack Version

no idea

### Describe your issue.

Unable to locate osmium ore in several hours mining, game un-playable

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

merchantofdeath#2094

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by theboo** [comment]
Did notice I forgot to add it to the nether tho, that should be changed... I don't think I'll have time to do that in the foreseeable future tho

**Comment by Kanzaji** [comment]
I can confirm that in dev Osmium generates normally, it is rare however, so I think boosting a bit chance on lower y levels could be a nice addition :D
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/81ea4819-196f-4b14-8dca-8f543eec2e55)

I will also add Osmium to the nether in the PR I'm working on atm.
