### ISSUE TITLE
PerViam server crash

### ISSUE THREAD

**Issue by Micaxs** [EnigmaticaModpacks/Enigmatica9#352]
### Modpack Version

1.6.0

### Describe your issue.

It seems that there is an issue with the PerViam mod on servers, it causes an odd crash, I've added the crash-report below for more info.

### Crash Report

https://gist.github.com/Micaxs/fe01f678a46f1414d3b9bf35b84cb5ff

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Mica#0001

**Comment by theboo** [comment]
This *should* be fixed in next update, I haven't had this crash on my family server since we removed vanilla mobs from this entity tag in dev

**Comment by Micaxs** [comment]
> This _should_ be "fixed" in next update, I haven't had this crash on my family server since we removed vanilla mobs from this entity tag in dev

Any eta when this next release occurs, or is there a temporary fix I could apply?

**Comment by theboo** [comment]
Add this file to `kubejs/server_scripts/base/tags/entity_type/pvi/replace_vanilla_navigator.js ` and reload the server

https://github.com/EnigmaticaModpacks/Enigmatica9/blob/develop/kubejs/server_scripts/base/tags/entity_type/pvi/replace_vanilla_navigator.js
