### ISSUE TITLE
BYG: Pendorite found 

### ISSUE THREAD

**Issue by MegaThornax** [EnigmaticaModpacks/Enigmatica9#354]
### Modpack Version

1.6.0

### Describe your issue.

It was said to report it in the modpack, so I'm doing my part.
I'm playing on a server hosted on a machine I'm playing on.
And, well, got pendorite in the embur bog.

I'm linking my latest server log and local log. It's written here so i comply.

Gonna add I'm using Prism Launcher, maybe it narrows things down.

### Latest Log

https://gist.github.com/MegaThornax/89a65e3e8ecfe7a78b2bbf252ab3ebd9

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

MegaThornax#9131

**Comment by Kanzaji** [comment]
Thanks for the report! Was already reported #256 , and was supposed to be fixed in #146, however that was not the case >.>
Proper fix is in #338 :D

**Comment by MegaThornax** [comment]
So **maybe** next realease will fix it ?

**Comment by Kanzaji** [comment]
Yup, next release should have this fixed :D
Also, we usually don't close the issues until the fix is released 😅

**Comment by MegaThornax** [comment]
Noted
