### ISSUE TITLE
PerViam Ticking Entity Crash

### ISSUE THREAD

**Issue by Racerman2001** [EnigmaticaModpacks/Enigmatica9#356]
### Modpack Version

1.6.0

### Describe your issue.

Upon loading into my singleplayer world, the game crashes to desktop. This crashed occurred twice in a row, but did not occur upon a third relaunch of the game. The crash appears to be directly related to PerViam's changes to pathfinding, specifically affecting a Villager near spawn.
This crash is **NOT** the same as https://github.com/EnigmaticaModpacks/Enigmatica9/issues/352 based on cursory observation of the crash report, as it appears to be a `NoClassDefFoundError` relating to PerViam's `RoadBlockRegistry`.

### Crash Report

https://gist.github.com/Racerman2001/5c72731a88837d5ddb707882718284e7

### Latest Log

https://gist.github.com/Racerman2001/498909ecd78dfa5b985eff1ebd725b14

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Racerman2001#9569

**Comment by theboo** [comment]
We have removed PVI from all vanilla mobs in dev, including villagers, the fix in #352 should still work for this
