### ISSUE TITLE
Create Alternator Recipe Problem

### ISSUE THREAD

**Issue by Joprebond** [EnigmaticaModpacks/Enigmatica9#357]
### Modpack Version

1.6.0

### Describe your issue.

When trying to craft the Create Crafts and addons alternator it needs the create specific andesite alloy and not the EE version.

### Have you modified the modpack?

Yes

### User Modifications

CCI

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

JoprebondOdin#5307

**Comment by NielsPilgaard** [comment]
@Kanzaji is this covered in your latest PR? :)

**Comment by Kanzaji** [comment]
😅Not yet!

**Comment by NielsPilgaard** [comment]
Would you mind including it? :D
