### ISSUE TITLE
Performanсе issues (sttuters)

### ISSUE THREAD

**Issue by mllightitup** [EnigmaticaModpacks/Enigmatica9#360]
### Modpack Version

1.6.0

### Describe your issue.

In the regular version of the modpack without any changes there are stutters, which greatly affect the feeling of the game.
For example, the game shows 130-140 fps, but it feels like the game is going at 60 fps. This can be confirmed by any performance monitor that is able to show rare events.
I also noticed that stutters are affected by the "mipmap level". For example, at "0" 99% FPS shows ~85fps, while normal fps is 140+. And at "4" 99% FPS shows ~60fps with the same normal fps (140+).
This happens on different PC configurations. I tested this on intel+nvidia setups. For example, on 9600k+4070 and laptop 12700h+3060 mobile.
These stutters are also present when the F3 menu is turned off. I went to check what happens in vanilla, and as expected there is no such effect, and everything is normal.
It also happens in worlds generated on vanilla or even in a super flat world without structures and on a peaceful mode of difficulty. 

I tried to turn off mods binary search to find the cause, but because a lot of mods it did not lead to anything and I have the impression that this effect is accumulated from the number of mods that add new blocks, etc. But I'm not so sure about this.
Screenshots
mipmap level 0:
![2023-05-25_14 14 37](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/43480503/38962c93-fb84-4d6a-aa71-001cdad968f2)
monitoring:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/43480503/b229342d-328f-48fd-81cb-ff7b5fe117b9)

mipmap level 4:
![2023-05-25_14 12 19](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/43480503/22bb0990-6962-4dd6-9436-e7383a0d1591)
monitoring:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/43480503/eba7ebe5-05ae-45de-a00f-449636405a4a)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Егорка#2482

**Comment by mllightitup** [comment]
Is there any profiler that allows to analyze what caused such frame time? I tried to use spark, but it did not show anything strange (or I just do not know how to use it correctly to look for such problems).

**Comment by mllightitup** [comment]
But this problem is not with my particular performance. This problem exists on many PC configurations. So, I think the problem is in some mods in this particular modpack. And I think this problem should not be solved individually

**Comment by mllightitup** [comment]
> I'm afraid we can't really help with FPS issues here, I recommend heading over to our Discord, hopefully there's some help to get there 😅

The problem is present with different JDKs, different arguments, different memory allocations, different graphics settings, and even if you add other optimization mods such as rubidium etc. I just asked a friend to check with 10600k+3070 and he has the same problem

**Comment by mllightitup** [comment]
I asked another friend with a 9700f+2060super to check this and the problem is still there. So, I think this is a modpack problem and should be reflected on this tracker and I want this problem to be solved for everyone, not just those who individually contact in discord

**Comment by MuteTiefling** [comment]
We understand the concern. Still, please take it to Discord as asked. If the investigation turns up an underlying issue caused by the pack, we'll look into that too.
