### ISSUE TITLE
No Telemetry mod

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica9#361]
### URL

https://www.curseforge.com/minecraft/mc-mods/no-telemetry

### Why would you like the mod added?

Starting from 1.18, minecraft has forced telemetry, sending non-anonymous data to Microsoft, and that can't be turned off. I can't see any reason why Mojang would need info from heavily modded MC, so I'd rather not feed extra user data to them.

**Comment by theboo** [comment]
E9 already has the NoChatReports mod which has this feature built in.
