### ISSUE TITLE
[Mod Suggestion] Engineers Decor!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#37]
### URL

https://www.curseforge.com/minecraft/mc-mods/engineers-decor/files/3970194

### Why would you like the mod added?

Adds a lot of industrial grade decorations :D

**Comment by NielsPilgaard** [comment]
I'm not sure about this one, since it adds a lot of Tech blocks. @MuteTiefling thoughts?

**Comment by MuteTiefling** [comment]
I do enjoy the mod, but I think I'd like to pass on it this time as the machines lack disoverability in JEI and are largely replicated by other mods.

**Comment by jlfree12** [comment]
I don’t suppose you’ll reconsider this one? It has some of the best decorative blocks in all of modded, especially the catwalks which are absolutely perfect for industrial builds.

**Comment by NielsPilgaard** [comment]
Perhaps we can just disable the machinery 🤔

**Comment by MuteTiefling** [comment]
Sounds fair.

**Comment by jlfree12** [comment]
I didn’t actually expect that to work lol. Super glad to hear it’s getting in!
