### ISSUE TITLE
Add Mod Name Tooltip

### ISSUE THREAD

**Issue by RoyalReject** [EnigmaticaModpacks/Enigmatica9#374]
### URL

https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip

### Why would you like the mod added?

I would like Mod Name Tooltip to be added to have uniformity between JEI and the players inventory when hovering over items.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion, we'll get that added - I thought it was already in tbf 😅
