### ISSUE TITLE
Supplementaries appears to be causing a crash on Server startup

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica9#377]
### Modpack Version

1.7.1

### Describe your issue.

Reported by Marvi Biene on Discord. They're getting the same crash as described here: 
https://github.com/MehVahdJukaar/Supplementaries/issues/633

### Crash Report

https://gnomebot.dev/paste/1114896894867537930

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Marvi Biene#0001

**Comment by MarviBiene** [comment]
Downgraded the mod to "supplementaries-1.19.2-2.3.14a" without any issue.
Clients can connect with a missmatching version, but are unable to see anything in their hand (or the hand itself).
