### ISSUE TITLE
Dense Crimson/Warped Stem Missing Tags

### ISSUE THREAD

**Issue by anivlys** [EnigmaticaModpacks/Enigmatica9#379]
### Modpack Version

1.7.1

### Describe your issue.

The Dense Crimson/Warped Stem appears to be missing tags, and as such is not treated (treeted) as a log for axe purposes.

Tags that the other Dense Logs have, but Crimson/Warped don't are as follows:
minecraft:logs
byg:all/logs
minecraft:completes_find_tree_tutorial

### Have you modified the modpack?

Yes

### User Modifications

Added InventoryHUD+

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report!
