### ISSUE TITLE
Domum Ornamentum mod

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica9#383]
### URL

https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum

### Why would you like the mod added?

This mod is a spiritual successor to ArchitectureCraft mod, allowing player to create decorative versions of normal blocks (and combing them even).
Would be good to have this mod for more decoration. Tho it would require some manual work to fill in all the mod tags, because by default it only works with vanilla blocks and those blocks that implement vanilla item tags, but not with stuff like modded brick blocks

**Comment by NielsPilgaard** [comment]
We already have Framed Blocks, so no thank you :)
