### ISSUE TITLE
Personality mod

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica9#384]
### URL

https://www.curseforge.com/minecraft/mc-mods/personality

### Why would you like the mod added?

Keybind to drop to 1 block of height is just too useful to not have

**Comment by NielsPilgaard** [comment]
You should be able to achieve the same with Ars :)

**Comment by juh9870** [comment]
This is about convenience again. If I have to use a glyph then might as well just break the block above. For prolonged actions that require crouch glyph is better ofc, but for quick terrain navigation players surely won't pull out their ars book and switch spell just to be smaller for 2 seconds
