### ISSUE TITLE
Trash slot mod

### ISSUE THREAD

**Issue by juh9870** [EnigmaticaModpacks/Enigmatica9#385]
### URL

https://www.curseforge.com/minecraft/mc-mods/trashslot

### Why would you like the mod added?

Having this is much better than littering items all over the place

**Comment by ZZZank** [comment]
In theory FTB mods will provide a trash slot on the top-left corner of the screen, that didn't work for you? 🤔

**Comment by juh9870** [comment]
Nope, no such slot anywhere on screen

**Comment by NielsPilgaard** [comment]
I'd rather not add it this time around to be honest, I'd prefer players find a solution themselves. A bucket of lava for example 😄

**Comment by juh9870** [comment]
This is just back to vanilla. It's not like we can't do this, it's all about convenience. Having to drop items in some hole/lava is not better than having trash slot, it just leads to more items littering random places. Especially since we are in modded, there are MUCH more random trash that you want to deal with. "Solution" is known, it just sucks

**Comment by juh9870** [comment]
This is more of a problem in e9e when you need to quickly dispose of a bunch of unwanted loot, and player surely not gonna place a bucket of lava to get rid of those, they will just throw them on a ground and leave them forever

**Comment by MuteTiefling** [comment]
I personally never found trash slots convenient, but that's maybe just me. 

Having to mouse drag an item, one stack at a time, into a slot in the gui is way more bothersome to me than Ctrl + Throw while hovering over them. 

I know they also have keybinds, but then it's just another thing I need to find a key for among the tens of things modded already needs keybinds for.

**Comment by theboo** [comment]
I, personally, love ftb essential's /trashcan command... I just wish their back command could be set to only work after death

**Comment by juh9870** [comment]
Yeah, trashcan button in top left part of an inventory in e6 was ideal
