### ISSUE TITLE
Slab to block crafting doesn't show the output

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica9#387]
### Modpack Version

1.7.2

### Describe your issue.

When crafting slabs to full blocks, the crafting table doesn't show the output, but it still works when you click to grab it.

This is how the crafting looks:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/39110993/27eef7a8-b06c-4c58-bb6c-b5d1541f1ae1)

But when you click on the output:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/39110993/ea4b0fa1-24ff-43fe-a50a-192014b44b08)

I tested it with plenty of slabs and it seems to be happening with most, if not all of them.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

seoy

**Comment by MuteTiefling** [comment]
Is this still happening without JEC? I'm not seeing it in dev anymore.

**Comment by SeooY** [comment]
I just checked in-dev with the latest commits as of right now and it's still happening for me. I don't have JEC installed.

**Comment by Kanzaji** [comment]
On the current dev, as of 27.08, I still can't replicate the issue >.>
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/3d71a8bd-cdcc-4508-b58f-a041d731ba8c)
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/d868d75f-08a3-4b13-880e-33745b3265b8)
