### ISSUE TITLE
Shift-Click Crafting a Flat-Top Barrel crashes the game, may delete barrel item

### ISSUE THREAD

**Issue by Racerman2001** [EnigmaticaModpacks/Enigmatica9#401]
### Modpack Version

1.7.2

### Describe your issue.

Attempting to convert a Sophisticated Storage Barrel to a Flat-Top variant by shift-clicking the result from the inventory crafting output causes a game crash. Upon cursory experimentation between two separate worlds, it appears there is a high (but not guaranteed?) chance that the barrel will be deleted as a result of the crash. Further testing recommended for this aspect of the bug.

### Crash Report

https://gist.github.com/Racerman2001/2d1b83d805d501bef38eb458314421b0

### Latest Log

https://gist.github.com/Racerman2001/4f0a8760d4fb8403ae82e413bcf343b8

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Racerman2001#9569

**Comment by MuteTiefling** [comment]
Thanks for the report. Can reproduce and have relayed!

**Comment by P3pp3rF1y** [comment]
This issue with flat barrel recipe is already fixed in the latest versions of storage so just updating will fix it.
