### ISSUE TITLE
Hotbar gets stuck

### ISSUE THREAD

**Issue by Garren134** [EnigmaticaModpacks/Enigmatica9#408]
### Modpack Version

1.7.2

### Describe your issue.

Hotbar is stuck on one slot, numbers or scrollwheel dont change the slot. Can fix by deleting options.txt and knownkeys.txt but it happens again dont know what causes it

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

bubsito

**Comment by MuteTiefling** [comment]
I've never been able to reproduce this. If it's still occuring in 1.12.1 or higher, please let us know.
