### ISSUE TITLE
Immersive Engineering Multiblock structures not connecting

### ISSUE THREAD

**Issue by BruceVDH** [EnigmaticaModpacks/Enigmatica9#414]
### Modpack Version

Enigmatica 9 1.7.2

### Describe your issue.

When trying to build a crude blast furnace there was a clear problem. I built the blast bricks and an engineers hammer. I set them up in a 3x3 as you're supposed to but when right clicking a center block it didn't do anything. I tried clicking every block and still nothing. I even tried building a new hammer and restarting minecraft itself but still nothing. After that i tried to build the improved blast furnace to see if that would work but it had the same problem. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

BruceVDH#5455

**Comment by MuteTiefling** [comment]
Assuming you closed this upon realizing the crude blast furnace is disabled? But what was the issue with the advanced one?
