### ISSUE TITLE
Ticking Entity Server Crash

### ISSUE THREAD

**Issue by IllegalCharacter** [EnigmaticaModpacks/Enigmatica9#418]
### Modpack Version

1.7.2

### Describe your issue.

I think it's related to one of the other crashes, and someone else in the support channel on discord had the same issue. I don't know that much, but it appears to be an issue with pathfinding, possibly related to the chairs from Create.

### Crash Report

https://gist.github.com/IllegalCharacter/ca046b0ef91d857d38bbd395c0f194c0

### Latest Log

https://gist.github.com/IllegalCharacter/16b6d82aa03743df80dbc595da9ac218

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

LimblessNick#5537

**Comment by jinkhya** [comment]
Hello,
as a headsup,this issue isn't fixed with 0.60. :)
I manually updated the mod and we're still getting the same crash. Here's the report : https://github.com/ldtteam/PerViamInvenire/issues/24

**Comment by MuteTiefling** [comment]
PVI is no longer in the pack. Going to go ahead and close this out.
