### ISSUE TITLE
Quark Feeding Through module causing lag

### ISSUE THREAD

**Issue by jinkhya** [EnigmaticaModpacks/Enigmatica9#426]
### Modpack Version

1.7.2

### Describe your issue.

Hello ! 
There are about 8 players currently playing on the server and it looks like the tps tanking a bit (it's around 14-15 right now)
I ran a spark profiler and here's the result. I tried to find the feeding through in world, and broke the couple I could find through /cu te find command but even after that it looks like it's still top usage in spark reports (might be the actual animals AI checking if feeding throughs are around?)

Anyways here is the spark report : https://spark.lucko.me/M5IPB6fFoW 

Thanks in advance :)
Jin

For info I found this : https://github.com/VazkiiMods/Quark/issues/3756
and wrote a brief message with the spark report.

### Have you modified the modpack?

Yes

### User Modifications

I removed
FTB-Backups
Dyn-view

I added some server side utility mods : 
Worldedit
ftb essentials
ftb ranks
discord integration
shutdowner
vanishmod
chunky

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

jinkhya

**Comment by MuteTiefling** [comment]
Thanks for the report. Gonna disable it as Farming for Blockheads' trough appears to have a much lower impact on TPS. 

https://github.com/EnigmaticaModpacks/Enigmatica9/pull/436
