### ISSUE TITLE
In-Game Quest Book detailing mod that does not exist

### ISSUE THREAD

**Issue by AkaneTsuzura** [EnigmaticaModpacks/Enigmatica9#427]
### Modpack Version

Enigmatica 9 1.7.2

### Describe your issue.

Building chapter of the FTB quest book tells you about The Mighty Architect. This mod is not in this mod pack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. This has already been fixed in dev
