### ISSUE TITLE
mk3 mining gadget disappears from elite energy cube while charging

### ISSUE THREAD

**Issue by gzcwnk** [EnigmaticaModpacks/Enigmatica9#428]
### Modpack Version

1.7.2

### Describe your issue.

On occasion when I place the mk3 mining gadget into an energy cube it vanishes, this has now happened 3+ times

### Have you modified the modpack?

No

### User Modifications

no

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

merchantofdeath

**Comment by gzcwnk** [comment]
https://gist.github.com/gzcwnk/460fe9bfb7d886691b3345927fe5857f

**Comment by MuteTiefling** [comment]
Thanks for the report. I'm not currently able to reproduce this, but it sounds more like a client de-sync than anything. You're certain the item is being voided? If you put it in and it disappears, what happens if you relog? Does it come back? Stays gone?

**Comment by gzcwnk** [comment]
It doesnt happen every time, more like once a week. On the last (4th) occasion it re-appeared when I went to charge a new mk3 I had just made as a replacement.

I have tried logging out and back in and it did not re-appear.

**Comment by MuteTiefling** [comment]
Very likely just a client de-sync. Don't think we can do anything about this.
