### ISSUE TITLE
Animal Fat not dropping

### ISSUE THREAD

**Issue by jinkhya** [EnigmaticaModpacks/Enigmatica9#429]
### Modpack Version

1.7.2

### Describe your issue.

Hello,
It looks like animal fat from hexerei is not dropping. I killed a lot of cows in singleplayer with a looting IV sword and nothing. Is there a specific tool I need? I saw there's a script for it in kubejs/server_scripts/base/loot_tables/entities/hexerei/
but I don't see what the problem is.

Thanks in advance,
Jin

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jinkhya

**Comment by MuteTiefling** [comment]
Thanks for the report. That'll be fixed up for next release.
