### ISSUE TITLE
[Mod Suggestion] Create!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#43]
### URL

https://www.curseforge.com/minecraft/mc-mods/create/files

### Why would you like the mod added?

I think everyone knows what Create is used for at this point 😅

**Comment by Gcat101** [comment]
1.14+ modpack without create or no balls?

**Comment by NielsPilgaard** [comment]
That was needlessly aggressive Gcat o_O
