### ISSUE TITLE
Drygmy's are retrieving Ingots from EE

### ISSUE THREAD

**Issue by Joprebond** [EnigmaticaModpacks/Enigmatica9#437]
### Modpack Version

1.7.2

### Describe your issue.

Drymys will get Iron Ingots and Copper Ingots from Drowned/Zombies that are from EE and say they are going to be removed

### Have you modified the modpack?

Yes

### User Modifications

CCI

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

JoprebondOdin#5307

**Comment by MuteTiefling** [comment]
Thanks for the report! This has been fixed in dev.
