### ISSUE TITLE
Public Server button overlaps with NoChatReports Reload button in MP menu!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#444]
### Modpack Version

dev

### Describe your issue.

![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/b465a0c3-97ae-4a92-9862-caacc496aaf2)
Not much else to say here 😅

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

kanzaji

**Comment by WitherTM** [comment]
I got the same issue, happens with every gui scale
