### ISSUE TITLE
Reduce spawnRange for Spirit cages

### ISSUE THREAD

**Issue by jinkhya** [EnigmaticaModpacks/Enigmatica9#448]
### Describe your suggestion

Hello,

I made the ultimate soul cage and noticed in JEI the spawn range is 11 blocks which is gonna be bigger than a chunk.  It's possible to adjust those through datapack/kubejs. The tiers are in data/spirit/recipes/tiers folder (https://github.com/terrarium-earth/Spirit/tree/1.19/common/src/main/resources/data/spirit/recipes/tiers)

Could it be possible to tweak those values a bit please.
Thanks in advance,
Jin

### Why would you like this added/changed?

I find it crippling to have to setup a room this large or have to block spawns with blocks to reduce it. :)

**Comment by MuteTiefling** [comment]
Sure thing. I'll have a look at adjusting those.
