### ISSUE TITLE
Emeraldite Shards (disabled item)

### ISSUE THREAD

**Issue by SilasHoffmann** [EnigmaticaModpacks/Enigmatica9#449]
### Modpack Version

E9 v1.7.2

### Describe your issue.

I found some byg:emeraldite_shards in one of the big sunken ships where you can find a drowned spawner and some chematic cannons.

### Have you modified the modpack?

Yes

### User Modifications

i added ftb ultimine, rubidium, oculus and a zoom- and a gamma mod, so this should not have caused the issue

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
I will try ^^"
