### ISSUE TITLE
Game keeps randomly crashing

### ISSUE THREAD

**Issue by awsomeguy67** [EnigmaticaModpacks/Enigmatica9#450]
### Modpack Version

1.8

### Describe your issue.

The game keeps randomly crashing, there was no consistency in the begging, but it started to mainly happen when I was at the meteor.  

### Crash Report

[<script src="https://gist.github.com/awsomeguy67/05326696f69f82fde6cb07ab3b5a89b3.js"></script>
](https://gist.github.com/awsomeguy67/05326696f69f82fde6cb07ab3b5a89b3)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report. Could you please reupload your crash log?

**Comment by Darkere** [comment]
This has been fixed in PerViamInvenire 63. If you are in single player you can update that yourself.
