### ISSUE TITLE
Cannot connect to server on version 1.8.0

### ISSUE THREAD

**Issue by sniggyfigbat** [EnigmaticaModpacks/Enigmatica9#451]
### Modpack Version

1.8.0

### Describe your issue.

We've just attempted to upgrade from 1.3.0 to 1.8.0, and we cannot log into the server. The issue is exactly the same as the one seen in #229 but the workaround posted there hasn't worked.

With the `refinery.js` and `smelter.js` files removed, we now get the following error (server-side) upon joining:
`Lorcogoth lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class cofh.lib.util.crafting.IngredientWithCount cannot be cast to class dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient (cofh.lib.util.crafting.IngredientWithCount is in module cofh_core@10.2.1 of loader 'TRANSFORMER' @3e0a9b1d; dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient is in module kubejs@1902.6.0-build.142 of loader 'TRANSFORMER' @3e0a9b1d)`

### Latest Log

https://gist.github.com/sniggyfigbat/990d5a617f5e3c8380bde82beadf7567

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by skrcka** [comment]
same issue

**Comment by NielsPilgaard** [comment]
Damn, I should've caught that in testing 😅  

While we work on resolving this issue, I recommend downgrading to 1.7.2. It might be a little while, sadly.

**Comment by sniggyfigbat** [comment]
@NielsPilgaard Hi dude. Just so you know, I tried swapping out `crystallizer.js` with the version from #452, and it didn't resolve the issue. Not sure if there was some additional change I missed. The error in the log didn't change, either.

Just as an aside, I just want to say how much I appreciate the speed with which you've addressed this. One of the reasons we always pick Enigmatica whenever we run a server is because of the incredible work you and your team do.

**Comment by sniggyfigbat** [comment]
Ah, I spotted this error in the logs with the amended `crystallizer.js`:
`Line 2682: [02jul.2023 20:13:05.867] [main/ERROR] [KubeJS Server/]: ! #75: Error occurred while handling event 'ServerEvents.recipes': TypeError: Cannot call method "toJson" of undefined (server_scripts:normal/recipes/thermal/crystallizer.js#75)`

I amended line 75 to:
```
if (recipe.fluid) {
	recipe.ingredients.push(recipe.fluid.toJson());
}
```

but alas, it didn't resolve the issue.

**Comment by sniggyfigbat** [comment]
OK, I tried the nuclear option and tried removing the entire thermal recipes folder from base, normal, and expert, and it let me onto the server. Next step: trawling through every damn one of those files until I work out which of them is broken.

**Comment by Kanzaji** [comment]
Just to save you the trouble... normal Thermal scripts are the one that are broken, and real fault is on Therrmal's fault 😅

**Comment by Darkere** [comment]
Thermal will be releasing a fix next week. We might be fixing it from our side before that.

**Comment by sniggyfigbat** [comment]
Righto'. Just so you all know, the broken script is `kubejs\server_scripts\normal\recipes\thermal\press.js`. I couldn't work out how to translate the `4x #forge:gems/${gem}` thing to standard json, unfortunately, so for now if anyone else has my issues then just remove that file and live without the Thermal expansion press for a while.

**Comment by MuteTiefling** [comment]
@sniggyfigbat Would you mind grabbing the thermal recipes from #455 and trying them on your server?

**Comment by sniggyfigbat** [comment]
@MuteTiefling I've grabbed the files, rebooted the server, seems to be working fine.
