### ISSUE TITLE
The create mechanism for Integrated Dungeons and Structures does not work

### ISSUE THREAD

**Issue by Starship-SpaceX** [EnigmaticaModpacks/Enigmatica9#453]
### Modpack Version

1.8.0

### Describe your issue.

Due to the extra stress consumed by the shaft and cogwheel, the unit doesn't actually work
/
![2023-07-02_19 14 31](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/129238646/081b35f1-e4f9-4f65-af6c-e7125d2a35a6)
![2023-07-02_19 14 27](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/129238646/8cabc97b-5115-4396-953b-8e54a8398cbb)

### Have you modified the modpack?

Yes

### User Modifications

jade-1.19.1-forge-8.8.1
jadeAddons-1.19.2-forge-3.5.0

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Extra stress from shafts and cogs is expert only, which hasn't been released.

If you're playtesting, please leave your feedback in the thread dedicated to it in discord.
