### ISSUE TITLE
Cannot slice bread with Create Mechanical Saw.

### ISSUE THREAD

**Issue by sniggyfigbat** [EnigmaticaModpacks/Enigmatica9#459]
### Modpack Version

1.8.0

### Describe your issue.

The [Some Assembly Required](https://www.curseforge.com/minecraft/mc-mods/some-assembly-required) page suggests I should be able to run bread through a Create sawmill and get a bunch of Bread Slices, but unfortunately this doesn't seem to be an available recipe. Does this need to get added to the Create recipe list?

### Have you modified the modpack?

Yes

### User Modifications

Fixed various Thermal recipes, see #451.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by sniggyfigbat** [comment]
Pretty sure the fix is to add the following to the recipes json in `\kubejs\server_scripts\base\recipes\create\cutting.js`:
```
{
    input: [Item.of('minecraft:bread')],
    outputs: [Item.of('some_assembly_required:bread_slice', 4)],
    processingTime: 30,
    id: `${id_prefix}bread_slice_from_bread`
}
```

**Comment by MuteTiefling** [comment]
Yep, these all got lost by the blanket removal of sawing recipes to unify log/plank recipes. 

I've just gone ahead and re-added them all.
