### ISSUE TITLE
Allow Farmers Delight recipes (e.g. Fried Rice) to be made in a Create Mixing Basin on a low heat.

### ISSUE THREAD

**Issue by sniggyfigbat** [EnigmaticaModpacks/Enigmatica9#463]
### Describe your suggestion

_Farmer's Delight_ has a bunch of cool foods which can be made in the Cooking Pot. It feels like these recipes should also be craftable in the Mixing Basin - ideally on a low heat (a campfire or unfed blaze) if possible, otherwise just normally heated.

As a bonus, it might be fun if cooking on a superheated blaze produced charcoal instead.

### Why would you like this added/changed?

It would make _Farmer's Delight_ recipes fit better into an automation pipeline in a Create-based base, and just generally makes sense.

**Comment by MuteTiefling** [comment]
There's no way to do 'low heat' per se, but I love the idea of this stuff burning if you happen to run it through a superheated mixer.
