### ISSUE TITLE
Mob behavior breaking

### ISSUE THREAD

**Issue by moonemoji** [EnigmaticaModpacks/Enigmatica9#465]
### Modpack Version

1.8.1

### Describe your issue.

Encountered this when playing with this mod: [video 1](https://youtu.be/omels3a96MQ) [video 2](https://youtu.be/8CcXdtf8scM)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Closing as the mod has been removed.
