### ISSUE TITLE
Alex's Mobs

### ISSUE THREAD

**Issue by Blade67** [EnigmaticaModpacks/Enigmatica9#468]
### URL

https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

### Why would you like the mod added?

Alex's Mobs has been in many prior Enigmatica packs and has made the world much more lively. It is a wonderful mod that would work well alongside Creatures and Beasts which was newly added to this version.

**Comment by MuteTiefling** [comment]
We decided early on to skip this one in e9 due to some issues we encountered in E6. I'm not really sure it would be a good idea to add it.

**Comment by Blade67** [comment]
> We decided early on to skip this one in e9 due to some issues we encountered in E6. I'm not really sure it would be a good idea to add it.

Shame! I never had any issues personally, so I was surprised by this.
Could you tell me what the issues were that you guys found?

**Comment by NielsPilgaard** [comment]
> Could you tell me what the issues were that you guys found?

These for example: https://github.com/EnigmaticaModpacks/Enigmatica6/issues?q=is%3Aissue+alex%27s+mobs+

Another reason to skip this is, mods that add a large number of entities come with TPS lag, since entities... do things 😄
