### ISSUE TITLE
Industrial Hemp Seeds not plantable on Farming For Blockheads farmland blocks

### ISSUE THREAD

**Issue by BloodyManD** [EnigmaticaModpacks/Enigmatica9#486]
### Modpack Version

1.8.1

### Describe your issue.

Industrial Hemp Seeds (Immersive Engineering) can't be planted on any of the Farming For Blockheads farmland blocks (fertilized farmland)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

BloodyMan

**Comment by MuteTiefling** [comment]
Thanks for the report. I've relayed it, but it looks like we can fix it with some tag modifications, so I'm going ahead with that.
