### ISSUE TITLE
Better automated cooking

### ISSUE THREAD

**Issue by Starship-SpaceX** [EnigmaticaModpacks/Enigmatica9#488]
### URL

https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen/files/4626287

### Why would you like the mod added?

Allows more convenient processing of certain recipes, increasing the association between mods

**Comment by MuteTiefling** [comment]
I'll take a look tonight, but this seems like it's getting into the clutter zone

**Comment by MuteTiefling** [comment]
It's very cute, I'll give it that. However, there are a few issues. 

1. It doesn't play nice with Create Crafts and Additions. By that, I mean you can't use the cooking mechanic at all when using liquid fueled Blaze Burners
2. No discoverability. If you don't know the mod is there, you'll never know it can automate the cooking pot. This is perhaps a trivial nitpick, but it's very important to me that mods make an effort to tell you what they can do. 

Beyond that, with a few lines of code, all of these recipes are already integrated into the mixing basin which, while not as cute, is considerably less weight than adding a mod just for a bit of compat that nobody will ever see.
