### ISSUE TITLE
Mod Suggestion -> Trash Cans

### ISSUE THREAD

**Issue by KuryKat** [EnigmaticaModpacks/Enigmatica9#489]
### URL

https://www.curseforge.com/minecraft/mc-mods/trash-cans/

### Why would you like the mod added?

I know that something similar had been suggested on #385 and got rejected because of some factors, but this mod is somewhat something else, it adds a way of deleting items, energy, fluids and so on, with filters, and what-not. 

By using systems like XNet or AE2 you can to handle the hassle and mess of one's inventory/system fairly easy.

I, personally, believe this would be a nice extra touch for the pack, but I understand if gets rejected, so no hard feelings XD ❤

**Comment by KuryKat** [comment]
And since we already have Entangled, by the same author, we won't need to add any extra dependencies, only the mod itself :D

**Comment by MuteTiefling** [comment]
Thermal has the nullifier which handles items and fluids
Energy meters can be set to void power
Mekanism chemical tanks can be set to void their gases
AE2 can void everything but power and turn it into singularities

**Comment by KuryKat** [comment]
Fair enough, I'm sorry for being ignorant on the matter XD
