### ISSUE TITLE
Mod Replacement -> Simple Discord RPC > Simple Discord Rich Presence 

### ISSUE THREAD

**Issue by KuryKat** [EnigmaticaModpacks/Enigmatica9#491]
### URL

https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc

### Why would you like the mod added?

This suggestion is to replace the current [Simple Discord Rich Presence](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence) with [Simple Discord RPC](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc) for a handful of reasons, but mainly for better customization and better-looking Discord Presence

The mod itself does the same thing, adds a Presence to the player's Discord, but I believe it has a fair more amount of resources and features that the modpack could benefit from, an example of modpack that uses it is the [Valhelsia 5](https://www.curseforge.com/minecraft/modpacks/valhelsia-5) and the [Junkie Monkey](https://www.curseforge.com/minecraft/modpacks/Junkie-Monkey) (my own pack for 1.16.5, used in the examples below cause it was the one I still had screenshots)

The mod author (HypherionSA) also provides an [Editor](https://github.com/hypherionmc/simple-rpc-editor/) for easier configuration setup, where you can easily edit your config files and even see a preview of what you'll see on Discord!

Examples:

Acronyms:
    - Small Profile = When you open an user's profile, by clicking on their name, on a server, for example
    - Big Profile = When you *actually* open an user's profile, by clicking on their profile picture and seeing their "Activity" tab

- Current Rich Presence (Simple Discord Rich Presence)
There aren't many examples, as this current rich presence is pretty "blank" in features, it only shows "Minecraft" as the game, with their own logo as the default logo for the logo icon and simple description and timestamp, in all fairness it's simple, but that's all...

Small Profile
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/aaaf3d64-c389-4d42-b580-eb074f5b2365)

Big Profile
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/7f7c15c0-df0a-4360-8cba-30c5b94386eb)

- The one I'm suggesting (Simple Discord RPC)

This one allows you to choose whatever you want for any of the fields, you can choose the icon, the small icon, the description, even create dimension overrides, this way you could even display a different game when on the Nether, for example, and so on...

Small Profile
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/cce3b29c-936a-4298-a1a8-6adad5416ca7)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/54e1d1ab-1329-4e93-8090-6cad35277c87)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/b66cdae0-b5a8-47fd-ae63-79d8b8edebbe)

Big Profile
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/4b4d624a-d59b-4d53-b7a0-e14df7a11505)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/8c12e0cc-d241-41f5-b095-855ecadafa74)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/fbe00574-bdfc-4ab8-a851-ba61e34aa42d)

So yeah, that's my suggestion, I'm open for discussion, and I'd love to hear your opinions, and I'd also love to hear the reason why you guys still use such simple Discord Presence mod, when you could be fully customizing your own presence to show the players playing "Enigmatica 9" and so own in their beautiful fully customized discord presences!

**Comment by NielsPilgaard** [comment]
I'll look into it, thanks :) our current one used to work just like Simple Discord RPC as far as I can see. Not sure when it stopped.

**Comment by NielsPilgaard** [comment]
Oof this is a ton of work 😄 seems like a solid mod though.
