### ISSUE TITLE
Make rockwool affected and compatible with Mekanism machines

### ISSUE THREAD

**Issue by wortelus** [EnigmaticaModpacks/Enigmatica9#492]
### Describe your suggestion

Painting machine and pigment extractor from Mekanism is used on all kinds of colorable blocks like terracotta, wool etc. It would be a nice thing for a rockwool to be affected same too as a matter of consistency.

### Why would you like this added/changed?

It would be consistent with the rest of the recipes of colorable blocks in the modpack.

**Comment by MuteTiefling** [comment]
Sounds good. I added a bunch of other ones too.
