### ISSUE TITLE
Performance Mods

### ISSUE THREAD

**Issue by brucethemoose** [EnigmaticaModpacks/Enigmatica9#5]
Here are some optimization mods that aren't in E8, but have already made the jump to 1.19 and have worked well in another 1.18 pack. Some (like it shall not tick) are extreme out-of-the-box, but can be configured to be less aggressive and would (at the very least, if they are not added) benefit from pack-specific configs and exclusions. Others would be nice to include in the server zip, as server owners might not otherwise know to run them. 

- It shall not tick: https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick
- Debugify: https://www.curseforge.com/minecraft/mc-mods/debugify
- Entity Culling: https://www.curseforge.com/minecraft/mc-mods/entityculling

Some more mods to keep an eye on, that will likely get 1.19 updates soon:
- https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save
- https://www.curseforge.com/minecraft/mc-mods/radium-reforged
- https://www.curseforge.com/minecraft/mc-mods/starlight-forge
- https://www.curseforge.com/minecraft/mc-mods/observable
- https://www.curseforge.com/minecraft/mc-mods/farsight/files
- https://www.curseforge.com/minecraft/mc-mods/fastsuite
- https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading

Rubidium, of course, is the big one, but adding it to the pack would be quite a commitment.

**Comment by brucethemoose** [comment]
Starlight and Farsight are now on 1.19. The former is much faster than phosphor, and mostly less problematic, while the latter basically has no compatibility issues or downsides.

**Comment by ExistingProgrammer** [comment]
> Another one to consider (once it makes the jump) is better fps: https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance
This mod is also 1.19 now

**Comment by brucethemoose** [comment]
Rubidium now has 1.19 builds as well.

Again, adding it to the pack early would be advantageous, as it would allow E9 to be built "around" Rubidium.

**Comment by brucethemoose** [comment]
Just found a much better summary of the performance mods out there now: https://github.com/NordicGamerFE/usefulmods

**Comment by NielsPilgaard** [comment]
Testing out these sorts of mods is usually a huge time sink for me, and is very rarely worth the effort. I'll consider many of them, but chances are everything but Entity Culling will be a nope.

**Comment by brucethemoose** [comment]
> Testing out these sorts of mods is usually a huge time sink for me, and is very rarely worth the effort. I'll consider many of them, but chances are everything but Entity Culling will be a nope.

The situation is different than 1.16.5. Mods like Radium, Radon and Ferritecore are widely tested and standard in many existing 1.18.2 and 1.19.X packs. And utility mods like Observable or Spark won't conflict with anything.


I can understand not officially supporting Rubidium and Starlight, but with most others, I respectfully disagree. Modded Minecraft just doesn't run well, especially on servers with more than a handful of people.

**Comment by NielsPilgaard** [comment]
I've added the following mods, pending testing:

- Smooth Chunk Save
- Limited Chunk Loading
- Rubidium
- Starlight
- Entity Culling

FerriteCore is already in the pack 👍
