### ISSUE TITLE
Beyond Earth

### ISSUE THREAD

**Issue by Gcat101** [EnigmaticaModpacks/Enigmatica9#50]
### URL

https://www.curseforge.com/minecraft/mc-mods/beyond-earth

### Why would you like the mod added?

So the team behind beyond earth recently announced that they will be porting it to 1.19.

The port isn’t out yet, but soon enough it will be.

Maybe this time space exploration will return to Enigmatica?

**Comment by MuteTiefling** [comment]
Has been discussed internally. The answer is no.
