### ISSUE TITLE
Immersive Engineering Excavator giving "Air" ores

### ISSUE THREAD

**Issue by zazum03** [EnigmaticaModpacks/Enigmatica9#501]
### Modpack Version

1.8.1

### Describe your issue.

The Excavator from Immersive Engineering works mostly fine, but digs up ores that are based in Air instead of being based in any type of stone or anything. They function as normal ores and everything, but have funny missing textures and are generally rather odd.
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/139827658/844cf65f-b0f4-4635-8b72-251372948281)

![](https://cdn.discordapp.com/attachments/984527413046312980/1130663722222899290/image.png)

Also seems to affect the core samples too.
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/139827658/0ea36948-e88f-419d-90bf-6b07bf59cbaf)

### Have you modified the modpack?

Yes

### User Modifications

Added Xerca's Music Mod.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

hamberlin

**Comment by MuteTiefling** [comment]
Thanks, that'll be fixed next update.
