### ISSUE TITLE
Djinni Machine Operator Quest not completing

### ISSUE THREAD

**Issue by MaverickX7** [EnigmaticaModpacks/Enigmatica9#508]
### Modpack Version

1.8.1

### Describe your issue.

Completing the ritual for the Djinni ore processor does not complete the quest in the quest book that states to complete the ritual.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

maverick_x7

**Comment by MuteTiefling** [comment]
Thanks for the report. 

Could you screenshot which quest exactly? I don't see any quest concerning the Djinn Ore Crusher. There's one for the Foliot, which works as expected in dev, and one for the Marid Crusher, which also works as expected.

**Comment by theboo** [comment]
I'm gonna guess they mean the machinist... It technically can process ores on demand by taking them where they'll be processed

**Comment by MuteTiefling** [comment]
Ah, that could be it. it wasn't set to an advancement at all
