### ISSUE TITLE
optifine crashes minecraft

### ISSUE THREAD

**Issue by QuiveryCacti** [EnigmaticaModpacks/Enigmatica9#510]
### Modpack Version

1.8.1

### Describe your issue.

whenever trying to launch mc with optifine it crashes but without optifine it doesnt

### Latest Log

https://gist.github.com/QuiveryCacti/bbc4dd6f4563b78cbcc01cdd136bc176

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Don't use optifine. It's terrible and causes many issues with modded minecraft.

We do not offer support for its use.
