### ISSUE TITLE
Enigmatic Unity bug

### ISSUE THREAD

**Issue by Shoesington** [EnigmaticaModpacks/Enigmatica9#521]
### Modpack Version

1.8.1

### Describe your issue.

The Ars compatible shield (Enchanter Shield) from Superior Shields uses the base source gem item and not the unified source gem.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Shoes

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
