### ISSUE TITLE
Hexerei armor causes server crash when interacting with witches 

### ISSUE THREAD

**Issue by 0xicl33n** [EnigmaticaModpacks/Enigmatica9#525]
### Modpack Version

1.8.1

### Describe your issue.

While wearing two pieces of hexerei armor (which is supposed to prevent witches from attacking you), if you approach a witch, the server crashes. By changing `removeErroringEntities` to `true` in `world/serverconfig/forge-server.toml`, I am able to join and the witch is immediately removed. By removing the armor pieces, i am able to stand near witches again without them being removed.

https://github.com/EnigmaticaModpacks/Enigmatica9/assets/2192160/9d5563ed-6224-4760-9d63-b04cc33e263d

 

### Crash Report

https://pastebin.com/hPKjuJ1j

### Latest Log

https://gist.github.com/0xicl33n/eae1d014bea43d55bd382cef7877934b

### Have you modified the modpack?

Yes

### User Modifications

`ftb-essentials-forge-1902.3.3-build.100.jar` was added for `/tpa`
`Chunky-1.3.38.jar` was added for world pregen

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

ph0sgene

**Comment by NielsPilgaard** [comment]
Thanks for the report, I've relayed it :)

**Comment by floatingatoll** [comment]
I encountered this today in a different context, and noted that hexerei 0.3.3 has a crash fix for the witch armor. Tested and confirmed. I don't use Enigmatical Modpacks, but duly noted!
