### ISSUE TITLE
Emendatus Enigmatica possibly causing crash on game startup

### ISSUE THREAD

**Issue by Tanden22** [EnigmaticaModpacks/Enigmatica9#530]
### Modpack Version

1.9.0

### Describe your issue.

Repeated crashing on startup. Crash log seems to be pointing at "emendatusenigmatica:dimensional_block" as the culprit.
If it's any help, i'm running the pack on Prism Launcher.

### Crash Report

https://gist.github.com/Tanden22/407fdc7ba0684c3bfcba368a59769cdb

### Latest Log

https://gist.github.com/Tanden22/240a2af8a9a8ff98e4b1e43a984cfe16

### Have you modified the modpack?

Yes

### User Modifications

Added:
-FTB Ultimine: ftb-ultimine-forge-1902.4.1-build.90.jar
-Xaero's Minimap: v23.5.0 for Forge 1.19.2 (or .1)
-Xaero's World Map: v1.30.6 for Forge 1.19.2 (or .1)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
This is a known issue right now, only current workaround is to just restart until it gets past this. EE dev is looking in to it.

**Comment by MuteTiefling** [comment]
Cleanup. Fixed with the removal of Railway
