### ISSUE TITLE
Broken recipe of oak drawer

### ISSUE THREAD

**Issue by BloodyManD** [EnigmaticaModpacks/Enigmatica9#533]
### Modpack Version

1.9.0

### Describe your issue.

Recipes for all oak drawer variants(1x1, 1x2 and 2x2) show up as double recipes where one recipe uses oak planks and the other recipe omits planks.
![изображение](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9305291/cd92ae6f-c32a-4bf0-8c8d-96a501a9b3ca)

### Have you modified the modpack?

Yes

### User Modifications

Rubidium + Rubidium Extras

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

BloodyMan

**Comment by MuteTiefling** [comment]
Thanks for the report. We'll investigate the issue.
