### ISSUE TITLE
Missing ore processing recipes

### ISSUE THREAD

**Issue by BloodyManD** [EnigmaticaModpacks/Enigmatica9#539]
### Modpack Version

1.9.0

### Describe your issue.

The recipes for processing Raw Ores are missing.
There are no KubeJS errors.
Modpack was updated from 1.8.1 to 1.9.0 via CurseForge launcher.

https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9305291/2ce0dbb7-443b-4658-8ef6-2e0ada4dae39

### Have you modified the modpack?

Yes

### User Modifications

Rubidium + Rubidium Extras

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

BloodyMan

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
