### ISSUE TITLE
Tag error when joining world causing invalid player data

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica9#544]
### Modpack Version

in-dev

### Describe your issue.

Currently play-testing E9E, so I'm constantly updated to the develop branch.
At random, when trying to join my world, a Tag error will be thrown in console. This disconnects me from the "Server" (even though it's a Single Player world), throws me into the Multiplayer Server view, and occasionally leaves the world in a locked state so I'm forced to restart the game to retry joining. 

It has happened to me 3 times in the last 5 days or so, so it doesn't always happen, and trying again makes it go away.

I've uploaded the full latest log, which includes the error.

### Latest Log

https://gist.github.com/SeooY/fd0ae0e594cfc15cbf038fddef346ee6

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

seoy

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by Darkere** [comment]
@Klikli-dev The error mentions modonomicon. Any idea if this could be something you are doing or is this (which I think is more likely) some Kubejs fuckery causing issues.

**Comment by klikli-dev** [comment]
@Darkere so it seems modonomicon is the one *throwing* the error but I think not causing it.
"Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block tag 'enigmatica:heartwoods/stage_3' at position 0:"

It looks like you have a modonomicon multiblock somewhere in the pack or one of the mods that uses that tag, but the tag does not exist?

**Comment by MuteTiefling** [comment]
The tag is sometimes randomly missing due to a bug in kubejs that causes our tag scripts to fail.

I'd personally prefer if it didn't crash out modonomicon because it's a shining thing to fix they missing tag once in game (just run a reload)

**Comment by klikli-dev** [comment]
> The tag is sometimes randomly missing due to a bug in kubejs that causes our tag scripts to fail.
> 
> I'd personally prefer if it didn't crash out modonomicon because it's a shining thing to fix they missing tag once in game (just run a reload)

fair enough! so I will just log an error without throwing an exception, and will use a custom bedrock tag as placeholder (because the whole process needs a tag)

**Comment by klikli-dev** [comment]
The latest versions of 1.19.2 and 1.20.1 now have this change - please let me know if it doesn't work because I can't repro the issue on my end so I could not test the behaviour

**Comment by MuteTiefling** [comment]
Awesome, thanks Klikli! You're the best :D

**Comment by MuteTiefling** [comment]
This was included in the 1.10 release
