### ISSUE TITLE
Ars Nouveau Crush Spell dyes dupe

### ISSUE THREAD

**Issue by BloodyManD** [EnigmaticaModpacks/Enigmatica9#545]
### Modpack Version

1.9.0

### Describe your issue.

Using Ars Nouveau Crush Spell on the top block of tall flowers drops both dyes and a tall flower.

### Have you modified the modpack?

Yes

### User Modifications

Rubidium + Rubidium Extras

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

BloodyMan

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Relayed: https://discord.com/channels/743298050222587978/1134634376961994752
