### ISSUE TITLE
Sophisticated storage chest crafting upgrade does not work properly with JEI move items feature

### ISSUE THREAD

**Issue by Reynales** [EnigmaticaModpacks/Enigmatica9#546]
### Modpack Version

1.9.0

### Describe your issue.

As you can see from the screenshots the move items button is missing whenever I open the recipe of any item while having the chest inventory open even though I have the crafting upgrade.

![Screenshot 2023-07-27 215247](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/140749999/95761b62-4186-4625-8408-7d1c5d33e364)
![Screenshot 2023-07-27 215641](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/140749999/f4e1baf5-5e9a-4390-a6c9-5f0a07306206)

### Have you modified the modpack?

Yes

### User Modifications

I have a mod called MineTogether added to the pack. I have also changed the altered certus quartz textures back to their defaults.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

reynales

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
Cleanup, this was fixed ages ago
