### ISSUE TITLE
Powah cable tiers upgrade cost

### ISSUE THREAD

**Issue by Reynales** [EnigmaticaModpacks/Enigmatica9#547]
### Describe your suggestion

So currently using the recipe that requires previous tier cables to be upgraded to the next tier is almost 2 times more expensive in terms of capacitors than simply using the recipe to craft the higher tiered cable outright.

Making two basic capacitors nets you 24 basic tier cables. If we wanted to upgrade them to hardened it would mean we could craft 72 hardened cables using the basic ones. This requires you to make 6 more basic capacitors and turn them into 12 hardened capacitors.

If we were to instead use the recipe that uses 2 energized steel rather than 2 basic cables, we receive 12 cables while only using a single hardened capacitor. That means you need to craft only 3 basic capacitors instead of the 6 that are required from the other recipe.

Perhaps tweak the recipe or outright remove it. As it is currently it's quite the loss upgrading cables from lower to higher tier using previous tier cables.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/140749999/731910c0-56f6-4b1e-bafa-84febbaf2d3b)

### Why would you like this added/changed?

Because it makes 1 of the recipes redundant and not worth using.

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
I'll go ahead and make the upgrade a little more interesting.
