### ISSUE TITLE
invisible player and mobs

### ISSUE THREAD

**Issue by Shuw4z** [EnigmaticaModpacks/Enigmatica9#551]
### Modpack Version

1.8.1

### Describe your issue.

my first time playing and i've tried rejoining and restarting the game multiple times but my player/skin is invisible and all the mobs are too. 
![2023-07-29_18 17 06](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/39592130/ecc6d481-ff12-43d2-bb6e-9e3a16af350e)
this is in F5. there are animal noises, as the subtitles say, but they are nowhere to be seen.
dropped items and block breaking animations are invisible as well

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Shuw4z** [comment]
i'll also add that items and block breaking animations are invisible as well

**Comment by NielsPilgaard** [comment]
May we have your latest.log please?

**Comment by Shuw4z** [comment]
https://gist.github.com/Shuw4z/a8d5654f3ed7720fe17662a7b3580f5f

**Comment by NielsPilgaard** [comment]
Thanks! I'm having a hard time searching through that log to be honest. Do you have one with less reloads/world joins?

**Comment by Shuw4z** [comment]
i dont sadly, it was my first time playing so i dont have any other logs

**Comment by NielsPilgaard** [comment]
Fair enough, I'll keep digging then :)

**Comment by MuteTiefling** [comment]
Apparently this might be Configured doing it.

**Comment by theboo** [comment]
If it is configured, I believe it can safely be yeeted... Create has its own built in config editor accessed through the "goggles" icon in the esc menu... The only thing configured has over create is JEI wrench icon links to it directly, but that feature doesn't even work right now anyway(it shows no client config available in configured).

**Comment by NielsPilgaard** [comment]
> Apparently this might be Configured doing it.

Context would be nice :D

**Comment by Darkere** [comment]
There were some reports couple months/weeks ago that going to the configs through the pause menu would cause this. 
Some other sources have blamed optifine for it. 

if @Shuw4z can reliably reproduce it then please test by removing configured. Any lead would be helpful

**Comment by Shuw4z** [comment]
@Darkere i tested if going to the configs is the issue since i did that when i first played, and i think it might be the issue.
i started the game and went to the configs, then created a new world and was invisible again. then i restarted the game and  created another world without going to the configs before that and everything was fine. 
guess i didnt think of that originally and kept going to the configs trying to fix it :')

**Comment by NielsPilgaard** [comment]
Excellent, thank you!
I also found this: https://github.com/MrCrayfish/Configured/issues/70#issuecomment-1509627406
We'll be removing Configured in the next update :)

**Comment by Shuw4z** [comment]
thank you! :)
