### ISSUE TITLE
dedicated server crash on boot with java.lang.NullPointerException 

### ISSUE THREAD

**Issue by StanberyTrask** [EnigmaticaModpacks/Enigmatica9#557]
### Modpack Version

1.9.0

### Describe your issue.

server was stable for a few days before we ran into somewhat infrequent crashes and now the server is refusing to boot 

### Crash Report

https://gist.github.com/StanberyTrask/29d7dad0861db7745f0abceca0b866d0

### Latest Log

https://gist.github.com/StanberyTrask/29d7dad0861db7745f0abceca0b866d0

### Have you modified the modpack?

Yes

### User Modifications

changed ftb-chunks config in the world folder along with increasing the memory allotment in the jvm args 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Looks like one of the AE2 configs is broken, I recommend you copy over a fresh config folder from a client or other server :)
