### ISSUE TITLE
CurseForge 1.9.0 Profile downloads 1.8.1 server files.

### ISSUE THREAD

**Issue by sniggyfigbat** [EnigmaticaModpacks/Enigmatica9#560]
### Modpack Version

1.9.0

### Describe your issue.

When using the `Download Server Pack` option on CurseForge, it downloads as 1.8.1. I suspected this might just be a misnaming issue, but when running both server and client with the 1.9.0 versions from CurseForge I'm getting mismatches on several mods.
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/3359069/ceddb8ad-6f5e-406c-8b96-5f0b7f88049e)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/3359069/20d99e70-9a58-459f-8404-a7c94520c16a)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/3359069/a892e2f8-9742-4f09-bb7a-d11fda523cd4)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
I'm guessing this could be due to 1.9.0 being marked as beta, and not release.

**Comment by sniggyfigbat** [comment]
@NielsPilgaard Any forward progress on this? It's still providing the 1.8.1 pack on CurseForge. I'm happy to download from another source, but I'm not sure where to look.

**Comment by NielsPilgaard** [comment]
Ah sorry, here's the link to 1.9.0 server files: https://legacy.curseforge.com/minecraft/modpacks/enigmatica9/files/4658829
