### ISSUE TITLE
Two recipes for plates

### ISSUE THREAD

**Issue by BloodyManD** [EnigmaticaModpacks/Enigmatica9#562]
### Modpack Version

1.9.0

### Describe your issue.

JEI shows two recipes for plates via Multiservo Press. The only exception is Netherite. 

![изображение](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9305291/738ce31b-09da-44b7-9992-e6f846c2a338)
![изображение](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9305291/2715b5a0-245f-47bf-bcb7-49db662c1f26)

### Have you modified the modpack?

Yes

### User Modifications

Rubidium + Rubidium Extras
I've also replaced unify_ore_processing.js with the one from the last commit.

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

BloodyMan

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
