### ISSUE TITLE
larger pattern provider

### ISSUE THREAD

**Issue by Starship-SpaceX** [EnigmaticaModpacks/Enigmatica9#565]
### URL

https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider

### Why would you like the mod added?

For some devices, a one-line pattern provider is not enough

**Comment by NielsPilgaard** [comment]
I'd rather people get creative with interface use than introduce buffed versions to be honest 😄

**Comment by Darkere** [comment]
You can do this fairly easy with a subnetwork.
