### ISSUE TITLE
Alternate Recipe for Pointed Dripstone

### ISSUE THREAD

**Issue by NuNn-DaDdY** [EnigmaticaModpacks/Enigmatica9#570]
### Describe your suggestion

**Modpack Version**
1.8.1

**Describe your issue.**
Currently, the only recipe for converting a dripstone block into pointed dripstone is via Mekanism's Crusher.  Having alternative options (e.g. Create - Crushing Wheel) would be ideal for instances when Mekanism is not being used.

### Why would you like this added/changed?

Enables different styles of play without forcing people to all use the same mods.  Obviously this is a very minor item, but increases quality of life in-game nonetheless.

**Comment by MuteTiefling** [comment]
Sounds good, I'll get that added
