### ISSUE TITLE
Enrichment Chamber + Lapis Dust

### ISSUE THREAD

**Issue by MooMcMooman** [EnigmaticaModpacks/Enigmatica9#571]
### Modpack Version

Enigmatica 9 v1.8.1

### Describe your issue.

![image_2023-08-03_152055669](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/131305003/02de39e1-b302-40f8-a987-f0f21a0717d5)

### Have you modified the modpack?

Yes

### User Modifications

Made tiab better (configs), added Essential, FTB Essentials (commands), AE2 things, AE2 MEGA cells, and EvilCraft
Disabled AI improvements

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

moomcmooman

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
