### ISSUE TITLE
Wither Council able to be summoned in Normal E9

### ISSUE THREAD

**Issue by MaverickX7** [EnigmaticaModpacks/Enigmatica9#574]
### Modpack Version

1.8.1

### Describe your issue.

I have been told the Wither Council Summon using Abras' Open Conjure is Expert exclusive, yet the recipe is in Normal mode. Searching in JEI reveals its recipe and it does work when attempted.

### Have you modified the modpack?

Yes

### User Modifications

Rubidium

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

maverick_x7

**Comment by MuteTiefling** [comment]
So, at first mention in discord I had thought this was a bug as I didn't remember adding this to normal at all.

It seems that is not the case, however. It is available for both modes with different recipes. So I guess have fun with it :D
