### ISSUE TITLE
Annihilation Planes can be enchanted a whole stack with just 1 book

### ISSUE THREAD

**Issue by BloodyManD** [EnigmaticaModpacks/Enigmatica9#577]
### Modpack Version

1.9.0

### Describe your issue.

Applying enchantments onto Annihilation Planes through Anvil enchants the whole stack.
![изображение](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9305291/1fec20db-0a3c-4432-98cd-be61df879b4b)

### Have you modified the modpack?

Yes

### User Modifications

Rubidium + Rubidium Extras

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

BloodyMan

**Comment by theboo** [comment]
I'd say this is about par for the course for enchantable stacksbles

**Comment by MuteTiefling** [comment]
Yep. I'd call it a feature, honestly.

Holding works the same way.

**Comment by BloodyManD** [comment]
Hm, but this allows duping of enchantments (fortune 4 can't be obtained via an enchanting table). There is Enchantment Extractor from IF in the modpack and Apotheosis way of extracting enchantments
