### ISSUE TITLE
Mouse Tweaks Scroll Crafting does not work

### ISSUE THREAD

**Issue by Reynales** [EnigmaticaModpacks/Enigmatica9#587]
### Modpack Version

1.10.2

### Describe your issue.

So the mod mouse tweaks has a function where when you are crafting something and u scroll up/down it automatically starts outputting into your inventory. This does not work and I do not know what is causing the issue. I tested it on 1.9.0 and 1.8.1 as well and it still did not work. Another thing is that you should be able to scroll inside an AE2 system to pick up or deposit items but that function does not work either.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

reynales

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by IgorKhramtsov** [comment]
There is a conflict with the Inventory Sorter mod. If you disable `wheelmovemodule` in the config of the Inventory Sorter, everything should work fine. This is also why any changes to the wheel-related settings of Mouse Tweaks do not have any effect.

**Comment by Reynales** [comment]
> There is a conflict with the Inventory Sorter mod. If you disable `wheelmovemodule` in the config of the Inventory Sorter, everything should work fine. This is also why any changes to the wheel-related settings of Mouse Tweaks do not have any effect.
 
I will try doing what you said when I get some free time today and post about it. Thanks for the info x).

**Comment by theboo** [comment]
I think we can leave this open so we can fix it in the pack before closing? Otherwise it will just remain an issue

**Comment by Kanzaji** [comment]
I included the required config change in PR #666 😄
