### ISSUE TITLE
[E9E] Crash in overworld related to brooms.

### ISSUE THREAD

**Issue by alikhamesy** [EnigmaticaModpacks/Enigmatica9#590]
### Modpack Version

in-dev

### Describe your issue.

Game randomly, and semi-frequently (on the order of every ~2-3 hours) crashing in the overworld. 

server and client slightly out of date with dev, on pull #569

### Crash Report

https://gist.github.com/alikhamesy/a2ae0aabf48f2d4442e0d001ebd72764

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

pilottroll

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
I found the issue reported here: https://github.com/JoeFoxe/Hexerei-1.19/issues/57
Seems to only happen when there's a broom seat equipped.

**Comment by MuteTiefling** [comment]
Looks like the latest Hexerei should fix this.
