### ISSUE TITLE
Dripstone cannot be crushed into Clay

### ISSUE THREAD

**Issue by ZZZank** [EnigmaticaModpacks/Enigmatica9#593]
### Modpack Version

1.10.2

### Describe your issue.

There are two curshing recipes for Dripstone, one is Dripstone->Pointed Dripstone, another is Dripstone->Clay. The second recipe is never usable. 
Same for Create's milling recipe.
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/47418975/e685fc75-391b-42a3-8002-dab22a769306)

### Have you modified the modpack?

Yes

### User Modifications

I removed EMI (it looks bad)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. We'll get that fixed up soon.
