### ISSUE TITLE
Immersive Engineering Blast Furnace Will not form

### ISSUE THREAD

**Issue by Matt-Petersen** [EnigmaticaModpacks/Enigmatica9#596]
### Modpack Version

1.8.1

## Description
The Immersive Engineering Blast furnace will not form when right clicked with the `Engineer's Hammer`.

The layout a is 3x3x3 cube following the instructions in the book.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

barbarick1ller

**Comment by MuteTiefling** [comment]
Thanks for the report. However, it is disabled. It shows disabled in the book and the quests explain it as well.

**Comment by NielsPilgaard** [comment]
Why is it disabled in normal mode?

**Comment by MuteTiefling** [comment]
Because it's such a short stepping stone. You use it once to make steel and dismantle it.

With it disabled, blast bricks were changed to use iron instead of steel so you can just go straight to the improved blast furnace.

**Comment by NielsPilgaard** [comment]
Super 👍
