### ISSUE TITLE
Visual - Non centered recipe for certus quartz growth

### ISSUE THREAD

**Issue by StefanosVorkas** [EnigmaticaModpacks/Enigmatica9#597]
### Modpack Version

1.10.2

### Describe your issue.

The  two options/descriptions for certus quartz growth come up as non centered, probably because the "set as default recipe" and "view recipe tree" buttons are throwing off the centering for the bottom bit 
![Screenshot 2023-08-12 012130](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/7047395/fc07d1b2-1271-479f-8664-ab781e9ce431)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

_vrk

**Comment by NielsPilgaard** [comment]
Thanks for the report

@theboo, our EMI bug relayer, would you mind relaying? 😄

**Comment by MuteTiefling** [comment]
went ahead and relayed, I think Boo is pretty busy these days ^_^
