### ISSUE TITLE
Falling out of world after dying

### ISSUE THREAD

**Issue by krusynth** [EnigmaticaModpacks/Enigmatica9#599]
### Modpack Version

1.5.0

### Describe your issue.

After dying, when the game attempts to reload, chunks do not load and I fall out of the world into the void, without dying again. It seems the game hangs on chunk loading, maybe?  I can load the inventory screen, etc., but attempting to save and quit also hangs - I have to end task. Reloading the world afterwards immediately sends me back falling into the void.

This happened a few months back and the same world file suddenly started working after a recent update to the pack, but now the world is stuck in this bugged state and I can't load my save game.

To fix this, I've tried disabling FTB Chunks, and I've tried adding FastLoad, but neither resolve the issue.

### Latest Log

https://gist.github.com/krusynth/959c1e35599ccb0eec7d96e570394bc2

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report. I recommend updating to the latest version, 1.10.2 at this time, and see if the issue persists.

**Comment by krusynth** [comment]
Excellent, the game loads now! I forgot I had reverted to the older version because I was having this trouble on a newer one, but updating to latest seems to allow the game to load. I'll reopen if I die and get stuck again.  Thanks so much!
