### ISSUE TITLE
Simply Tools

### ISSUE THREAD

**Issue by MelanX** [EnigmaticaModpacks/Enigmatica9#6]
### URL

https://www.curseforge.com/minecraft/mc-mods/simply-tools

### Why would you like the mod added?

It's not really a "please add this mod" but just a "hey, you added [Vanilla Hammers](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers-forge) to previous packs but this was merged with [Vanilla Excavators](https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge) and got rid of [MoreVanillaLib](https://www.curseforge.com/minecraft/mc-mods/morevanillalib). If you'd search for a 1.19 version of the hammers, you wouldn't find any".

**Comment by NielsPilgaard** [comment]
Awesome, thanks 👍
