### ISSUE TITLE
Machines for auto block placement not working in claimed chunk

### ISSUE THREAD

**Issue by ZZZank** [EnigmaticaModpacks/Enigmatica9#600]
### Modpack Version

1.9.0

### Describe your issue.

When inside an area already claimed by someone,  machines for auto block placement will not work. 
I tried Placer Module(Modular Router) and Placer(IF), none of them works. 
A solution is "Allow any fake player" in FTBTeams' config menu. After setting this to `true`, things seem to function normally. 

I'm using E9-1.9.0, but given that I didn't see any default config files related to FTBTeam in E9-1.10.2, I think this Bug also exists in the latest version. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
The trouble with setting this by default is that players can still grief you by placing fake player blocks just outside the claim and letting them go.

I'm not sure the benefits outweigh the negatives here?
