### ISSUE TITLE
[E9E] Change text in quest book to match new search in EMI

### ISSUE THREAD

**Issue by Small321** [EnigmaticaModpacks/Enigmatica9#607]
### Describe your suggestion

I was in discord earlier and I was wondering why I couldn't see the tools when I searched using $tools and they said that EMI uses # instead of $ now. The quest book doesn't show this and is still using the old method. 
![WinShot 881](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/97195679/b4e8a9d3-fd79-4c97-9a7d-c65697e38933)

### Why would you like this added/changed?

I didn't know that this change had happened and think that it would be good to update it since there might be other people who don't know about the change or new mod.

**Comment by MuteTiefling** [comment]
Good catch. I'll get that changed shortly. Thanks!

**Comment by MuteTiefling** [comment]
Also fixed up the storage tab while I was at it.
