### ISSUE TITLE
Pumpkin Warden from Oh The Biomes You'll Go spawning in End and causing server crashes

### ISSUE THREAD

**Issue by snafuPop** [EnigmaticaModpacks/Enigmatica9#609]
### Modpack Version

1.10.2

### Describe your issue.

(For reference, server was upgraded from E9 1.8.1 to 1.10.2 since server crashes began)

Pumpkin Warden mobs from Oh The Biomes You'll Go are spawning in the End. Once any player loads into the End and a Pumpkin Warden entity spawns, the server grows increasingly unstable and lags over the course of several hours, until it eventually crashes. Once the server crashes, the world/server becomes permanently inaccessible and a back-up world needs to be loaded.

Our understanding from the crash logs is that the Pumpkin Warden is attempting to path to a bell in the End, which it cannot accomplish but will continue to attempt to do so indefinitely.

![2023-08-12_13 11 18](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/17917612/b27a5508-5a11-4c7b-9535-8107fae9e24e)

### Crash Report

https://gist.github.com/snafuPop/a87c7e311fdcccb595e44458f9e22170

### Latest Log

https://gist.github.com/snafuPop/b05e19edc7225b80e2092af4adf9d2a6

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

@snafuPop, or @argoninium

**Comment by NielsPilgaard** [comment]
Thanks for the report. Do they spawn often?

@MuteTiefling think this could be related to our add_spawns script?

**Comment by MuteTiefling** [comment]
Probably. I'm not sure I understand how though.  I'll remove them from there, however, and see.

**Comment by snafuPop** [comment]
> Thanks for the report. Do they spawn often?
> 
> @MuteTiefling think this could be related to our add_spawns script?

They're a pretty common spawn, sometimes even appearing as soon as we load in. Thanks all for responding so quickly.

**Comment by snafuPop** [comment]
Oops, did not mean to close the issue.

They're a pretty common spawn, sometimes appearing as soon as we load in. Thanks for responding so quickly.
