### ISSUE TITLE
[E9E] Loot from minibosses is not fully localized

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica9#610]
### Modpack Version

1.10.2

### Describe your issue.

The loot from rift minibosses contains unlocalized strings:

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/636602/821f13c5-40b9-457f-97ec-c9423dd321d4)

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/636602/25b2041f-91d1-4f9e-967f-279658d474bb)

### Have you modified the modpack?

Yes

### User Modifications

Added shaders (Oculus, Rubidium, oculus-flywheel-compat), plus [OMD](https://www.curseforge.com/minecraft/mc-mods/oh-my-donation-omd) and [XtraCommands](https://www.curseforge.com/minecraft/mc-mods/xtra-commands)

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

iarspider

**Comment by MuteTiefling** [comment]
Thanks for the report. Could you please hold the item and type `/kubejs hand`? This will print the item nbt in chat. You can click it to copy it.

Paste the whole string here.

**Comment by iarspider** [comment]
Couldn't quickly find the helmet, but here is a chestplate with the same issue:
```
Item.of('twilightforest:knightmetal_chestplate', '{Damage:0,affix_data:{affixes:{"apotheosis:armor/attribute/blessed":0.37087363f},name:\'{"italic":false,"color":"#808080","translate":"misc.apotheosis.affix_name.three","with":["miniboss.enigmatica.skeleton_forsaken_knight\\\'s",{"translate":"affix.apotheosis:armor/attribute/blessed"},"",""]}\',rarity:"common",uuids:[[I;47928465,169953860,-1516760347,603175142]]},apoth_boss:1b,display:{Name:\'{"extra":[{"text":"Cuirass"}],"text":"Knightmetal "}\'},"quark:RuneAttached":1b,"quark:RuneColor":{Count:1b,id:"quark:blank_rune"}}').enchant('twilightforest:chill_aura', 3)
```

And here is the other chestplate
```
Item.of('twilightforest:yeti_chestplate', '{Damage:0,affix_data:{affixes:{"apotheosis:armor/attribute/gravitational":0.76734334f,"apotheosis:armor/attribute/ironforged":0.6717769f},name:\'{"italic":false,"color":"#33FF33","translate":"misc.apotheosis.affix_name.four","with":["miniboss.enigmatica.stray_hoarfrost_knight\\\'s",{"translate":"affix.apotheosis:armor/attribute/gravitational"},"",{"translate":"affix.apotheosis:armor/attribute/ironforged.suffix"}]}\',rarity:"uncommon",uuids:[[I;-858456374,-1169603029,-1828709150,-1470886056]]},apoth_boss:1b,display:{Name:\'{"extra":[{"text":"Chestplate"}],"text":"Yeti "}\'},"quark:RuneAttached":1b,"quark:RuneColor":{Count:1b,id:"quark:blue_rune"}}').enchant('naturesaura:aura_mending', 1)
```

**Comment by MuteTiefling** [comment]
Thanks, I've relayed the issue.
