### ISSUE TITLE
Coke Bricks hidden from EMI

### ISSUE THREAD

**Issue by Luxaedel** [EnigmaticaModpacks/Enigmatica9#611]
### Modpack Version

1.10.2

### Describe your issue.

EMI regex hides 'Coke Bricks' so the coke oven cannot be constructed.

### Have you modified the modpack?

Yes

### User Modifications

Added FTB Essentials

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Igeyorhm

**Comment by MuteTiefling** [comment]
Thanks for the report.

Assuming this is the issue. https://github.com/EnigmaticaModpacks/Enigmatica9/blob/master/kubejs/client_scripts/base/emi_material_unification.js#L106

We'll get that fixed up soon.
