### ISSUE TITLE
[TYPO][QUEST][E9E] Discovering Enigmatica

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica9#614]
### Modpack Version

1.11.1

### Describe your issue.

Quest mentions "Exploration questline", which is actually called "Discovery"

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks, I'll get that fixed up here soon.
