### ISSUE TITLE
Material Laser Base does not require the Lens of Ender to work

### ISSUE THREAD

**Issue by GlassRavioli** [EnigmaticaModpacks/Enigmatica9#616]
### Modpack Version

dev

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/137257788/6ec8a4ad-de1e-4ab1-b08e-5774c69da2b1)

In "The End" biome, using the material laser base with four laser drills, I'm able to get all four of the items without the Lens of Ender being present in the machine. Using the Lens of Ender doesn't seem to change the behavior.

The Fluid Laser Base does not have this issue and properly requires the Lens of Ender to generate the Resonant Ender.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

rickyrandom

**Comment by MuteTiefling** [comment]
Thanks for the report. I'll look into a way to re-work this.
