### ISSUE TITLE
archwood broom quest (expert)

### ISSUE THREAD

**Issue by kads-e** [EnigmaticaModpacks/Enigmatica9#617]
### Describe your suggestion

the quest in the hexerei quest line only takes witch hazel and willow while the one in chapter one also takes archwood
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/99212606/cc489336-886d-48ab-9fe0-0bbdcd28710d)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/99212606/364c9367-0fd7-4219-a7df-0a63e15c62eb)

### Why would you like this added/changed?

I rly want a archwood one but also get the quest ;w;

**Comment by MuteTiefling** [comment]
Thanks for the report. I'll get this fixed up soon.
