### ISSUE TITLE
(expert) crushing rune quest

### ISSUE THREAD

**Issue by kads-e** [EnigmaticaModpacks/Enigmatica9#618]
### Describe your suggestion

the quest asks for a crush rune which you already have from the beginning 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/99212606/54ad679a-456a-48fe-a747-c95e8db140ee)

### Why would you like this added/changed?

you wouldnt need to wait for the drop to complete the quest if you get sensitive first

**Comment by MuteTiefling** [comment]
Thanks for the report. The Crush Glyph is marked as Optional in the quest, meaning you don't actually need to get it. It's simply there for illustration purposes

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/5e284921-b36d-4ca6-9f1f-d012acca37dc)
