### ISSUE TITLE
Issues in chat from emojiful

### ISSUE THREAD

**Issue by jinkhya** [EnigmaticaModpacks/Enigmatica9#625]
### Modpack Version

1.11.2

### Describe your issue.

When emojiful is present, some things break in chat.
For example /spark tps shows empty.

**With emojiful :** 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/10158963/0dd11aec-eeb4-4f35-a424-ab287806979a)

**Without emojiful :**
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/10158963/67f5c88b-9d89-46a3-b54a-0363c760fdd7)

I also found that if using a discord relay mod (discord integration forge in my case) you only see the name of the person writing in discord in game, but not the actual message. Like so : 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/10158963/a2498fc4-81de-4b70-9ed9-5ed1352f1a32)

Thanks in advance
Jin

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

JinKhya

**Comment by NielsPilgaard** [comment]
I relayed it, thanks 👍

**Comment by NielsPilgaard** [comment]
We'll consider it, thanks for the suggestion :)

**Comment by NielsPilgaard** [comment]
We've decided to remove Emojiful until the issue has been resolved :)
