### ISSUE TITLE
Several Ars Glyphs cannot be cut into parchment

### ISSUE THREAD

**Issue by lavraleksej** [EnigmaticaModpacks/Enigmatica9#630]
### Modpack Version

1.11.2

### Describe your issue.

The Burst Glyph, Blank Glyph and glyphs from the Ars Scaling Compats mod (Resize, Shrink and Expand) are missing the 
`forge:glyphs` tag and the cutting board parchment recipe
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/35431436/19106a66-d691-436f-a32a-a0dbaa2d3cdf)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Sakuya (lavraleksej)

**Comment by MuteTiefling** [comment]
Ah thanks. These got added later and I forgot to update the recipes. I'll get them fixed soon.
