### ISSUE TITLE
Quest Typo E9E millstone

### ISSUE THREAD

**Issue by telomar** [EnigmaticaModpacks/Enigmatica9#637]
### Describe your suggestion

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/128550940/42a2f067-4cd7-46dc-81a9-1a23897bffde)
Looks like it is missing a word, maybe change to "Millstone can process tougher ores and"

### Why would you like this added/changed?

typo

**Comment by MuteTiefling** [comment]
Thank you! That'll be fixed up next version.
