### ISSUE TITLE
Ancient Debris biome information not present in EMI

### ISSUE THREAD

**Issue by mherzogjr** [EnigmaticaModpacks/Enigmatica9#638]
### Modpack Version

1.11.2 (E9 normal)

### Describe your issue.

Trying to collect ancient debris using laser drill.  I have selected 6 brown lenses and have been trying depths between -20 and 20 within the nether (I saw a video that showed a JEI biome setup that said 0 - 20 is best for ancient debris) and have not received any ancient debris from this process over a solid 2 hours. 

Looking in EMI I could not find any similar information on biomes that are black/whitelisted, depths, etc.  I am not sure if the issue is that it's just missing from EMI, or that it's a bug related to harvesting ancient debris. 

Either way the 2 issues seem to be 1) the information is not accessible in EMI and 2) I do not appear to be able to pull ancient debris using the laser drill in the nether

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

blackbrant

**Comment by MuteTiefling** [comment]
Thank you! That'll be fixed up next version.
