### ISSUE TITLE
Apotheosis Hellshelf not craftable in Occultism storage

### ISSUE THREAD

**Issue by Noxtralis** [EnigmaticaModpacks/Enigmatica9#643]
### Modpack Version

1.11.2

### Describe your issue.

The recipe is complete but there is no output. 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/38422731/9785c86b-8e8a-48df-9c79-9023aae717c3)
This works just fine in Ars crafting tho
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/38422731/37166507-a545-4129-a4e2-f0a9485fcac5)

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

noxtralis

**Comment by MuteTiefling** [comment]
I'm no longer able to reproduce this, so I'll go ahead and close this out. Must have been fixed somewhere along the way.
