### ISSUE TITLE
[AARGH] Torchberry Plant

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica9#645]
### Describe your suggestion

Make some sort of recipe to craft torchberry plants, because they get destroyed when you accidentally hit it with anything other than shears, which you will never have equipped by default pretty much.

### Why would you like this added/changed?

n/a

**Comment by MuteTiefling** [comment]
You'll be able to plant torch berries on the bottom of dirt, like you can plant other berry plants.
