### ISSUE TITLE
visual bug with EMI mod

### ISSUE THREAD

**Issue by telomar** [EnigmaticaModpacks/Enigmatica9#648]
### Modpack Version

1.11.2

### Describe your issue.

if you have recipes bookmarked that have quantities for their outputs, the numbers for the output show through tooltip text:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/128550940/1fc62f3c-49d6-49f0-85a0-71dff2b7e8fa)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/128550940/1b3e4cfa-f53d-44ec-96ee-bbb66e3d188a)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

telomar

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll relay that.

**Comment by MuteTiefling** [comment]
I'm having trouble replicating this. Are you certain no other mods have been added?

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/8f11a484-e10e-40a7-9b7f-99d6086b8002)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/ae1a74fd-35fc-4239-a94d-1c0b105f44a6)

**Comment by telomar** [comment]
Yes, no mods added or changed.  

It looks like you are mousing over another bookmarked recipe; I am only seeing it when I mouse over an item in an inventory where the tooltip is over the bookmarked recipes.  I play windowed so it might not show up on larger resolutions or smaller UI scales.

**Comment by MuteTiefling** [comment]
Alright, I'll give that a try.

**Comment by MuteTiefling** [comment]
Ahh, there we go. So it's specifically while in Sophisticated Storage then. I can reproduce it now. Thanks for the extra info!
