### ISSUE TITLE
[Mod suggestion] Entangled!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#65]
### URL

https://www.curseforge.com/minecraft/mc-mods/entangled

### Why would you like the mod added?

It's like Mekanism Entangloporter, but can imitate other blocks with a distance of 1000 blocks by default.
It was already in E6 and E8 so I think I don't need to explain what it does 😅

**Comment by MuteTiefling** [comment]
I think this one worked pretty nicely with the restrictions we had in E6 (no cross dim). I might want to trim the range down too, but that's an easy configuration change.

**Comment by Kanzaji** [comment]
Just the fact it will be in would be actually awesome :D I remember using it in just one room to get access to really tight places and just to not have cables everywhere, never actually tried long-range transfer and I think not a lot of people use long-range anyways. So I'm fine with lower range.
