### ISSUE TITLE
[Ars Elemental] Trinket Pouch bugging out

### ISSUE THREAD

**Issue by Yusunoha** [EnigmaticaModpacks/Enigmatica9#654]
### Modpack Version

1.11.2 [Expert]

### Describe your issue.

I'm running into a problem using the trinket pouch from Ars Elemental. I created all the familiar rings from Occultism, and I crafted the trinket pouch from Ars Elemental to store all those familiar rings. 

If I put one or two rings in the pouch everything's still fine, but if I store all of them in the pouch and I close the pouch, I can no longer open it afterwards. I tried putting the pouch in the bundle curios slot and open it using a hotkey, but that doesn't work either.

After this I spawned back in all the familiar rings and pouch and tried it again, and the same thing happens.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

yusunoha

**Comment by MuteTiefling** [comment]
Thank you for the report. I'm unable to replicate the issue with the familiars I've tried. It's possible that this is limited to a specific one. Would you mind repeating your test but try opening the pouch and removing them with each new familiar? If you add one and are suddenly unable to pull any out, then the last one is likely the culprit.

**Comment by Yusunoha** [comment]
Hmm, I tried it again this morning, created a backup and multiple copies of the items, but I wasn't able to replicate the issue either anymore. I tried it in different ways, but this time the pouch didn't bug out. 

When it happened yesterday it did happen after the game was already running for a good amount of hours, and this morning it was a fresh loaded instance, but that'd make it a very rare bug to occur. So I guess you can call this issue closed.
