### ISSUE TITLE
Aura Generation in Nomadic Tents

### ISSUE THREAD

**Issue by kjchiamu** [EnigmaticaModpacks/Enigmatica9#655]
### Modpack Version

Enigmatica 9 Expert 1.11.1

### Describe your issue.

Aura does not generate in nomadic tents. Ancient Trees don't generate it, and the Linger Absorber doesn't work there either.

Aura still depletes in this dimension though, causing permanent negative effects, such as breathless..

Attempted to update the auraTypeOverrides value for Natures Aura, but the value gets reverted on Server startup.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by SeooY** [comment]
I can't replicate the issue with the Lingering Absorber. It generates Aura just fine inside the Nomadic Tent dimension.
https://streamable.com/sll6gr

**Comment by MuteTiefling** [comment]
I had a bit of a mishap in my tent as well and was able to transport Aura in with an Ars Nouveau portal and an Aura Cart. 

I also just tested the Lingering Absorber and had no issues generating Aura like Seooy. I suspect something may have simply been missing from the structure.

**Comment by kjchiamu** [comment]
You are correct, sorry, my bad. Thanks
