### ISSUE TITLE
summon wilden tablet bug [E9E]

### ISSUE THREAD

**Issue by telomar** [EnigmaticaModpacks/Enigmatica9#656]
### Modpack Version

1.11.2

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/128550940/af76cba1-7a55-4c99-9f4e-02e4341ebf2b)
I think I either got this from a lootr chest in the snow queen castle or as an ars reward, I'm not sure which.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

telomar

**Comment by MuteTiefling** [comment]
Thanks for the report! I'm having a terrible time getting this to drop and I'm fairly confident it's not actually part of the Ars quest loot or quest rewards. 

However, I'm adding an extra check to ensure it's removed from any loot table that might be dropping it.
