### ISSUE TITLE
[E9E] Accept any Potion of Ancient Knowledge in recipes

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica9#657]
### Describe your suggestion

Recipes for Ars' Blank Thread and PnC Gilded Upgrade should accept any version of "Potion of Ancient Knowledge (4:00)" (Create, Hexerei, ...)

### Why would you like this added/changed?

Recipes for Ars' Blank Thread and PnC Gilded Upgrade explicitly require **Hexerei's** "Potion of Ancient Knowledge (4:00)", and batch-crafting potions with Hexerei is not easy: there is only one tank, which acts as both input and output, and potions doesn't have a bucket form, so no easy filtering. 

Another option is to create these items in Create's heated mixer in addition to the Hexerei's cauldron.

**Comment by MuteTiefling** [comment]
I don't believe there's any simple way for me to tell it to use any potion; potion fluids contain nbt and everyone does them slightly differently. Any bottled potion will convert into a hexerei potion in there, however, if you simply right click the bottle on the cauldron.

That said, when I coded these in I did so knowing that you'd never really have to craft many of them. After you build your armor, after all, you'll never do them again outside of extreme cases of total inventory loss. They're meant to be done by hand, essentially. 

What I can do to improve them, perhaps, would be to reduce the amount of potion they require. So a single brew of potion could let you do 8 threads, for example. Would that help, do you think?

**Comment by iarspider** [comment]
I see. For me, either solution (crafting 1 or 8) works. Thanks!

**Comment by MuteTiefling** [comment]
Alright, I'm marking this as Not Planned simply because the fix isn't the suggestion offered. However, the potion cost per thread will be reduced to 200mb from 2000mb.
