### ISSUE TITLE
[expert] Tectonic Grenades not mining amethyst blocks and glowstone blocks

### ISSUE THREAD

**Issue by kads-e** [EnigmaticaModpacks/Enigmatica9#658]
### Modpack Version

1.11.2

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/99212606/8cc9cec0-8ceb-4bc7-bdf3-b994b9d46b77)
would help with mining in hollow hills 

### Have you modified the modpack?

No

### User Modifications

no

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

pink_kadse

**Comment by MuteTiefling** [comment]
It appears that these are coded to only break stone and dirt type blocks. https://github.com/CoFH/ThermalCore/blob/1.19.x/src/main/java/cofh/thermal/core/item/EarthChargeItem.java#L45

**Comment by kads-e** [comment]
interesting, but then how are they breaking ores?
I would guess they have the tag stone somehow, but it also broke certus quartz for example 
but I'm too stupid for coding anyways :D

**Comment by MuteTiefling** [comment]
It's looking at the base material, as far as I understand, and ores are all stone as a base material.
