### ISSUE TITLE
Item to Gas Conversion

### ISSUE THREAD

**Issue by SaltymcSaltface** [EnigmaticaModpacks/Enigmatica9#662]
### Describe your suggestion

Change Item to Gas conversion for Flint > Oxygen to 1 salt item per 100mb, Salt > HCL to 1 salt item per 100mb.

### Why would you like this added/changed?

So I'm not sure if this is intended or not, but the item to gas conversion for salt to HCL is 2mb per item, which means it takes 100 pieces of salt, which is over 11 blocks, to process ONE raw ore in the Chemical Injection chamber. I get that you're supposed to be incentivized to automate this with brine evaporators and whatnot, but you'd still be incentivized to do so if it took 20 salt, or even 2 salt items to process the ore. As it is, I'd advocate for bringing the conversion amount up to 100mb, or 200mb, or not even having the item to gas conversions, as it's misleading to think its remotely worthwhile to use mined salt. 
The same thing applies to flint actually. Gathering 128 flint/salt to process a stack of raw ore would be a chore, but one worth doing.

**Comment by MuteTiefling** [comment]
Thanks for the suggestion! However, I would rather people automate the gases. The item conversions, I've always seen as a quick way to do a handful of recipes before the full production line is set.

**Comment by SaltymcSaltface** [comment]
The only recipes that might theoretically be worth doing is gunpowder to sulfur with HCl, or charcoal to sulfer with Oxygen, if you cant find any sulfur. 
Substrate to HDPE is fine because it only takes 10mb to do so. This is specifically about ore processing. 100 items needed to process one raw ore is incredibly excessive, even when the intent is automation. It makes the transition from 2 output per raw to 3-4 so irritating that I prefer to switch to a different mod, such as Ars Nouveau, or even -and it truly pains me to say this- immersive engineering.
