### ISSUE TITLE
[expert] natures aura adept hopper recipe missing

### ISSUE THREAD

**Issue by kads-e** [EnigmaticaModpacks/Enigmatica9#663]
### Modpack Version

since 1.11.2

### Describe your issue.

the recipe was still in 1.11.1 and is missing since 1.11.2, because the change was not in the changelog and you still need it for the hive hopper I would assume it was removed on accident 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

pink_kadse

**Comment by MuteTiefling** [comment]
The recipe is showing fine on my end: 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/08b3e22e-dae0-48ab-b75d-39f9fc68d7bd)


Please double check that you don't have any KubeJS errors. If you do, run `/reload` until they go away.

**Comment by kads-e** [comment]
hmm, I didnt remember having any, but now I have the recipe...
