### ISSUE TITLE
[E9E] Iron in Sushi Rice Cooker

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica9#664]
### Modpack Version

E9E 1.11.2

### Describe your issue.

The rice cooker from Sushi Go Crafting uses 6 iron ingots to make, this seems extremely expensive for the point where you'd want to make it.

I think this one slipped through in making it use Tin Ingots.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Good catch. Thanks for the report.

I'll get that changed over to something more appropriate.

**Comment by MuteTiefling** [comment]
I'll add something for the seaweed too since you mentioned it
