### ISSUE TITLE
[E9E/1.11.2] Ars Nouveau Blink glyph with Warp scroll combo doesn't teleport mobs.

### ISSUE THREAD

**Issue by Yusunoha** [EnigmaticaModpacks/Enigmatica9#665]
### Modpack Version

1.11.2

### Describe your issue.

Using the Ars Nouveau Blink glyph you should be able to teleport mobs to a specific locations if you hold a set warp scroll in your offhand. 

Sadly in v1.11.2 of the pack this doesn't seem to work. I've tried it on different mobs, tried holding the scroll in my offhand and in my hotbar, tried using a stabilised warp scroll and the position is set to a chunkloaded area. None of this worked.

This issue has been reported by a couple of players in the discord channel, so it's an issue that's happening for others aswell.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Yusunoha

**Comment by MuteTiefling** [comment]
Seems to only be an issue in the Twilight Forest. I'm assuming this is related to the issues we had early on with stabilized warp scrolls.

**Comment by MuteTiefling** [comment]
Relayed here: https://discord.com/channels/743298050222587978/1145106688467292230
