### ISSUE TITLE
[E9E] Add Aquatic Entangler to Scribe's Table quest in Expert Chapter One

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica9#667]
### Describe your suggestion

The Antique Ink part of the Scribe Table recipe is causing constant confusion to players, thinking they have to manually fish for it and getting frustrated, while the Aquatic Entangler is a very easy and accessible way of getting it. The Aquatic Entangler is mentioned already in the JEI info tab, but it seems to be going unnoticed, adding it to the quest would make it abundantly clear that it's the intended way of getting the ink at that point.

### Why would you like this added/changed?

More clarity on where to get the Ink, and avoid constant confusion to players that are manually fishing for the Ink and not getting it.

**Comment by MuteTiefling** [comment]
Gonna change this a bit by locking it behind the death tome quest. That quest is also bound to an advancement rather than mob kills.
