### ISSUE TITLE
Slag gravel does not appear in EMI in E9E

### ISSUE THREAD

**Issue by GlassRavioli** [EnigmaticaModpacks/Enigmatica9#669]
### Modpack Version

dev

### Describe your issue.

When using Crush to break down basaltz, the slag that is generated can then also be crushed down into a block that EMI doesn't recognize: slag gravel.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

rickyrandom

**Comment by MuteTiefling** [comment]
Thanks for the report. I see you're on the dev branch, but are you sure you're on the latest commits? This was fixed a few weeks ago and is live in 1.11.2: https://github.com/EnigmaticaModpacks/Enigmatica9/pull/612

**Comment by GlassRavioli** [comment]
Ah, okay. Our server is still on 1.11.1.

**Comment by MuteTiefling** [comment]
Alright. Gonna close this out then.
