### ISSUE TITLE
[Expert] Bumblezone Honey Crashes Game While Using Create Spout and Pump

### ISSUE THREAD

**Issue by SaturdayHS** [EnigmaticaModpacks/Enigmatica9#670]
### Modpack Version

v1.11.2

### Describe your issue.

While trying to pump Bumblezone Honey with the Create Pump into the Create Spout, the game crashes. The way I have it set up is that I have a 1x1 hole with a Create Pump above the hole that pumps into a Create Spout with a Depot under that, since Bumblezone doesn't have a 'Spout to Bucket' recipe listed under JEI, that might be why it crashed. Also, whenever this specific honey starts to flow, that also caused a crash.
I was also looking for the honey fluid but couldn't see it listed, even though there is a bucket for this honey.

### Crash Report

https://gist.github.com/SaturdayHS/b430f9a1a2893c8a7d3fd6412f9fdb6c

### Latest Log

https://gist.github.com/SaturdayHS/74e4bef6c0631a224fd1e5cc0ef1c544

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

saturdayhs

**Comment by NielsPilgaard** [comment]
Thanks for the report. This is fixed in a recent Bumblezone update, and we'll make sure to include it in our next update :)
