### ISSUE TITLE
[Expert] "Unlocked Nether" achievement description is not localized

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica9#671]
### Modpack Version

1.11.2

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/636602/62cbee27-71fe-4366-8d52-3e57cb9c72d4)

### Have you modified the modpack?

Yes

### User Modifications

Added shaders (Oculus, Rubidium, oculus-flywheel-compat), plus [OMD](https://www.curseforge.com/minecraft/mc-mods/oh-my-donation-omd) and [XtraCommands](https://www.curseforge.com/minecraft/mc-mods/xtra-commands)

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

iarspider

**Comment by MuteTiefling** [comment]
Thanks for the report! I'll get that fixed up
