### ISSUE TITLE
[E9E][TYPO][QUEST] Millstone

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica9#672]
### Describe your suggestion

"the Millstone can tougher ores" -> Mill? Grind? Crush? Process? Transmogrificationate?

I don't want to tougher my ores! They're tough enough!

### Why would you like this added/changed?

Typo

**Comment by MuteTiefling** [comment]
Duplicate https://github.com/EnigmaticaModpacks/Enigmatica9/issues/637
