### ISSUE TITLE
[E9E] Range 3 Upgrades for Mining Gadgets are uncraftable

### ISSUE THREAD

**Issue by Arlyse-1** [EnigmaticaModpacks/Enigmatica9#675]
### Modpack Version

1.11.2

### Describe your issue.

The Tier-3 range upgrade for the Mining Gadgets laser requires a Tier-3 range upgrade instead of a Tier-2 to craft, making it unobtainable. 

![2023-08-28_16 10 14](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/143450125/70f0f324-2653-4e6c-99f2-dbc0ab32e234)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

lazyjuan

**Comment by MuteTiefling** [comment]
Thanks for the report!
