### ISSUE TITLE
Wool cannot be used as sails of Create Windmill

### ISSUE THREAD

**Issue by ZZZank** [EnigmaticaModpacks/Enigmatica9#678]
### Modpack Version

1.12.1

### Describe your issue.

The Windmill quest in Create chapter says that Windmill accepts wool, but it in fact does not accept any kinds of wool, only  sail/sail_frame can be recognized by windmill. 

I'm playing Expert Mode. 

### Have you modified the modpack?

Yes

### User Modifications

I removed EMI. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NeosGhost** [comment]
version 1.18.0 windmill quest is showing wool as a substitute for sail blocks.


thanks

**Comment by MuteTiefling** [comment]
Ah yep. I've got that removed now from the task. Should only accept sails next update.
