### ISSUE TITLE
[E9E] Nature's Blessing Ironwood Hoe does not bonemeal sage or occultism demon dream fruit (need to check other modded crops) 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica9#681]
### Modpack Version

1.12.1

### Describe your issue.

Using the loot Nature's Blessing ironwood hoe from the naga, the hexerei sage and occultism demon dream fruit are not bonemealable. The other hexerei plants are, need to check the rest; Vanilla crops are fine. 

### Have you modified the modpack?

Yes

### User Modifications

Experience Obelisk
Full brightness toggle + collective
Twilight flavors and delight
FTB essentials
Disabled all the 'server' related mods except for serverconfig updater. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ZephyrWindSpirit

**Comment by MuteTiefling** [comment]
Thanks for the report, I've relayed the issue. https://github.com/Shadows-of-Fire/Apotheosis/issues/1007

**Comment by MuteTiefling** [comment]
Eh, turns out it's quark breaking this...
