### ISSUE TITLE
"Use Butcher knife to obtain Tallow. Butcher knife is disabled."

### ISSUE THREAD

**Issue by Ved-s** [EnigmaticaModpacks/Enigmatica9#682]
### Modpack Version

1.12.1

### Describe your issue.

![](https://cdn.discordapp.com/attachments/1138181433928724635/1148592239879147540/image.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ved_s

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll get that fixed for the next version.
