### ISSUE TITLE
Achievement for placing belts called `Kelp drive` though belts aren't made of kelp anymore

### ISSUE THREAD

**Issue by Ved-s** [EnigmaticaModpacks/Enigmatica9#684]
### Modpack Version

1.12.1

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/53968411/510bfa7b-d838-4646-9c37-ad6c36ac8fb3)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/53968411/84a7a231-e7c9-4742-a6c7-1e4ee552fd43)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ved_s

**Comment by MuteTiefling** [comment]
Thanks for the report!
