### ISSUE TITLE
Harvesting magebloom with `Nature's blessing + Fortune` hoe produces magebloom seeds

### ISSUE THREAD

**Issue by Ved-s** [EnigmaticaModpacks/Enigmatica9#686]
### Modpack Version

1.12.1

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/53968411/d839a9bb-663f-4a47-85b8-b4a15b787b09)
Harvesting magebloom with hoe with `Nature's Blessing III` and `Fortune III` produces magebloom seeds
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/53968411/a3a8202d-007f-417a-9c4a-a531e932ea1d)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ved_s

**Comment by MuteTiefling** [comment]
Thanks for the report. However, this plant has a low chance of giving you seeds when it is harvested. There's nothing wrong with getting seeds from this interaction.
