### ISSUE TITLE
Disabled items show up in ore dictionary recipes

### ISSUE THREAD

**Issue by Ved-s** [EnigmaticaModpacks/Enigmatica9#687]
### Modpack Version

1.12.1

### Describe your issue.

https://cdn.discordapp.com/attachments/1138181433928724635/1149782403997511680/image.png
Power cables from Powah are disabled, but visible in oredict

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ved_s

**Comment by theboo** [comment]
It looks like this recipe just accepts anything with forge energy capability? It isn't tag based, and I'm pretty sure our hide scripts should be covering these already so maybe this isn't fixable, but still worth looking in to, may need to get emi devs involved.

**Comment by MuteTiefling** [comment]
It was doing this in jei too. I think it's just not fixable because it works exactly as boo describes. Anything with rf capabilities.
