### ISSUE TITLE
[E9E] Heart of the sea can be obtained not by crafting

### ISSUE THREAD

**Issue by iarspider** [EnigmaticaModpacks/Enigmatica9#691]
### Modpack Version

1.12.1

### Describe your issue.

One of players on my server got Heart of the Sea from killing an Elder Guardian. Also he found Empty Blaze Burners somewhere ("probably from Create dungeon", the one with spikes and drills).

### Have you modified the modpack?

Yes

### User Modifications

Added shaders (Oculus, Rubidium, oculus-flywheel-compat), plus [OMD](https://www.curseforge.com/minecraft/mc-mods/oh-my-donation-omd) and [XtraCommands](https://www.curseforge.com/minecraft/mc-mods/xtra-commands)

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

iarspider

**Comment by MuteTiefling** [comment]
Thanks for the report. 

I'm not terribly concerned about the empty blaze burners as they'd be a major hassle to remove. They're also so late in the pack that it doesn't have any appreciable impact.

I'll certainly look into what's going on with the Heart of the Sea, however.

**Comment by iarspider** [comment]
The empty burners are unusable in Expert, so they are just junk. Or the "vanilla" interaction still works?

**Comment by MuteTiefling** [comment]
the normal interaction still works fine.
