### ISSUE TITLE
Starbuncle gas transfer

### ISSUE THREAD

**Issue by squillis** [EnigmaticaModpacks/Enigmatica9#692]
### Modpack Version

1.13.0

### Describe your issue.

When transporting gasses with starbuncles, they only seem to transfer when there's an empty inventory, but if you add a 3rd inventory (second deposit) inventory they'll keep transferring to the 1st bound inventory. They'll only transfer once if there is 1 inventory and once that inventory has gas in it they stop. I can provide video evidence if needed. I reproduced this many times.

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

Yes

### User Modifications

Added shaders

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

spmirhs

**Comment by MuteTiefling** [comment]
This is due to the very high transfer threshold we've set in the pack. It was done to help them transfer as much per trip as possible so they'd have very good throughput. 

It maybe doesn't need to be as high as it is, however. I'll look at reducing it somewhat.
