### ISSUE TITLE
Pulverizer/backpack voiding potions

### ISSUE THREAD

**Issue by squillis** [EnigmaticaModpacks/Enigmatica9#693]
### Modpack Version

1.13.0

### Describe your issue.

if you have stack upgrades in a backpack, and use a pulverizer to pull the potions out of the backpack, it pulls the whole stack and voids anything over 1 potion. D:

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

Yes

### User Modifications

Shaders

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

spmirhs

**Comment by MuteTiefling** [comment]
Issue relayed to Sophisticated Backpacks as it seems they should be preventing extracting more than 1 of a non-stackable item

**Comment by MuteTiefling** [comment]
Should be fixed with the recent releases of Sophisticated backpacks/core/storage
