### ISSUE TITLE
Breaking Dimen

### ISSUE THREAD

**Issue by squillis** [EnigmaticaModpacks/Enigmatica9#698]
### Modpack Version

1.13.0

### Describe your issue.

Breaking tier 2 dimensional storage stabilizers crashes my game, everytime I break them off the storage system.

### Crash Report

https://gist.github.com/squillis/6e902038bf43662d04ff6ee5a7f6a358

### Latest Log

https://gist.github.com/squillis/0a361a0d0050efdc90a070b19d3cd9d7

### Have you modified the modpack?

Yes

### User Modifications

shaders

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

spmirhs

**Comment by MuteTiefling** [comment]
Could you please try this without the mods you've added for shaders?
