### ISSUE TITLE
Lazier AE2

### ISSUE THREAD

**Issue by Zarrexx** [EnigmaticaModpacks/Enigmatica9#7]
### URL

https://www.curseforge.com/minecraft/mc-mods/lazierae2

### Why would you like the mod added?

Played with this recently for the first time and it removed a lot of the headache that comes with using AE2 and automating/waiting for Inscribers and some of the more annoying AE2 machines. Currently in 1.18.2 but it looks promising for 1.19

**Comment by Zarrexx** [comment]
Further suggestion: The "YUNG's Better" series of mods. In my opinion they greatly enhance portions of the game that are lacking in their vanilla implementation, such as desert temples, strongholds, and underwater temples.

**Comment by NielsPilgaard** [comment]
Please make separate issues per mod, or bundle very similar ones like the Yung mods :)

Lazier AE2 is a nope, it looks like it makes things just a bit too easy.
