### ISSUE TITLE
Spellbound invar is still referred to as compressed iron in advancements

### ISSUE THREAD

**Issue by Ved-s** [EnigmaticaModpacks/Enigmatica9#702]
### Modpack Version

1.13.0

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/53968411/2e24b09d-21be-4cd7-89ab-6535af70e0aa)

### Have you modified the modpack?

Yes

### User Modifications

Ears, Build Guide

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ved_s

**Comment by MuteTiefling** [comment]
Thanks for the report!
