### ISSUE TITLE
Soul Gems Allow For the Deployment of Multiple Familiars

### ISSUE THREAD

**Issue by modified-reality** [EnigmaticaModpacks/Enigmatica9#705]
### Modpack Version

1.13.0

### Describe your issue.

![Screenshot from 2023-09-23 21-43-01](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/68307393/8826b26a-ea13-460c-92b0-a8a812663efa)

By deploying a familiar and putting it inside a soul gem, you are able to deploy an additional familiar while it is inside the gem. This allows you to let the previous familiar out of the soul gem, which results in the deployment of a second familiar. This can be done an infinite number of times with however many soul gems. It resets your familiars back to one if you switch with the duplicates deployed though. This bug has significant impact, as you could quite conceivably have a massive storm of Wixies and every familiar perk at once. 
![Screenshot from 2023-09-23 19-24-44](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/68307393/956a17a2-a14f-4c45-8349-0914a58061b9)

### Have you modified the modpack?

Yes

### User Modifications

Rubidium and Complimentary Re-imagined for the Shader

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Wettuce

**Comment by MuteTiefling** [comment]
Thanks for the report! Should be all fixed in the next release.
