### ISSUE TITLE
E9E Bugged enigmatic grave crashes the game

### ISSUE THREAD

**Issue by SpacialNightmare** [EnigmaticaModpacks/Enigmatica9#706]
### Modpack Version

1.13.0

### Describe your issue.

I was fighting the gate of the wilden grove and i died twice in a row, while running back into the fight i tried to pick up my first grave, however that seemed to crash my game, now everytime i log back into the game the grave is still there with a bunch of wilden spikes floating on top, and i can loot the grave a bunch of times, and seems to randomly crash when looting the grave, sometimes it immediately crashed, and other times i could loot it 5 times before crashing. I tried removing it in creative, didnt work.
![2023-09-24_22 51 32](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/48810731/ea0e28f5-c60f-4a74-917a-d91e9e9eef1c)

seeing no way to remove the grave, i have loaded into a backup, i do still have the old save file available if needed/wanted
i provided 2 logs, 1 leading up to the initial crash, and 1 leading up to the crash with the bugged grave. the crash logs were identical, so i only provided 1

### Crash Report

https://gist.github.com/SpacialNightmare/9af60bcfb87095e242ca076bc0407044

### Latest Log

https://gist.github.com/SpacialNightmare/01edf899f14a5f6a0769d63b7cda9429

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

spacialnightmare

**Comment by NielsPilgaard** [comment]
Thanks for the report!
@Quarris it looks to me like you might've fixed this already in your latest release, could that be the case? :)

**Comment by Quarris** [comment]
I have released a beta update to test some new features which clearly didn't work, so I archived that release as soon as issues started popping in. I believe the latest visible release on curseforge should now be stable.

**Comment by NielsPilgaard** [comment]
Super, thanks. I'll update and release e9 1.15.0 in approx. 36 hours :)

**Comment by DereC4** [comment]
Oh hey you're the guy who made the cool conveyor belts using armor stands
