### ISSUE TITLE
Suggestion: AECapFix

### ISSUE THREAD

**Issue by 62832** [EnigmaticaModpacks/Enigmatica9#707]
### URL

https://www.curseforge.com/minecraft/mc-mods/aecapfix

### Why would you like the mod added?

Disclaimer: I am the developer of the mod in question.

I put together this mod in order to fix various broken interactions involving AE2 and Powah, due to the lack of invalidation for these mods' Capabilities.

The developer for Energy Meter [has personally vouched for this mod](https://discordapp.com/channels/195234321836146688/1138181433928724635/1153730929949417502) in the Enigmatica Discord server as quoted below, since one such interaction affecting the Enigmatica packs in particular is the interaction between Powah blocks and the Energy Meter when removing attached Powah blocks.

> As mentioned multiple times on this Discord after numerous reports of the issues with the Energy Meter in combination with Energizing Rods by Powah, there is now a mod that fixes that behavior. It forces Powah and AE2 to invalidate their capabilities which will fix a lot of cross mod interactions. I tested it locally and it seems to fix all the Energy Meter issues that arised in the past as well. So you may want to take a look at it and add it to E9E because a lot of the progression seems to rely on the energy transfer through the EM: [mod link]

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion 👍 AECapFix is already added in-dev, I expect it to go out in v1.4.0 :)
