### ISSUE TITLE
Server completley refuses to start

### ISSUE THREAD

**Issue by kristupas098** [EnigmaticaModpacks/Enigmatica9#709]
### Modpack Version

Enigmatica9ExpertServer-1.13.0 

### Describe your issue.

enviroment:
ubuntu 20.04 aarch64 java 20
windows 11 x86-64 java 20

server file link: **https://www.curseforge.com/minecraft/modpacks/enigmatica9expert/files/4745568** and https://www.curseforge.com/minecraft/modpacks/enigmatica9expert/files/4745569

server completley refuses to start

### Crash Report

https://gist.github.com/kristupas098/83df494a5acb106efd246b7019b611d7

### Latest Log

https://gist.github.com/kristupas098/83df494a5acb106efd246b7019b611d7

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
You need java 17
