### ISSUE TITLE
Suggestion: Botania

### ISSUE THREAD

**Issue by chaoaretasty** [EnigmaticaModpacks/Enigmatica9#710]
### URL

https://www.curseforge.com/minecraft/mc-mods/botania

### Why would you like the mod added?

Botania has been a long standing part of the Enigmatica packs and its absence is notable. While there are several magic packs in already there's always been a unique feel to Botania which I'd love to bring into our current world.

**Comment by MuteTiefling** [comment]
We wanted to step away from Botania this time for a variety of reasons. Its exclusion is intentional.

**Comment by chaoaretasty** [comment]
I'd be interested in knowing more about the reasons if you have the time (not to argue against or debate btw, just to get a better understanding of the direction and thinking of the team)
