### ISSUE TITLE
[E9E] Suggestion: Increase capacity of Immersive Engineering Silo and Tank multiblock storage structures

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica9#712]
### Describe your suggestion

 Increase capacity of IE water Tank (and Silos). They are both only at default values meaning the Tank can only hold 512 buckets worth of fluid which is almost nothing in modded terms, especially with how large the structure is and the amount of copper required to build it. 

Silos are less useful but could use a buff as well.

### Why would you like this added/changed?

Single block solutions (/Drawers/Fluid Drawers, Fluid Cells, Various tanks from Thermal/PNC) far outstrip the expensive multiblock storage solutions provided by IE. Increasing their capacity can bring them more in line with other far cheaper, and smaller, options.

**Comment by NielsPilgaard** [comment]
I don't see why not, seems like a good change :)

**Comment by MuteTiefling** [comment]
Much to my dismay, I seem to be unable to find a way to increase this? I'm not seeing it in the IE server config at all.

**Comment by NielsPilgaard** [comment]
Damn me neither :/ not much we can do then.
