### ISSUE TITLE
Portable Energy Interface doesn't have a crafting recipe

### ISSUE THREAD

**Issue by wortelus** [EnigmaticaModpacks/Enigmatica9#713]
### Modpack Version

1.13.0

### Describe your issue.

Portable Energy Interface from Create: Crafts & Additions doesn't have a crafting recipe in E9. Note that the other contraption interfaces for items and fluid does indeed have correct recipes.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

wortelus

**Comment by MuteTiefling** [comment]
Thanks for the report! That'll be fixed next update.
