### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by RKuijsters** [EnigmaticaModpacks/Enigmatica9#716]
### Modpack Version

1.14

### Describe your issue.

Whenever I try to connect to the server i get the "timed out" message so do friends that connect. The 1.13 version of the pack works fine and other packs do too. I have java 17 installed. 

### Latest Log

https://gist.github.com/RKuijsters/39efbbf07a297487dc8bea1425029855

### Have you modified the modpack?

No

### User Modifications

I did a clean install of the client and the server and got the logs 0 changes

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

kyousuke019

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll look into this ASAP. 
Could you please provide a client latest log as well?

**Comment by RKuijsters** [comment]
Cliënt logs are line 1 - 4650  after that are the server logs

**Comment by RKuijsters** [comment]
Any chance you can share what the issue was iam very curious 🧐

**Comment by NielsPilgaard** [comment]
I believe it was this: https://github.com/VazkiiMods/Quark/issues/4370
