### ISSUE TITLE
[E9E] AE2 - Crystal Growth Accelerator Information outdated

### ISSUE THREAD

**Issue by ba77osai** [EnigmaticaModpacks/Enigmatica9#717]
### Modpack Version

1.13.0

### Describe your issue.

In the provided AE2 Book the entry for the Crystal Growth Accelerator is outdated. It tells you about using it with water to grow seeds faster but currently you just need to place it next to a budding block to accelerate the growth.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/8996622/52784c83-d4b0-4473-b72d-c71e6cd742d7)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

ba77osai

**Comment by MuteTiefling** [comment]
Thanks for the report, I've relayed the info!

**Comment by MuteTiefling** [comment]
Apparently this wasn't meant to be available at all in 1.19 and won't be fixed.
