### ISSUE TITLE
[E9E] NPE crash on save load

### ISSUE THREAD

**Issue by Tepa00** [EnigmaticaModpacks/Enigmatica9#718]
### Modpack Version

1.14.1

### Describe your issue.

Updated from 1.12.1, on start it crashes when loading the save.
NullPointerException on a ae2 matter condenser that has a Create funnel dumping garbage into it and extracting matter balls to a chest.
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/8587616/1863149b-67c8-4bca-8607-f8eedf6ae72a)

Removing AECapFix from the server allows the save to load, and removing it from the client allows the client to join.

### Crash Report

https://gist.github.com/Tepa00/234a5130f39979870f263cf657c3912f

### Latest Log

https://gist.github.com/Tepa00/971666180c97354802f5725cedef4954

### Have you modified the modpack?

Yes

### User Modifications

Deleted emojiful because it breaks text rendering in many places, such as every single mods guide book.
Removed aura drain from eu because aura went negative and generation over a large area started eating into server TPS.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report, we'll get that resolved ASAP 😊

**Comment by 62832** [comment]
Sorry about that. I've just now released a patch for AECapFix to prevent this from happening again.

**Comment by NielsPilgaard** [comment]
No worries, we'll try again in the next release 😄
