### ISSUE TITLE
[E9E] Unable to craft Focus of Necromancy

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica9#719]
### Modpack Version

1.13

### Describe your issue.

Unable to create Necromantic Focus from Ars Nouveau.

All items are correct, gold dust is laid down but when the withered sapling grows it does nothing.

![Necro focus-1](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/7070416/a0043ea4-c89a-4220-899e-de44851b1b94)
![Necro focus-2](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/7070416/577a1078-3804-4b9a-bf94-3b501424f17a)
![Necro-focus-3](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/7070416/268f3f10-68ec-496c-a013-3ef50786b582)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Tank!#8912

**Comment by MuteTiefling** [comment]
Apparently it doesn't like BYG trees at all. It'll use purple archwood now.
