### ISSUE TITLE
Shut-Up experimental settings not working while creating new world.

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#72]
### Modpack Version

1.0.2 Dev

### Describe your issue.

Shut-Up experimental settings just... doesn't work. While creating new world you still get the warning about world using experimnetal settings ^^"

![obraz](https://user-images.githubusercontent.com/60540476/195549091-b1e39b4d-7442-49a3-bde7-69d9f0767c12.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Kanzaji#0621

**Comment by NielsPilgaard** [comment]
https://github.com/CorgiTaco/ShutupExperimentalSettings/issues/16

**Comment by jerkery678** [comment]
![image](https://user-images.githubusercontent.com/115450509/222696191-e5c13d15-3b42-4d5a-8d00-90645daea8d0.png)

Use Yeetus Experimentus instead I guess

**Comment by Kanzaji** [comment]
We already did that long time ago 😅
