### ISSUE TITLE
Budding Therium Crystal and Amethyst Golems

### ISSUE THREAD

**Issue by bartu26** [EnigmaticaModpacks/Enigmatica9#720]
### Modpack Version

1.13.0

### Describe your issue.

The Ars Nouveau Amethyst Golems dont want to harvest the Budding Therium Crystals. I allowed the Fake Player via FTB Server to allow them to break the Clusters. The Golems can hower pickup the Shards and deposit them when I manually mine the Clusters.

The Budding Subzero Crystals, the Budding Certuz Quartz and the Budding Amethyst work as intended.

![grafik](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/49201294/e2e4a769-0e15-446f-bca3-96e4c35b35d8)

One thing I noticed are some inconsistencies at the Item Tags regarding the Budding Therium Crystals, not sure if this is causing the issue.

![2023-10-12_16 52 32](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/49201294/3ccc2c0d-41c3-4846-a6ef-a6650a856d59)

![2023-10-12_16 52 38](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/49201294/5e0e0c49-6422-4256-937f-4f4d0ad636eb)

![2023-10-12_16 52 42](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/49201294/b044f177-fc51-4262-956e-83c00117b9d6)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
The important tag for breaking is on the cluster itself: 

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/a5fe8f6e-edd6-40b5-a71c-99d6e464def8)

The tags are still present in 1.14 and the clusters are being broken properly in my test world. I suspect a bad install is to blame here.
