### ISSUE TITLE
Applied Energistics 2 meteorites

### ISSUE THREAD

**Issue by Ved-s** [EnigmaticaModpacks/Enigmatica9#722]
### Modpack Version

1.14.2

### Describe your issue.

Applied Energistics 2 generates meteorites in Overworld, which contain disabled processor presses
![](https://cdn.discordapp.com/attachments/1138181433928724635/1162368402829094912/image.png?ex=653baeee&is=652939ee&hm=15b2d33bbf0bb5f30f721ec8ace29063c8191dd060b716d2e649924e845a9218&)
![](https://cdn.discordapp.com/attachments/1138181433928724635/1162368652402765834/image.png?ex=653baf2a&is=65293a2a&hm=22c6260e87aa04355b5fd90811ce2c9799d8938047b6d499c9518441729d9f4e&)

### Have you modified the modpack?

Yes

### User Modifications

Added visual client mods, Ears and Build Guide

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ved_s

**Comment by Ved-s** [comment]
@MuteTiefling was this the case on version 1.12? I started on that version and they could be queued to generate on that.

**Comment by MuteTiefling** [comment]
They've been disabled since forever. Like before play testing and long before release.

**Comment by MuteTiefling** [comment]
Looks like it was switched from a config to a biome tag at some point. They'll be gone for real next update.
