### ISSUE TITLE
Falling out of the sky when flight effect refreshes

### ISSUE THREAD

**Issue by dizzystem** [EnigmaticaModpacks/Enigmatica9#726]
### Modpack Version

1.14.2

### Describe your issue.

I was previously playing on version 1.13.0. Since the server I'm playing on updated to 1.14.2 today, I've been falling out of the sky every 30 seconds or so. From watching my effect timer, it happens when the Ars Noveau ritual of flight refreshes my flight effect to 59 seconds - my guess is that when it does that it's removing flight for an instant before adding it again, which makes me fall.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Tetrikitty#2647

**Comment by MuteTiefling** [comment]
Seems that ars nouveau has a fixed version for this. You ought to be able to update manually to fix it. Or we'll update it in our next update.
