### ISSUE TITLE
E9E Soul engulfing structure

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica9#727]
### Modpack Version

E9E - 1.14.2

### Describe your issue.

When looking up the recipe for the soul engulfing structure you can no longer mouse over the picture in JEI and see what items/blocks should be used to make the structure. Worked in previous version of the modpack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by calog3no** [comment]
I did notice if you find the needed blocks in JEI and click for use JEI will show the structure as one uses for the blocks.

**Comment by NielsPilgaard** [comment]
Thanks for the report, the EMI dev is working on fixing this :)

**Comment by theboo** [comment]
Should be fixed in latest EMI version, can wait for an e9e update ior update EMI yourself
