### ISSUE TITLE
Redstone and glowstone not craftable using spout

### ISSUE THREAD

**Issue by digerbop** [EnigmaticaModpacks/Enigmatica9#728]
### Modpack Version

1.14.2 (expert) 

### Describe your issue.

Cannot craft glowstone using nightvision potion in a create spout with cinderflower on a depot underneath. Equally Redstone won't craft using this set up with a strength potion in the spout. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Be sure you've got create potion fluid. You can either craft it with create or drain a potion bottle with the create fluid drain.
