### ISSUE TITLE
Items sometimes deleted when middle clicking sophisiticated storage chest that has slot memory

### ISSUE THREAD

**Issue by zifnab06** [EnigmaticaModpacks/Enigmatica9#729]
### Modpack Version

1,.14.2

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/283805/a4f32c4a-c8ea-4c55-bd26-fca8e032de4b)

This chest has deleted items 3 times so far. I'm not able to reproduce consistently.  

Repro steps (when this does happen): 
- Set most slots in the chest to have slot memory
- Fill in the rest of the chest with random items
- Middle click inside the chest window to sort the chest

Occasionally the items in the slot memory spaces get moved. If there's not enough space in the chest to fit all items outside of slot memory, items that no longer fit in the chest get deleted. (I lack a log right now, I'll upload one next time this happens)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

zifnab06

**Comment by MuteTiefling** [comment]
Sounds like we need to blacklist the middle click sort. These things hand their own sort that should work better anyway.
