### ISSUE TITLE
Player that have OP permissions on the server are being kicked from the server.

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#73]
### Modpack Version

1.0.2

### Describe your issue.

Players that are OP on the server are being kicked from it with this error:
![obraz](https://user-images.githubusercontent.com/60540476/195549690-14e43bf0-a989-46de-a879-99d7a532341a.png)
With no way to join server back, until they are de-op'd ^^"

This report is here for people to know this is actually known bug, and there is no fix for it *yet*.

### Latest Log

[debug.log](https://github.com/EnigmaticaModpacks/Enigmatica9/files/9774717/debug.log)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Kanzaji#0621

**Comment by Nellana2** [comment]
I'm running into this same error. I'm able to join the server just fine, until I op myself, and I'm unable to rejoin.

**Comment by brads900** [comment]
having the same issue also

**Comment by Darkere** [comment]
https://github.com/Quarris/EnigmaticGraves/issues/46

**Comment by Quezler** [comment]
fixed upstream ^
