### ISSUE TITLE
Amethyst can get duped or reduced with compacting drawers

### ISSUE THREAD

**Issue by KaiAndreas1** [EnigmaticaModpacks/Enigmatica9#731]
### Modpack Version

1.14.2

### Describe your issue.

When using the Functional Storage compacting drawer with amethyst shards it uses 9 to make each block instead of 4.

This either reduces how much you have by pulling it out in block form or allows for a dupe by crafting the amethyst into blocks and then putting them in the compacting drawer and getting 9 shards back from each block put in

Steps to reproduce Item deletion:
1. place 9 shards in the compacting drawer
2. remove 1 block, there will now be less amethyst then you started with

 Steps to reproduce dupe:
1, Place amethyst blocks in compacting drawer
2. Remove all amethyst shards from drawer
3, Craft all shards back into block
4, Repeat ad infinitum

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Kaiandreas

**Comment by KaiAndreas1** [comment]
After a little further testing on other 2x2 combinations in the drawer:


**does not combine to storage block in drawer:**
Therium 
Subzero shards
Honey Crystal

Honeycomb does not combine into a block if you put the honey comb into it, you have to start by placing the block into it for the conversion to work as intended

I tested a few other vanilla and Ae2 2x2 storage blocks but found no other dupable conversions

**Comment by Kanzaji** [comment]
https://github.com/Buuz135/FunctionalStorage/pull/235
