### ISSUE TITLE
[E9E] Mod emi breaks visibility of biom list from industrial forgoing

### ISSUE THREAD

**Issue by Kenshij** [EnigmaticaModpacks/Enigmatica9#734]
### Modpack Version

1.14.2

### Describe your issue.

The mod emi breaks the visibility in jei of the biom list from usage of item laser base (fluid and ore) from industrial forgoing.
Tested with removing all mods except jei, emi and industrial-forgoing.
Reported to mod author https://github.com/emilyploszaj/emi/issues/330

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kenshij

**Comment by theboo** [comment]
Should be fixed in EMI's latest update. Can wait for an e9e update or update EMI yourself to fix
