### ISSUE TITLE
Could not open unix_args.txt

### ISSUE THREAD

**Issue by Boyownik** [EnigmaticaModpacks/Enigmatica9#741]
### Modpack Version

1.15.1 & 1.15.0

### Describe your issue.

When I use start-server.sh script on my Ubuntu server i get error like this:
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/27145369/22510234-5b9e-4cfe-9434-1cb629c0b9ad)
It says it cannot open unix_args.txt

I have checked and updated default java version on Ubuntu between 17-18 and it is still giving me same error.
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/27145369/1525db5a-7331-4f6b-9b3d-e773e0e6db42)

Tried few reinstalls of modpack.
Tried on 15.0.0 & 1.15.1 version of modpack

Edit: In addition, All The Mods 8 which is on 1.19.2 aswell is working fine for me on same machine

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report, we'll investigate the issue.

@badegg365 do you have any ideas as to what could be causing this? Seems like the Unix args file isn't generated 🤔

**Comment by NielsPilgaard** [comment]
Most likely a silly question, but you didn't run the start script on a Windows machine and then move the files over right?

**Comment by Boyownik** [comment]
> Most likely a silly question, but you didn't run the start script on a Windows machine and then move the files over right?

No i didn't. I straight downloaded server files from curseforge using wget, unzipped and installed on my VPS

**Comment by NielsPilgaard** [comment]
I cannot reproduce this issue using Linux Mint - I don't have an Ubuntu server to test on unfortunately. 

Is Forge installed? What does the contents of the `libraries` folder look like?

**Comment by Boyownik** [comment]
> I cannot reproduce this issue using Linux Mint - I don't have an Ubuntu server to test on unfortunately.
> 
> Is Forge installed? What does the contents of the `libraries` folder look like?

Funny enough it appears that forge failed to install which i didn't notice lol. I have reinstalled and the start script is giving me this output: 
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/27145369/aa821f9c-6824-46d6-919e-ee040daa8fb0)

The only solution for now that people with similar issue on web is to make sure to use proper java which I do - see screenshots above. I have even added path to java in server config.

**Comment by Boyownik** [comment]
Okay after deinstalling every Java that I had on my VPS and installing open jdk 19 it seems that it is finally working. Despite setting default java version as seen on screen in main topic it must have still using the wrong one. Linux won't stop surprising me apperantly xd

I think you may close this issue. Thanks a lot for help :D

**Comment by NielsPilgaard** [comment]
Sure thing, glad it works 👍
