### ISSUE TITLE
Found disabled items in create dungeon

### ISSUE THREAD

**Issue by sabeto38** [EnigmaticaModpacks/Enigmatica9#744]
### Modpack Version

1.14.2

### Describe your issue.

I found Andesite Alloy (Emendatus Enigmatica) and crushed raw copper (create mod) inside the loot chests of some create structure.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

sabeto.

**Comment by NielsPilgaard** [comment]
Thanks for the report :) Do you remember which structure?

@Kanzaji Do you recall if this is one of the unification things we cannot fix?

**Comment by sabeto38** [comment]
The structure is called "Tinker's Workshop", according to this screenshot from the curseforge page of [Integrated Dungeons and Structures](https://www.curseforge.com/minecraft/mc-mods/idas)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/148582510/ea70a1a9-dfc8-486b-a1f0-49caf6fd6625)

**Comment by Kanzaji** [comment]
> Thanks for the report :) Do you remember which structure?
> 
> @Kanzaji Do you recall if this is one of the unification things we cannot fix?

It might 😅 However looking at the fact EE Ingot was found there... it's probably my Unification script that got outdated because of Create changing Ids.. I will look into it.

**Comment by Kanzaji** [comment]
Unless you found Create crushed ore in here >.> This is something we can't fix (at least, without modifying the structure itself) 😓
![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/67c11f9c-1ef7-4fda-a7ab-7a878c6ca144)

**Comment by Kanzaji** [comment]
Okay final update on the issue (I hope 😄):
- Unification script is up-to-date, so I'm guessing Crushed Raw Ore from Create was found in the place showed in previous message.
- EE Andesite Alloy is disabled only in Expert, and I found that it's not removed / replaced from Loot, so that will get fixed up soon :D
- Not sure if we should spend time replacing all the items in Structures that we can't unify automatically >.> I guess we could replace all the structures with our overrides that have items unified, but the question is, is it worth it?

**Comment by NielsPilgaard** [comment]
> Not sure if we should spend time replacing all the items in Structures that we can't unify automatically >.> I guess we could replace all the structures with our overrides that have items unified, but the question is, is it worth it?

I don't think it's worth it no :/

**Comment by sabeto38** [comment]
> Unless you found Create crushed ore in here >.> This is something we can't fix (at least, without modifying the structure itself) 😓

would be very much possible, that i found the crushed ore on the item shelves, that would explain the low amount i had, but i didnt really pay attention at the moment, i just discovered the "disabled" tooltip afterwards, while going through the loot.
