### ISSUE TITLE
Water Wheel quest description out of date

### ISSUE THREAD

**Issue by ct-klein** [EnigmaticaModpacks/Enigmatica9#760]
### Modpack Version

1.15.1

### Describe your issue.

The text of the water wheel quest is out of date with an update to the Create mod.
You can no longer apply water to all 5 sides of the wheel to increase the stress units.
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/8160400/27a72243-9413-4fb1-b548-6159ad3363ad)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Irongron#9144

**Comment by MuteTiefling** [comment]
Thanks for the report! That'll be fixed next update
