### ISSUE TITLE
Player and mobs invisible after creating a new world.

### ISSUE THREAD

**Issue by MagnusHellfire** [EnigmaticaModpacks/Enigmatica9#765]
### Modpack Version

E9E 1.15.1

### Describe your issue.

 similar issue in closed bug report here > invisible player and mobs #551 
 If you open mod options at any point before creating a world all entities will be invisible, creating another new world doesn't resolve the issue. 
 
 Bug is seemingly caused by an incompatibility between Alex's Mobs and Catalogue, rather than configured which was removed per bug report #551

### Latest Log

https://gist.github.com/MagnusHellfire/33f60b97ce222416eee42751615265fb

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
We don't have alex' mobs though? Must be an incompatibility with something else?

**Comment by MagnusHellfire** [comment]
> We don't have alex' mobs though? Must be an incompatibility with something else?

...yep, mixing up modpacks. Not sure what it would be incompatible with in this case then.

**Comment by NielsPilgaard** [comment]
Seems like it can happen if a mod is missing some configuration that Catalogue is expecting. I think our best bet is to just remove Catalogue to be honest.

**Comment by theboo** [comment]
I think we forgot to remove this

**Comment by NielsPilgaard** [comment]
Oh boy, that I did :P I've removed it from my dev instance now, so it'll be removed next release.
