### ISSUE TITLE
Change Create's Industrial Iron Recipe

### ISSUE THREAD

**Issue by Flounder-M** [EnigmaticaModpacks/Enigmatica9#766]
### Describe your suggestion

Industrial Iron is a decorative block from Create that interacts with Chutes and is made by Stonecutting an Iron ingot. As far as I can tell making it is a one-way street. Currently you need iron ingots to make it, I suggest changing this to use Black Sheetmetal to keep it consistent with the chute recipe.

### Why would you like this added/changed?

To make this decorative item available at the same time the item it is meant to decorate becomes available, and to assist in decorating earlier.

**Comment by MuteTiefling** [comment]
Sounds good. New recipe will be like this: 

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/931b395e-a521-4465-bcef-14186e8bb36f)

**Comment by Flounder-M** [comment]
That's great! Thank you for your work 😄 Appreciate all you and the team do.
