### ISSUE TITLE
Conflicting recipes for Crushed Ores in a Centrifugal Separator

### ISSUE THREAD

**Issue by SilverRuin** [EnigmaticaModpacks/Enigmatica9#767]
### Modpack Version

1.15.1

### Describe your issue.

Most crushed ores have two conflicting recipes when places into a Centrifugal Separator. The recipes generally are either:

10k RF cost with an output of 9 base ore nuggets and a chance of additional base ore nuggets and/or other ore nuggets) recipe
1.6k RF cost with an output of 9 base ore nuggets and a chance for other ore nuggets/other material/nothing

The game doesn't seem to choose either recipe consistently. Copper ore uses the 10k cost recipe, and aluminum ore uses the 1.6k cost recipe. There's probably some balance considerations needed for some of the ore recipes as some recipes are roughly equivalent and for others, one option is superior to the other.

Ores I observed this issue for: Tin, Zinc, Silver, Uranium, Aluminum, Gold, Copper, Nickel, Lead, Iron.

![separator](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/88354170/cef6270a-4dc4-48b2-aa1d-e86aa4a1f159)

### Crash Report

None

### Latest Log

None

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

silverruin (SilverRuin)

**Comment by Kanzaji** [comment]
Thanks for the report! We will investigate this issue.
