### ISSUE TITLE
Incorrect Basic Spell Turret Quest Description

### ISSUE THREAD

**Issue by Tlotro** [EnigmaticaModpacks/Enigmatica9#770]
### Modpack Version

1.15.1

### Describe your issue.

Contrary to the quest description, supplying the lingering absorber with melded potions does not increase the output. The only parameters that matter are time and power, both probably averaged, since melded potions have been performing worse than standart potions of the same maximum duration.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. that'll be fixed next update
