### ISSUE TITLE
[Mod Suggestion] Ender storage

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#78]
### URL

https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8/files/all

### Why would you like the mod added?

Ender storage is another classic in modded minecraft, allowing for item/fluid wireless multi-dim transport :D
PS: I know there is Quantum Entangloporter from Mekanism, so this could need a bit of a discussion ^^"

**Comment by MuteTiefling** [comment]
I really feel this is a mod that needs to be given a break.

Nature's Aura has ender caches that work very similarly, but require aura.

Entangloporters exist, as mentioned.

Ae2 has wireless capabilities.

Ars nouveau can be used for long range transport in more creative ways.

PNC has some interesting methods for it as well.
