### ISSUE TITLE
Translation in Crowin?

### ISSUE THREAD

**Issue by IceDragonFla** [EnigmaticaModpacks/Enigmatica9#784]
### Describe your suggestion

As a Chinese Minecraft player, I really love the tech modpack especially Enigmatica series, but it's hard for other guys playing with to read English, so if it's available for you to upload the quest book's lang file on Crowin (which is quite nice for someone love translating (like me) to translate it and try to spread this modpack)

### Why would you like this added/changed?

translate the questbook on [this website](https://crowdin.com/)

**Comment by NielsPilgaard** [comment]
Hi there 😊 thank you for the suggestion!
We think this would be a great change as well, but we simply don't have the time to add or maintain it I'm afraid, it reduces development speed.

**Comment by IceDragonFla** [comment]
Really appreciate that you can reply my suggestion, cause I am not a native English speaker. May not express my opinion clearly. 
Actually I am a translation contributor, I really want to help you translate this modpack =w=

**Comment by NielsPilgaard** [comment]
I understand that you want to help, but just making quests possible to translate takes a great deal of time, and slows down development. Sorry.

**Comment by IceDragonFla** [comment]
Thank you so much for replying me such a stupid issue, hope enigmatica series goes better in the future, appreciate again for you guys!
