### ISSUE TITLE
Add a recipe to retrieve books from bookshelves without manually mining them

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica9#790]
### Describe your suggestion

I got a bunch of bookshelves with silk touch but would like to get the books out of them without placing them down and mining them again. Possible suggestions:
Saw
Cutting board
Crush recipe
Various crushers

### Why would you like this added/changed?

It beats placing down several stacks of bookshelves and mining them.

**Comment by MuteTiefling** [comment]
Thanks for the suggestion! That'll be in next update
