### ISSUE TITLE
Occultism mobs can't get milked by a Drymy as expected

### ISSUE THREAD

**Issue by JonasDoe** [EnigmaticaModpacks/Enigmatica9#793]
### Modpack Version

15.1 - but the 1.16.0 doesn't seem to address this issue either.

### Describe your issue.

- A Drymy won't pull loot from mobs like Ghast, Blaze, Infested Endermite, summed by Occultism. Neither put in a Seat (tested with the Endermite) nor in a Containment Jar (tested with all three of them) will work.
- A Skeleton from the Wild Hunt won't produce Wither Skulls etc. when put in a seat. Might be intended to keep things balanced, though. I forgot to test how it behaves in a Containment Jar.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report. They're intentionally blacklisted, however.

**Comment by JonasDoe** [comment]
I see! Strikes me as a bit odd though, since none of these is harder to capture in the non-occultism version (or regardiing the Endermite to get Endstone another way), and it's some unexpected behavior. Is it really worth that undocumented suprise? (With the Wither Skeleton being a notable exception ofc.)
