### ISSUE TITLE
Add Spirit

### ISSUE THREAD

**Issue by CodexAdrian** [EnigmaticaModpacks/Enigmatica9#8]
### URL

https://www.curseforge.com/minecraft/mc-mods/spirit

### Why would you like the mod added?

Spirit is a soul based magic mod, built upon the soul magic added in the nether update for Minecraft. It adds highly configurable content, with soul based spawners, tools and crafting recipes. You can level up soul crystals and use them in spawners to get better, more effective mob spawners. It also adds Soul Steel tools. When empowered, these tools can use the souls in a soul crystal to perform effects, like make mobs explode on a sword swing or create a potion cloud when a soul is shot from a bow. I think it would be a fun addition to add to Enigmatica 9, tinkers construct compat is planned in the near future.

**Comment by MuteTiefling** [comment]
This is one that looks pretty interesting. Definitely worth a look.

**Comment by CodexAdrian** [comment]
Hey guys, I actually just released a mod that works hand in hand with Spirit. It's a tech mod that has a similar concept to woot, using the spirit soul crystal as a way to hold data for simulating mob drops. I think it'd make a good fit here.

https://www.curseforge.com/minecraft/mc-mods/vitalize

**Comment by NielsPilgaard** [comment]
I don't like the concept tbh 😅 thanks for the suggestion anyway.
