### ISSUE TITLE
[Mod Suggestion] Cooking for blockheads

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#80]
### URL

https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads

### Why would you like the mod added?

Cooking for blockheads adds a lot of food-related stuff, allowing to literally cook in minecraft :D
*Completely not used by half of the people just to have infinite water source from a sink*

**Comment by MuteTiefling** [comment]
The sink aside, this one really makes the least sense of all the possible food mods. Most of its features go unused without Pam's. I'd rather skip it.
