### ISSUE TITLE
Belt of Unstable Gifts changes

### ISSUE THREAD

**Issue by kobuld** [EnigmaticaModpacks/Enigmatica9#801]
### Describe your suggestion

Edit the list of potion effects that the belt will apply to ones that do not cause headaches
namely. removing night vision, speed, and other spell effects that could interfere with or annoy the player.

Balance changes could be to give the belt a cooldown between effects, and increase the duration of potions. Constantly reapplying new effects could potentially cause server lag.

### Why would you like this added/changed?

As it is right now. The belt is completely unbearable to use given the frequency and type of potion effects it applies

It will apply random 3-5-second duration potion effects constantly. This can be incredibly frustrating to use, given that potion effects can alter the camera, speed, or how the world looks to the player.

an example:
it will apply speed 2, causing the players' camera to zoom in and give them an unexpected speed boost which could throw them off course. a few seconds later it would apply night vision, The camera would zoom back out and the world would start flashing, as night vision does when it is about to run out.

as long as the belt is worn. this will reoccur constantly and can be headache-inducing.

**Comment by MuteTiefling** [comment]
I believe all the visual effects are removed with this PR. Now you'll mostly just randomly get extra healing or damage reduction. Free Saturation on occasion will also likely mean you won't need to eat much while wearing this outside of combat.
