### ISSUE TITLE
Ars containment Jars + Industrial foregoing lasers for safer farming above Wither/Chimera

### ISSUE THREAD

**Issue by migmolrod** [EnigmaticaModpacks/Enigmatica9#802]
### Describe your suggestion

At some point in the modpack, one needs to use a Fluid Laser Base above a Wilden Chimera to get Magicite and above a Wither to get another fluid (I don't know what exactly now).

I remember to be able to do it in Enigmatica 6 Expert with the Wither to farm whatever it was needed with it back then (ether gas was it?). In a less safe way, with a wither-proof slab between the laser base and the Wither itself.

But here, Wilden Chimera seem to be a little bit more hostile in terms of block griefing. And even with the protection from FTB Chunks, it manages to destroy some blocks. It could even destroy some panzer glass slabs in the ceiling (I have a tower with multiple occultism pentacles in each floor and tried to protect the pentable above)
So now I'm quite scared of putting a laser machine above the wilden chimera and risk it.

Then I thought "maybe I can use a containment ritual to have a Wilden Chimera inside a jar and maybe the laser still works with the jar right below it". So I tried it but had no luck. Still think it could be a nice addition.

Would you be able at all to have those bosses inside containment jars working below the laser base? Some entities inside those jars just behave as if they weren't in a jar (for example, you can milk contained cows and trade with contained villagers).

Or do I need to talk with Ars and/or Industrial foregoing creators so they make it possible to do this?

### Why would you like this added/changed?

Wilden Chimeras apparently are able to destroy wither proof slabs inside chunks protected by FTB Chunks so it would be nice to have a safer way to put them below fluid laser bases

**Comment by MuteTiefling** [comment]
Thank you for the suggestion. To contain these, you already have a powerful option, however; the stasis chamber. 

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/f891f20d-28fd-4632-be98-bde03e2163c3)

It's impossible to make them work on a block containing a mob (containment jar). They simply aren't meant to work that way. The closest we could do would be to create special lenses like we did with the ender dragon, but the intent is that you'd use a stasis chamber to contain them.
