### ISSUE TITLE
 "When using spells from the Ars Nouveau mod to induce the growth of plants belonging to the hexerei, a deadlock occurs due to the use of the 'harvester' from the Create mod."

### ISSUE THREAD

**Issue by cy-aqua** [EnigmaticaModpacks/Enigmatica9#804]
### Modpack Version

1.15.1

### Describe your issue.

User
Crashed while entering the world, presumably due to hexerei's recipe, create's Reaper began to shake while growing using spells in the game, and soon after the game crashed and is no longer able to enter the world. The error report is as follows, I am not very able to read these, hope to solve this problem

### Crash Report

https://gist.github.com/cy-aqua/cab32eae28f98c952b586e97e3a2240d#file-crash-2023-12-10_01-14-29-server-txt

### Latest Log

https://gist.github.com/cy-aqua/d41bd1164d80e617cfffeb99a80d157d

### Have you modified the modpack?

Yes

### User Modifications

[键位冲突显示] Controlling-forge-1.19.2-10.0+7.jar
[铷] rubidium-mc1.19.2-0.6.2c.jar
[实体渲染机制优化] entityculling-forge-1.6.1-mc1.19.2.jar
[是，史蒂夫模型] yesstevemodel-1.19.2-release-1.1.5-hotfix-2.jar
[通用拼音搜索] jecharacters-1.19.2-4.4.2.jar
[现代化 UI] ModernUI-Forge-1.19.2-3.9.0.2-universal.jar.disabled
[现代化修复] modernfix-forge-5.7.2+mc1.19.2.jar
[星光] starlight-1.1.1+forge.cf5b10b.jar
[玉 ] Jade-1.19.1-forge-8.9.0.jar
[越肩视角重制] ShoulderSurfing-Forge-1.19.2-2.8.1.jar
[自定义局域网联机] lanserverproperties-1.9.1-forge.jar
[自动汉化更新] I18nUpdateMod-3.5.2-all

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MuteTiefling** [comment]
You ought to be able to recover your world by enabling the `removeErroringEntities` in the forge server configs

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/a62ac338-638b-412a-83bc-4c4072c37ef2)

You've added a lot of mods there, however, so I'm not sure what more we can offer by way of support.
