### ISSUE TITLE
Gravel washing

### ISSUE THREAD

**Issue by Ckyfreak** [EnigmaticaModpacks/Enigmatica9#807]
### Modpack Version

1.16.1

### Describe your issue.

Gravel washing with create doesn't seem to work. Not sure if it has been removed or just not working.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Ckyfreak24

**Comment by MuteTiefling** [comment]
Thanks for the report. It's intentionally removed as it promotes gameplay that frequently leads severe lag.
