### ISSUE TITLE
[Mod Suggestion] Simply light!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#81]
### URL

https://www.curseforge.com/minecraft/mc-mods/simply-light/files

### Why would you like the mod added?

This mod adds some simple lights :D Another decorative mod that was used before, so waiting for opinions if we keep it or we skip it.

**Comment by NielsPilgaard** [comment]
I'm not sure to be honest, I have no idea whether it's used or not :P

**Comment by atlgeek007** [comment]
I use simply lights whenever it's available, because there are lighting options not available elsewhere.
