### ISSUE TITLE
Starbuncle duplicates latex

### ISSUE THREAD

**Issue by aqpoyo** [EnigmaticaModpacks/Enigmatica9#812]
### Modpack Version

E9E 1.16.1

### Describe your issue.

If a starbuncle equipped with a starbucket is told to move liquid from Thermopneumatic Processing plant to a small fluid tank it will dup the liquid, in this case It is latex.
I was trying to move out the water when you make rubber from latex but it took out the latex and filled the tank.
I don't know if it matter but another starbuncle was taking the latex from an arboreal extractor to the tpc. (This starbuncle was waiting to have more latex available, while the other was dupping the latex into the fluid tank)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

aqpoyo

**Comment by MuteTiefling** [comment]
Fixed with Starbuncle Mania update https://github.com/EnigmaticaModpacks/Enigmatica9/blob/d46519340c2702edf34a856a86343ce531a243a2/changelogs/changelog_mods_1.18.0.md?plain=1#L20
