### ISSUE TITLE
Plastic (Industrial Forgoing) Disabled

### ISSUE THREAD

**Issue by benjamin-antupit** [EnigmaticaModpacks/Enigmatica9#814]
### Modpack Version

1.16.1

### Describe your issue.

Plastic (as part of Industrial Forgoing) is disabled and there's no way to obtain it. It is a core ingredient for many parts of the mod. Could a recipe for Industrial Forgoing plastic be added, or could it be unified with another mod's plastic?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

benjamin.antupit

**Comment by Kanzaji** [comment]
Thanks for the report!

Industrial Foregoing Plastic is indeed disabled on purpose in Expert mode, however it should be left untouched in Normal version of Enigmatica 9. 

From what I remember from talk in Discord, you are playing Normal version 😅However, I'm unable to reproduce this on 1.16.1 E9 Normal mode >.>

**Comment by MuteTiefling** [comment]
Closing these out as I cannot reproduce and they appear to be due to a bad install.
