### ISSUE TITLE
You need overworld oak for the functional storage mod

### ISSUE THREAD

**Issue by Sylvanus334** [EnigmaticaModpacks/Enigmatica9#815]
### Modpack Version

1.16.1

### Describe your issue.

You need overworld oak for the functional storage mod, i.e. drawers. The only way to get it currently is from the cloud islands with a giant pickaxe.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
The market is also available early game and sells all saplings
