### ISSUE TITLE
Making an Enchanter's Crossbow wipes the crossbow's NBT data (Ars Nouveau is outdated)

### ISSUE THREAD

**Issue by muzak23** [EnigmaticaModpacks/Enigmatica9#820]
### Modpack Version

1.16.1

### Describe your issue.

If you try to make an enchanted/gemmed crossbow into an Enchanter's Crossbow, the NBT data will be wiped and you will only get a plain EC. I lost a god bow :(

Ars Nouveau patched this bug (along with a few others) on Dec 25:
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4982436

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

muzak23

**Comment by MuteTiefling** [comment]
Thanks for the report! We're probably due for a little update here for this and a crash in bumblezone that was fixed.
