### ISSUE TITLE
Crashing in the Ur-Ghast dungeon

### ISSUE THREAD

**Issue by mnxxfxl** [EnigmaticaModpacks/Enigmatica9#824]
### Modpack Version

1.17

### Describe your issue.

Crashing at random points in the Ur-Ghast dungeon. I was flying straight to the Ur-Ghast and crashed both during and after the Ur-Ghast fight. 

### Crash Report

https://gist.github.com/mnxxfxl/9e90198177470b0a35ebdf642bb99631

### Latest Log

https://gist.github.com/mnxxfxl/002a08550bff959e68c1e05ddc617d99

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ak4.7

**Comment by NielsPilgaard** [comment]
Thanks for the report.

It looks like it's related to FTBChunks - Did you by chance have the area claimed?

**Comment by NielsPilgaard** [comment]
Found the issue reported here: https://github.com/FTBTeam/FTB-Mods-Issues/issues/1049

**Comment by Kanzaji** [comment]
This is fixed on Dev of FTB-Chunks, so should be fixed next update of the mod 😄

For now we either wait or downgrade FTB-Chunks before optifine-shenanigans fix.

**Comment by NielsPilgaard** [comment]
Downgrading to fix this in E9 1.17.2, should be up within 15 minutes.
