### ISSUE TITLE
E9E: Make Excavator quest accept ironwood excavator/mining hammer

### ISSUE THREAD

**Issue by TheKedart** [EnigmaticaModpacks/Enigmatica9#826]
### Describe your suggestion

Change the quest Equipment -> Excavators to accept ironwood excavator/mining hammer. 

### Why would you like this added/changed?

Players are much more likely to obtain (as loot) or craft the ironwood versions of the tools considering the gating of the diamond ones.

**Comment by MuteTiefling** [comment]
Odd, I could have sworn those accepted any of the tools :D I'll get that changed up
