### ISSUE TITLE
Change position of Lingering Absorber Automation quest

### ISSUE THREAD

**Issue by TheKedart** [EnigmaticaModpacks/Enigmatica9#833]
### Describe your suggestion

Move lingering absorber automation quest to be a child of the lingering absorber quest

### Why would you like this added/changed?

so i can tell people the spell is in the quest and not look like an ass because that quest is kinda tucked away

Real talk tho, it just makes sense for it to be a child quest of the lingering absorber.

**Comment by MuteTiefling** [comment]
Good idea!
