### ISSUE TITLE
[Expert] Few Create blocks aren't translated.

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#836]
### Modpack Version

1.17.2

### Describe your issue.

Some of the blocks in Create aren't translated into Expert form 😅

![obraz](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/a03d27ee-f93d-4308-898c-19c8e7fa7e41)

## List:

- Brass Encased Shaft
- Brass Encased Cogwheel
- Brass Encased Large Cogwheel
- Andesite Door

On small note, there are few new things in Create, and I think quests should get revisited, as for example, now there is Another rope pulley that allows for way easier Elevators! And Mechanical Rollers were added as well, which are really neat.

### Have you modified the modpack?

Yes

### User Modifications

Added Embeddium. Shouldn't affect translations tho 😄

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

kanzaji

**Comment by MuteTiefling** [comment]
What language is your client in? The renamed items for Expert would only be applying to `en-US`

**Comment by MuteTiefling** [comment]
Annnd... no I can't find anything but the andesite door. the others don't show in EMI. 

Rolling mill is also represented in the quests. I think I just didn't do the elevator pulley because I didn't want to spend the time on it. Might look at it in a bit though

**Comment by Kanzaji** [comment]
Figured out why I was able to even see them in the first place. I did change in EMI Configuration file the source for index from `Creative Tabs` to `Creative Tabs + Registered` 😅 That explains why you aren't able to find them, as by default they aren't visible 😋
