### ISSUE TITLE
Cannot Enter the Overworld in rituals.

### ISSUE THREAD

**Issue by YiRanMushroom** [EnigmaticaModpacks/Enigmatica9#840]
### Modpack Version

1.17.2

### Describe your issue.

In the ritual that teleports people to the overworld, when it teleports me there, the game compeletely freezed, and if I exit the game and load that world, the time would become before the ritual was started. I tryed 4 times, and in a time that it even unable to teleport, the game freezes even before the ritual ends.

I modified the NBT, and I found that if I change my dimention to the overworld, the game works fine, so it would probably a problem with that ritual.

### Latest Log

https://gist.github.com/YiRanMushroom/3fea6d45fb35b7efddb90fe7d4a643da

### Have you modified the modpack?

Yes

### User Modifications

Used ExtendedAE

https://github.com/GlodBlock/ExtendedAE

AE2AO

https://www.curseforge.com/minecraft/mc-mods/forge-ae2-additional-opportunity

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. We'll investigate the issue

**Comment by Kanzaji** [comment]
Issue was reproduced in dev, but thanks for letting us know :D
