### ISSUE TITLE
UrGhast chest overflows and does not always contain a dream stone

### ISSUE THREAD

**Issue by Szavircu** [EnigmaticaModpacks/Enigmatica9#841]
### Modpack Version

1.16.1

### Describe your issue.

The Ur-Ghast chest does not always contain a dream stone. It also always seems to be full with excess items like fire essence appearing in the world near it.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report!
