### ISSUE TITLE
Chunks cannot be loaded after teleporting to overworld

### ISSUE THREAD

**Issue by YocyCraft** [EnigmaticaModpacks/Enigmatica9#843]
### Modpack Version

1.17.2

### Describe your issue.

The minimap of ftbchunks shows the terrain, but the chunk failed to be loaded on the client side.

![2024-01-10_22 10 03](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/80801884/b1f32249-26ae-468d-bc24-bcaffa8d82c4)
![2024-01-10_22 10 59](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/80801884/dba378ae-38ef-4de4-b752-7f8b7eacae77)
![2024-01-10_22 12 25](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/80801884/348c2027-ab68-4e11-9340-9b793850c53f)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
This is fixed in e9e v1.18.0

https://www.curseforge.com/minecraft/modpacks/enigmatica9expert/files/5015233
