### ISSUE TITLE
Lightning crafting doesn't show percentages in EMI

### ISSUE THREAD

**Issue by kirjorjos** [EnigmaticaModpacks/Enigmatica9#845]
### Modpack Version

1.17.2

### Describe your issue.

No matter where I hover, there isn't anywhere that lists any percent chance for a lightning craft in EMI
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/35607697/bbd8d972-eb6e-483d-a83c-59a69863fbb4)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

kirjorjos

**Comment by MuteTiefling** [comment]
Not a proper fix, but the linked PR is going to set this to a 1:1 ratio instead of the current random chance
