### ISSUE TITLE
duplication of all items in bauble Slots

### ISSUE THREAD

**Issue by flece** [EnigmaticaModpacks/Enigmatica9#847]
### Modpack Version

1.18.0

### Describe your issue.

after summoning the Unbound Afrit Ritual i got killed by that Boss "Krtimac"
and it duplicated all my Items in my bauble slots. 
* Backpack but without content
* Ars Rings
* Naga Trophy

this happens 2 times.

After that i stole him all his Armor (Hopper) and let him kill me again....this time NO duplication.

<3

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
Thanks for the report!

Did you had the "Charm of keeping" from Twilight Forest in your inventory / bauble charm slot :D?

**Comment by flece** [comment]
i think it was an  "Charm of Keeping III" but i dont know for sure.

**Comment by MuteTiefling** [comment]
I'm just going to go ahead and disable the Charms of Keeping entirely. They should no longer drop as loot as of next update. Feel free to toss them in the trash.
