### ISSUE TITLE
E9E - Cheaper Tent Mallet

### ISSUE THREAD

**Issue by TheKedart** [EnigmaticaModpacks/Enigmatica9#848]
### Describe your suggestion

I would like a much cheaper tent mallet recipe.

Ideas:
-Amethyst Shards instead of source stone
-Soapstone instead of source stone (cause it's black? and kinda common in hollow hills)
-Six string = 1x tent fabric (Spiders are common in Lich tower and hollow hills)

ALTERNATIVELY:
-Make the quest reward tent mallet unbreakable
-Make the quest reward tent mallet come enchanted with Unbreaking III

### Why would you like this added/changed?

When I first started the pack, I wanted to use the tent as a temporary base while I went from boss to boss taking them down, before deciding on a permanent base location. The quests seemed to imply this was the point of giving you a tent! Unfortunately, the low durability of the starter mallet and the tech requirements to craft more meant that I had to abandon my hopes and dreams and make an actual base in-world. Once you have an actual base, the value of the tent as a starter base drops pretty sharply.

I don't feel that making the bad mallet easier to craft impacts pack balance in any meaningful way; it just makes it easier to actually live like a nomad lost in the Twilight Forest before you get into the nitty-gritty of an expert pack.

**Comment by MuteTiefling** [comment]
So, currently the only requirement to crafting another mallet is the Imbuement Chamber. That requires crafting Bronze and is 2 quests after the tent is given out...

By the time you kill the Naga and get some starting ore, you should be able to make another hammer. No?

**Comment by TheKedart** [comment]
Imbuement chamber requires Ritual of the Forest, which requires gold leaf, which requires a tree setup + waiting. This required infrastructure + wait time made me decide to make a permanent base instead of living out the nomadic dream :'(

**Comment by MuteTiefling** [comment]
I'll take a look at something. I'm not fond of the idea of changing the recipe further, but perhaps some source stone in chests would help.
