### ISSUE TITLE
Attribute of thermal upgrade augments obtained by crafting and quest reward are inconsistent

### ISSUE THREAD

**Issue by YocyCraft** [EnigmaticaModpacks/Enigmatica9#849]
### Modpack Version

1.18.0

### Describe your issue.

Upgrade augment obtained from quest reward:

![2024-01-15_16 10 43](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/80801884/d31b62da-fd08-4d4f-93bb-606e128a54b5)

Upgrade augment obtained by crafting:

![2024-01-15_16 10 47](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/80801884/39fa2850-34b9-4d13-9e7e-94334184decf)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. This was somewhat intentional but poorly addressed in game. I think for the sake of consistency I'll just normalize these to the crafted levels.
