### ISSUE TITLE
E9E - Hint via JEI About Items Received via Druid's Pouch Naga Drop

### ISSUE THREAD

**Issue by Seacant** [EnigmaticaModpacks/Enigmatica9#852]
### Describe your suggestion

Items received via the Druid's Pouch (Hexeri seeds, Quark saplings, Mendosteen, etc) should have a note in JEI that they are received via the Naga boss chest / Druid Pouch. Most of them already have an `Info` panel describing where they would normally be found, so this would fit as an additional note in there.

### Why would you like this added/changed?

I just spend an embarrassing amount of time trying to find Mendosteen on a "naturally occurring Flourishing Archwoord Tree" when those don't seem to exist (at least in the twilight forest)

**Comment by MuteTiefling** [comment]
Out of curiosity, what got you on the track of needing them before completing the first quests?

**Comment by Seacant** [comment]
They were totally in my chest the entire time. I assumed I didn't have any because I had not, at that point, done the ritual for the flourishing archwood, and that was how they were said to be obtained. I went straight to looking for a naturally occurring tree once the planted tree gave no results.

**Comment by MuteTiefling** [comment]
Hrm... So it might help if at least some of the drops weren't in the druid satchel, allowing it to show up in EMI

**Comment by Seacant** [comment]
Saw the new descriptions added in 185c56. They look great, and would have helped hint me towards checking my seed bags. Thanks!
