### ISSUE TITLE
EMI shows irrelevant alternatives

### ISSUE THREAD

**Issue by flece** [EnigmaticaModpacks/Enigmatica9#866]
### Modpack Version

1.18.0

### Describe your issue.

Pack fresh installed. EMI default settings
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/400313/434f06dc-2241-4bcd-8690-843a5fe97d77)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
That is by design of EMI, it doesn't show alternatives, but items that are in the tag used in the recipe 😄

**Comment by flece** [comment]
as i started the pack it was hidden. i cannot say when it changed.
