### ISSUE TITLE
Occultism: Friends Advancement doesn't work

### ISSUE THREAD

**Issue by txm3278** [EnigmaticaModpacks/Enigmatica9#868]
### Modpack Version

1.18

### Describe your issue.

Summoning a familiar does not grant the Occultism: Friends Advancement and does not complete the Chapter 1 quest, Combat Assistance - Familiars. When trying to grant the advancement using the command, the advancement can't be found.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

TMinz

**Comment by MuteTiefling** [comment]
Hrm, yep. Seems to have broken at some point. Confirmed on my side as well. I'll check in with klikli to see what's up there.

**Comment by txm3278** [comment]
I don't know what changed but we were now able to get the advancement. We have since entered Chapter 2 so not sure if that fixed it

**Comment by MuteTiefling** [comment]
Thanks for the update. I'll keep an eye on it still. Sometimes advancements are just... Weird.

Still, it's odd I was also having issues in a fresh world.
