### ISSUE TITLE
Boats can't be crafted with Twilight Oak Planks

### ISSUE THREAD

**Issue by Jatie1** [EnigmaticaModpacks/Enigmatica9#873]
### Modpack Version

1.18.0

### Describe your issue.

I think it's self explanatory
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/70575943/f5fc267f-b699-4b78-8fcb-2d7ac8e7be7a)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Jatie

**Comment by MuteTiefling** [comment]
Thanks for the report. Unfortunately, there's no Twilight Oak boat to make from Twilight Oak planks. 

Oak, Spruce, Birch, and Jungle planks are readily available in the Twilight Forest, however, and can be used to craft their respective boats. Practically every other sapling may also be purchased from the Market and used for boat making purposes as well.
