### ISSUE TITLE
Whitelist ME interfaces and pattern providers

### ISSUE THREAD

**Issue by fifty-six** [EnigmaticaModpacks/Enigmatica9#877]
### Describe your suggestion

As of Entangled 1.3.17, AE2 (and RS) blocks are blacklisted by default due to 'buggy behavior'. I believe it's mostly just cables not connecting. I'd love to see the interface and pattern providers "whitelisted" as they worked well. The `ae2` tag is blacklisted, for reference.

### Why would you like this added/changed?

Entangling interfaces and pattern providers significantly reduced cable clutter/amount of item transportation things I had to use, as well as it being a mild breaking change.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion! 

In order to better assess this, I'd like for you to ask the Entangled dev what buggy behavior with AE/RS entails, so I can make an informed decision - Is that fine with you? :)

https://github.com/SuperMartijn642/Entangled

**Comment by SeooY** [comment]
This seems to be the buggy behaviour referenced, that prompted the change: 
https://github.com/SuperMartijn642/Entangled/issues/27#issuecomment-1368512955

The only "bug" (I would call it more unexpected behaviour) is that the network itself can't be entangled. But knowing that limitation, it's still useful to entangle interfaces to input into the network.

**Comment by NielsPilgaard** [comment]
Super, thank you 👍
