### ISSUE TITLE
Ancient City Honey Compass doesn't register in Quest Book.

### ISSUE THREAD

**Issue by fifty-six** [EnigmaticaModpacks/Enigmatica9#882]
### Modpack Version

1.19.1

### Describe your issue.

The "Honey Compass - Ancient City" doesn't register in the quest for the "Ritual of Growth" in Chapter Three. For what it's worth, I crafted it in the Twilight Forest and took it out of an inventory there, where it then couldn't find the structure on initial withdrawal, then it said Ancient City once I actually right clicked in the Overworld.

### Latest Log

https://paste.gg/p/anonymous/c8d20b361e72485f9f952b97f65c612f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

56#1363

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll investigate the issue.
