### ISSUE TITLE
pre-Entangled Blocks are no longer able to be placed

### ISSUE THREAD

**Issue by fifty-six** [EnigmaticaModpacks/Enigmatica9#883]
### Modpack Version

1.19.1

### Describe your issue.

If you break a block that you've entangled using the binder, then you can't place them down again as it gives you the error `Binder is bound to unknown dimension 'minecraft:'!`. For what it's worth, this was the same error you'd get with blacklisted blocks previously. Note that you *can* still entangle blocks, you just can't break and replace them without resetting them and re-binding, which is an inconvenience.

### Latest Log

https://paste.gg/p/anonymous/c8d20b361e72485f9f952b97f65c612f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

56#1363

**Comment by MuteTiefling** [comment]
Thanks for the report, we'll look into that.

**Comment by netherportal3** [comment]
I second this. The same bug was present in All The Mods 9, and requires you to reset them in the crafting grid. If you need more info, I can do more testing.

**Comment by MuteTiefling** [comment]
Thanks for the offer. It's already been reported to the author, however, so at this point it's in their hands.

**Comment by MuteTiefling** [comment]
Looks like we'll be able to fix this completely in the next update.
