### ISSUE TITLE
MultiMC "Archive does not contain a recognized modpack type" when following install instructions

### ISSUE THREAD

**Issue by TorleifHensvold** [EnigmaticaModpacks/Enigmatica9#889]
### Modpack Version

Enigmatica 9 - E9 - 1.19.2 (Uploaded Feb 24, 2024)

### Describe your issue.

When following the instructions for installing the modpack in MultiMC (version 0.7.0-3826) as described in https://wiki.enigmatica.net/main/help-desk/guides/installation MultiMC gives the error "Archive does not contain a recognized modpack type" when trying to import from .zip as instructed.

This is the same kind of problem that other people have had with this, see https://new.reddit.com/r/VaultHuntersMinecraft/comments/ydgyuk/multimc_archive_does_not_contain_a_recognized/ for the _type_ of problem this is, and following the instructions given in https://new.reddit.com/r/VaultHuntersMinecraft/comments/vb5nab/comment/ic743ze/ (with updated versioning as fitting the modpack) has worked well for all other modpacks I have installed since those other modpacks include all the individual mod .jar files when downloading the server files, while Enigmatica 9 server files only include:

- server-guid.txt
- server-setup-confic.yaml
- start-server.bat
- start-server.sh

A good course of action in response to this would be to at least change the installation instructions for MultiMC on your wiki site to say that you don't currently support MultiMC, and I would hope that it would be possible to make it feasible to get Enigmatica 9 imported to MultiMC. I believe one _could_ download all the mods individually and add them and thus play through MultiMC, though that is a massive amount of work each and every person wanting to play it would have to go through. To mitigate this a solution could be to include a .zip of the collected .jar files (at their correct version for the modpack) in the additional files tab on CurseForge separate from the standard "server files" you currently supply.

Another option could be to have the pack available through Modrinth or ATLauncher, as those currently show up as places one can easily install modpacks directly through the MultiMC client. Technic has some Enigmatica versions available (I'm assuming unoffical uploads there) available through the MultiMC client, but not Enigmatica 9.

I'm sure you may have other solutions you can think of or figure out that may be better than the options I have given here, and hope you're willing to help people be able to play your modpack(s) through MultiMC. Thank you for your patience and work.

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TheKedart** [comment]
Not a bug. You can't install curseforge modpacks via MultiMC.

You have two options:
1. Download the modpack using a different launcher (ie Curseforge) and then copy the instance over. This will take a bit of finagling to get working and is not recommended if you have no clue what is going on.
2. Use a better launcher that can download modpacks. I recommend Prism Launcher.

**Comment by TheKedart** [comment]
Curseforge explicitly changed how packs are distributed and MultiMC explicitly changed to not support Curseforge. Your past experience is irrelevant; what you want to accomplish is not possible with how things work currently.

You can download the pack separately and import it into multiMC if you can figure it out, or you can use a different launcher.

**Comment by MommyHeather** [comment]
MultiMC is incapable of downloading or importing Curseforge modpacks anymore.

If you want to use it, use Prism Launcher - it is a MultiMC fork, with Curseforge support and various other QOL features.

**Comment by MommyHeather** [comment]
> Another option could be to have the pack available through Modrinth or ATLauncher, as those currently show up as places one can easily install modpacks directly through the MultiMC client. Technic has some Enigmatica versions available (I'm assuming unoffical uploads there) available through the MultiMC client, but not Enigmatica 9.

As for this:

Modrinth is impossible, due to API constraints.
Technic illegally reuploads packs and mods without author consent. This is a license violation for the vast majority of those packs / mods.

**Comment by Darkere** [comment]
>  did write that it worked perfectly well to get modpacks from CurseForge with MultiMC when those modpacks included all the .jar files in the server files .zip file.

I recommend avoiding this approach. You may be missing out on critical mods that only work on clients

**Comment by TorleifHensvold** [comment]
MommyHeather:
> MultiMC is incapable of downloading or importing Curseforge modpacks anymore.
> 
> If you want to use it, use Prism Launcher - it is a MultiMC fork, with Curseforge support and various other QOL features.

Please read again how I managed to play CurseForge distributed modpacks with MultiMC. It's not difficult, it's just not single-button convenience. That's also not the most important part of it (see the whole thing about the official instructions on how to install it in MultiMC given by the official wiki), and saying "use another launcher" is not helpful when this is the only modpack I've had this problem with (because of the .jar files not being distributed in the .zip for the server files, as previously stated) and I'm not planning on changing launchers over one modpack not distributing the .jar files with the server files .zip like all the other modpacks I've installed do.

It's not like I'm even asking for official support for MultiMC. See what I originally wrote about _at least_ changing the installation instructions on the official wiki to say that MultiMC isn't currently supported. I was just hoping it was possible to get the .jar files as a collection, not just the 4 files that were in the server files .zip as written originally.


TheKedart:
> Curseforge explicitly changed how packs are distributed and MultiMC explicitly changed to not support Curseforge. Your past experience is irrelevant; what you want to accomplish is not possible with how things work currently.
> 
> You can download the pack separately and import it into multiMC if you can figure it out, or you can use a different launcher.

**If** this modpack distributed the .jar files like all the other modpacks I've dealt with then as previously written I would not have a problem. What I want to accomplish is perfectly possible, because what I want to accomplish is to have the .jar files used in the modpack collected in a .zip file for easy addition to the instance of the modpack through MultiMC. I can understand that doing so will be at least a little more work in addition to the fancy server startup scripts, and I don't know how easy that would be to automate.
I'm not asking for getting one-click installation of the modpack. As far as I understand it would even make it easier for people not using _any_ 3rd party launcher for Minecraft to manually get the modpack to work if they got the collection of the .jar files from the developers of the modpack.

As for your claim that MultiMC explicitly changed to no support CurseForge what I now read seems more to imply that MultiMC does not try to circumvent the blocking of downloads while other launchers explicitly try to circumvent it. While I think it sucks that CurseForge changed how non-CurseForge launchers could access their resources that is in fact their prerogative. I would be interested in seeing information that supports your claim of MultiMC explicitly changing to not support CurseForge since your statement seems to indicate that you have something better than my searches to support it.

Now, I'm going to tell you something you probably know. You come across as very hostile to me when I've only tried to be civil and bring up something I feel is a problem that has some easy solutions (part of this impression of hostility is not at all recognizing some of the solutions I brought up and just going straight to what amounts to "you're doing it wrong"). It does not _seem_ to me like you read and understood what I originally wrote with how you are responding.

**Comment by MommyHeather** [comment]
Read darkere's explanation as to why you should not use server packs on the client. 

Also, no, prism does *not* circumvent blocking of downloads.
It uses the official third party api, using its own api key.

**Comment by TorleifHensvold** [comment]
> > did write that it worked perfectly well to get modpacks from CurseForge with MultiMC when those modpacks included all the .jar files in the server files .zip file.
> 
> I recommend avoiding this approach. You may be missing out on critical mods that only work on clients

Thank you for your concern. You may be correct that there would be some mods that are only meant to be on the client download that I'm missing, though I haven't encountered any problems with it so far. As far as I know all the things that change the gameplay itself has to at least be on the server. I can't really see what things would be critical that would only be on the client. I may be missing something that makes it important, though.

**Comment by TorleifHensvold** [comment]
> Also, no, prism does _not_ circumvent blocking of downloads. It uses the official third party api, using its own api key.

https://github.com/PrismLauncher/PrismLauncher/issues/635 seems to indicate there is circumvention of CurseForge blocking of downloads.
I also used https://github.com/TayouVR/MinecraftLauncherComparison to get an overview.

**Comment by MommyHeather** [comment]
That's a workaround, and sends the user to the curseforge website - that is what curseforge wanted, and isn't really "circumventing" anything.

Most mods don't require this however, only those who's devs have explicitly chosen not to allow downloads through the third party api.

**Comment by theboo** [comment]
Prism,  and other third party launchers like GD are not *bypassing* the third party restriction some mods have enabled(2 devs out of 300 mods in e9 have third party downloads disabled... Hexerei and EE+add-ons is it). They just open a browser and download from the site directly, these downloads are still counted towards the mod dev's download count for those precious curse points...

If you want the multimc experience with full CF support, prism is your answer, it is a fork of multimc. Downloading a server pack containing the entire pack including mods and configs and importing to mmc is not curseforge support, that's mmc importing a modpack that, for all it knows, could have come from anywhere.

You are definitely correct we should remove multimc from the wiki install instructions. These were written long before CF made their change and mmc decided to not follow suit. That section of the wiki should either just be renamed to prism, or removed entirely. Putting something like "we no longer support multimc" would make 0 sense as it wasn't us who removed support rather it was CF changing and multimc not following that removed said support, not some conscious decision on our end. We have been shipping server packs in this fashion long before the changes happened as well.

**Comment by TorleifHensvold** [comment]
I do not consider wrong documentation to be a support request. If I had done something other than exactly what I was instructed to through the official sources I consider that a bug. Neither do I deal with Discord stuff. It's not open.

You should probably fix the documentation bug on your wiki.

And if you wish you can consider wanting the .jar files as a .zip collection to be a feature request.

**Comment by MommyHeather** [comment]
> And if you wish you can consider wanting the .jar files as a .zip collection to be a feature request.

We've explained why this is a bad idea.

Yes, the documentation should be updated to mention Prism instead of MultiMC, but nothing else needs to change.
Modpacks are far more than jar files, and client / server packs often (rightfully) have different file lists.

**Comment by Kanzaji** [comment]
Okay I need to add my two cents here >.>

Distribution of the jar files in a zip file, instead of the CF Mod Ids is against CF TOS and is not even possible due to the fact jars can't be included in the official modpack zips, except some old mods that aren't on CF which are on the special list of allowed jars.

Also yes, I also think the section about MultiMC should just get removed 😅

If you want to stick with MultiMC anyways, use FTB launcher to install packs or some other third party app that has an option to download mods by ID. Or just change the launcher what is the simplest solution >.>

**Comment by TorleifHensvold** [comment]
To Kanzaji; Perfectly fine clarification comment.
I think it's strange that a lot of packs distribute a .zip of the .jar files as their server files under "additional files" on CurseForge if such is against the ToS. At least all the previous ones I've installed has had that.

**Comment by Kanzaji** [comment]
I think server / additional files are an exception for this, tho I'm not 100% sure as I'm not the one that uploads the zips :P

**Comment by MommyHeather** [comment]
Afaik it's fine TOS wise in server packs, but still potentially dodgy with licensing.

But also, the script method is just.. *cleaner*.

**Comment by MuteTiefling** [comment]
> I do not consider wrong documentation to be a support request. If I had done something other than exactly what I was instructed to through the official sources I consider that a bug. Neither do I deal with Discord stuff. It's not open.
> 
> You should probably fix the documentation bug on your wiki.
> 
> And if you wish you can consider wanting the .jar files as a .zip collection to be a feature request.

It's not a pack issue. We'll adjust the wiki, but this is the wrong forum to discuss it.

**Comment by NielsPilgaard** [comment]
I apologize for the hostility you've faced here @TorleifHensvold. The issue is ofcourse perfectly valid.

I have removed the MultiMC install instruction from our wiki.

We do not distribute jars in the server files for the following reasons:
- Server files with mod jars in them do not give mod authors CurseForge points (essentially money)
- Distributing jars is security risk. The CF rules appear to be fairly lax when it comes to server files, I don't know whether the jars are malware scanned.
- Smaller initial download size

Thank you for the feature request, but we will not be adding server files with jars in them.

**Comment by TorleifHensvold** [comment]
Thank you for the very well explained reasons, especially the part about how making a pack of the jars would essentially deprive those mod creators of some helpful monetary income.

Wish you the best.
