### ISSUE TITLE
Occultism Old Edition book duping

### ISSUE THREAD

**Issue by Joprebond** [EnigmaticaModpacks/Enigmatica9#89]
### Modpack Version

1.0.2

### Describe your issue.

When trying to make the occultism old book it will fill up your inventory with the "old edition". To reproduce, make the new book then use the 2x2 crafting grid to make the "old" book

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

JoprebondOdin#5307

**Comment by NielsPilgaard** [comment]
Thanks for the report, sorry for not responding sooner. 
While trying to reproduce the issue, I simply crashed.
I made this bug report: https://github.com/klikli-dev/occultism/issues/819
