### ISSUE TITLE
EMI not showing recipe preview in non-vanilla processing recipes

### ISSUE THREAD

**Issue by OlivierHogue** [EnigmaticaModpacks/Enigmatica9#890]
### Modpack Version

1.19.1

### Describe your issue.

When bookmarking recipe outputs from processing recipes from non-vanilla machine/process, it only shows the output item, not the recipe preview.

For example :

Pressing a on the recipe output of the vanilla furnace produce the recipe preview
![2024-03-04_10 46 22](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/98484605/4ecbe75d-eb0e-47da-aa77-26515b654f95)

But pressing a on the recipe output of the energized smelter from Mekanism doesn't produce the recipe preview
![2024-03-04_11 10 26](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/98484605/bfa70e06-1f0d-4557-b413-629a31f9cd0c)

Pretty much all modded processing machine or equivalent are affected, Ars Nouveau, Create, Occultism, Thermal, etc.
![2024-03-04_11 17 37](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/98484605/84086b55-33d6-481a-9b27-0bb4d20fa39e)

But world interaction and mob drops outputs are working
![2024-03-04_11 15 24](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/98484605/32fbab9e-2d21-4602-87f1-3f6fb6b256b3)

Kube.js is not reporting any errors nor warnings.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

barthymaeus

**Comment by MuteTiefling** [comment]
I believe this may be related to another issue we discovered lately. I'll link it to that and see what the EMI dev has to say.

**Comment by MuteTiefling** [comment]
Alright, looks like the underlying issue has been fixed in EMI.

**Comment by OlivierHogue** [comment]
Yup, I just saw it too. So do I just close the ticket, or is it done by the team ?

**Comment by MuteTiefling** [comment]
Don't worry about it. We'll close it up when we actually release a version with the fix.
