### ISSUE TITLE
AE2 Annihilation Plane not respecting Storage Bus filter

### ISSUE THREAD

**Issue by stormyblade** [EnigmaticaModpacks/Enigmatica9#894]
### Modpack Version

1.19.1

### Describe your issue.

Set up an Annihilation Plane connected to a ME Interface via a Storage Bus to mine Certus Quartz Crystal. It should only mine fully grown crystals, however it mines any type of crystal so as soon as one appears it gets destroyed (therefore not getting any Certus Quartz Crystal, despite it being in the Storage Bus)

This is probably because breaking a non-fully grown crystal is supposed to drop dust, but here it does not

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

stormyblade

**Comment by MommyHeather** [comment]
Is it enchanted with silk touch?

**Comment by stormyblade** [comment]
> Is it enchanted with silk touch? I believe it needs to be for this method to work.

No
the issue is that non fully grown crystals do not drop dust

**Comment by MuteTiefling** [comment]
I suspect this was fixed here already: https://github.com/EnigmaticaModpacks/Enigmatica9/pull/887/commits/9736f8718f622ba4c8a9759a6cf3bf0a3409528a

They're working correctly in Dev.

**Comment by MuteTiefling** [comment]
Yep, reverted that change in dev and it immediately started behaving as you're describing.

**Comment by MommyHeather** [comment]
Well, I stand corrected. Good to know.
