### ISSUE TITLE
Unable to craft Sophisticated Storages' Netherite Barrel/Chest

### ISSUE THREAD

**Issue by andr9528** [EnigmaticaModpacks/Enigmatica9#897]
### Modpack Version

v1.19.1

### Describe your issue.

Noticed that Sophisticated Storage' Netherite Barrel was not craftable, and then saw the same was the case for the chest.
Mentioned it on the Discord chat, where Motoko then pointed out that it was a bug.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

WolfDK@2337

**Comment by SeooY** [comment]
This seems to come from a mismatch between the Upgrade and the direct Barrel recipes. The Diamond to Netherite Upgrade is craftable. For example. here's the Gold to Diamond Upgrade:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/39110993/a0ec63b8-a0e4-4598-a3ce-a33b560360b2)
But here's the Barrel recipe:
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/39110993/a6e015f4-e089-4498-be10-cf121bd0ac39)
It seems like they misaligned at some point, and it could cause confusions.

**Comment by MuteTiefling** [comment]
Thanks for the report. I'll look into it.

**Comment by MuteTiefling** [comment]
Yeah, looking back at old versions, all of the upper tier crafts were meant to be disabled except for the tier upgrade items you click on an inventory to upgrade it. Looks like the recent sophisticated changes messed with a lot of that.

https://github.com/EnigmaticaModpacks/Enigmatica9/pull/898
