### ISSUE TITLE
MowLib (Group of Mods)

### ISSUE THREAD

**Issue by Mowmaster** [EnigmaticaModpacks/Enigmatica9#9]
### URL

https://www.curseforge.com/minecraft/mc-mods/mowlib/files

### Why would you like the mod added?

[Pedestals](https://www.curseforge.com/minecraft/mc-mods/pedestals/files)
[Effect Scrolls](https://www.curseforge.com/minecraft/mc-mods/effect-scrolls)
[Crystal Blocks](https://www.curseforge.com/minecraft/mc-mods/effect-scrolls)

Pedestals has gotten a huge rework and is way more pack dev / user friendly then before. there is already full documentation for what content already exists as well as new enhanced JEI support being added. (not all upgrades are finished yet, and a lot wont be re-added as the focus will be primarily focused on 'farming' [crops, animals, mobs])

Effect Scrolls is a stackable (stack limit based on duration/amplifier) potion effect item that gives users the ability to customize potion effects, amplifications, and durations based on what theyre doing, and its all completely customizable for pack devs
[jei and docs are in progress now]

Crystal Blocks is mainly a building blocks mod allowing 64 colors of blocks to build with, there are plans to add vertical slabs and potentially connected texture blocks as well as more block options in the future.

There is plans for a storage mod and generator mod as well that will use MowLib but ill suggest those later as they are developed.

**Comment by NielsPilgaard** [comment]
I'm sorry but no, we're trying to keep E9 light, and we don't really have a need or place in expert for either of those mods.
