### ISSUE TITLE
EMI not saving default recipes correctly

### ISSUE THREAD

**Issue by andr9528** [EnigmaticaModpacks/Enigmatica9#900]
### Modpack Version

v1.19.1

### Describe your issue.

When 'hearting' a recipe in EMI, only recipes which use vanilla mechanics will get saved between sessions.
Any that use a crafting block/system added by a mod will only be saved in the current session, and be lost upon restarting.
Recipes that are seemingly added by KubeJs are saved fine, as long as they use vanilla mechanics for creations.

Steps to reproduce:

1. Open emi.json in Visual Studio Code, and scoll all the way down to the 'recipe_defaults' object.
  a. Or some other software that has Live update on file changes. 
2. While looking at the emi.json file, ingame 'heart' and 'unheart' creation of Copper Ingot from Copper Nuggets in Crafting Table.
3. Notice in the emi.json that the 'heart' state is saved correctly.
4. Now do the save as 2. but using the 'Automated Packing' recipe by Create.
5. Notice in the emi.json that the 'heart' state is NOT saved correctly.

Have tested with a few other different vanilla/modded crafing systems. Fell free to contact me on Discord, if more examples are needed.

### Have you modified the modpack?

Yes

### User Modifications

2 small changes.
- Have re-enabled Sophisticated Storage/Backpacks' feeding upgrade.
- Changed Quark's "Enable Player Inventory In Chests" to false.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

WolfDK@2337

**Comment by MuteTiefling** [comment]
Thanks for the report. Did a little testing and it appears to be related to this: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/890

So it'll get fixed next update. In the meantime, you can probably safely update EMI unless you're on a server.
