### ISSUE TITLE
Bookwyrm Familiar Description Doesn't Match Between Quest Book and Worn Notebook

### ISSUE THREAD

**Issue by ValkoorMB** [EnigmaticaModpacks/Enigmatica9#909]
### Modpack Version

1.91.1

### Describe your issue.

The descriptions for the effect of the Bookwyrm familiar are different between the Quest Book and the Ars Worn Notebook. The Quest Book describes it as "lending their strength to each of their partner's spell casts", while the Worn Notebook describes them as automatically picking up nearby items and exp orbs within 5 blocks of the player. Upon testing, it looks like the item magnet functionality is what is occurring, but I wasn't able to test if it is _also_ boosting spell damage.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Valkoor

**Comment by theboo** [comment]
This is because the bookwyrm familiar functionality was changed at some point to make more sense with what the helper mob currently does(storage lectern network), rather than the spell caster it was in older versions. It does not have spell power functionality, the magnet is what it do. Ez fix!
