### ISSUE TITLE
Lectern Bug

### ISSUE THREAD

**Issue by LCSNeo** [EnigmaticaModpacks/Enigmatica9#910]
### Modpack Version

1.20.1

### Describe your issue.

I found a bug and was able to replicate it. If you add bookwyrm to the lectern and then with wand link controller or any chest(probably didn't test it) to lectern. Then killed bookwyrm and lectern says 1 connected inventory and 0 bookwyrms. It may seem nothing wrong but since there is 1 connected inventory it still thinks there is bookwyrm allowing to use lectern without bookwyrms at all. Did not test futher but the speculation would be you could use single bookwyrm to add unlimited amount of time inventories and still working without bookwyrm. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

LCSNeo#2804

**Comment by MuteTiefling** [comment]
Just a little extra context here for future reference:

Bookwyrms are only checked when you add an inventory. If there aren't enough, the new inventory isn't added. Being able to dispel/kill them without breaking connections is an intended feature in the mod.
