### ISSUE TITLE
Crash when Gateway attempts to generate Affix Item

### ISSUE THREAD

**Issue by andr9528** [EnigmaticaModpacks/Enigmatica9#911]
### Modpack Version

v1.20.1

### Describe your issue.

Fighting a Small Fire Elemental Gateway inside a Compact Machine (unlikely related but info anyways).
On kill of the last blaze, of the last wave the game crashes with the attached crash report.

On reload of the world, the game immediatly crashes again.

### Crash Report

https://gist.github.com/andr9528/95505a38f9dbbb3e96ac5b015a468509

### Latest Log

https://gist.github.com/andr9528/13fec762387c63b833c424c95f445321

### Have you modified the modpack?

Yes

### User Modifications

Have...
- Re-enabled Sophisticated Backpacks/Storage Feeding upgrade
- Reset Entangled's config to default.
- Set Quark to not sort player inventory, when sorting chests.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

WolfDK@2337

**Comment by andr9528** [comment]
Is reproducable, as it happens every time the gateways is completed.
Also seen to happen for the Small Death Tome Gateway

**Comment by MuteTiefling** [comment]
Thanks for the report. Yes, it appears to be something with the compact machines dimension, as it works fine outside of them. 

I'll keep investigating. Currently I suspect there may be a config that didn't account for this dim, but cannot confirm.

In the meantime, you can recover your world by setting `removeErroringEntities = true` in the `forge-server` config.

**Comment by andr9528** [comment]
@MuteTiefling Just thought of something. Should the same config adjustment not also be applied for the AE2 Spatial dimension?

**Comment by MuteTiefling** [comment]
Possibly. I thought players weren't allowed in there?

**Comment by andr9528** [comment]
If you stand in the area that is going to be stored, it will bring you in too. Just remember to bring a way out yourself, otherwise you are stuck.

**Comment by MuteTiefling** [comment]
Gateways 3.2.3 resolves the crash entirely, so I think I'll just let it stand at that.
