### ISSUE TITLE
Scrolling through waves on 'Death Tome Gate Pearl' in EMI crashes game

### ISSUE THREAD

**Issue by endobson** [EnigmaticaModpacks/Enigmatica9#913]
### Modpack Version

1.20.1

### Describe your issue.

I open inventory, EMI is on the right. Enter "Tome Gate" or similar in the search bar to and hover over the 'Death Tome Gate Pearl'. Scroll with shift held, and observe crash

### Crash Report

https://gist.github.com/endobson/502e6d7c3f2bd8f049b5c300233affe3

### Latest Log

https://gist.github.com/endobson/f9cf93425093becf2657ada55027acbc

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Shadows-of-Fire** [comment]
Screm, @SiverDX I thought you checked for these issues

**Comment by SiverDX** [comment]
don't accept ~candy~ commits from strangers

**Comment by TheUnnamed44** [comment]
When scrolling through the pearl's waves in the recipe window, the game does not crash, but rather the screen says "Error Rendering":

![2024-03-28_13 55 02](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/63647783/8122de7b-e56d-414e-8957-9c8af1983622)

And when hovering, a massive block of error code is shown:

![2024-03-28_13 55 07](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/63647783/780c7c8f-a349-46ee-beea-9f2e27e4e23b)

**Comment by SeooY** [comment]
I can confirm that the `GatewaysToEternity-1.19.2-3.2.3` release fixes both of these issues.

**Comment by MuteTiefling** [comment]
Unfortunately, that appears to be tagged as NeoForge, so the Curseforge launcher doesn't let us see it. Not sure we can actually include it in the pack as a result, but that's more @NielsPilgaard's area of expertise.

**Comment by MommyHeather** [comment]
No 1.19 jar should be tagged as for neoforge, so that's something the mod dev needs to sort. Regardless, doesn't the curseforge launcher let you see stuff that's tagged for both forge and neoforge?

**Comment by MuteTiefling** [comment]
Not when the mod loader doesn't match, no. 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/94bccf2d-2c38-4ffc-b6de-363aeeaee0d5)


If I manually add it, it even warns against it: 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/e33c0e98-ab63-4038-99ab-2c9e405f74cc)

**Comment by MommyHeather** [comment]
Ah I see, it's tagged neoforge only. @Shadows-of-Fire you might want to change that.

**Comment by Shadows-of-Fire** [comment]
Fixed, loader got mismatched during a buildscript backport
