### ISSUE TITLE
E9E Occultism Quest requiring unobtainable items

### ISSUE THREAD

**Issue by Robby9777** [EnigmaticaModpacks/Enigmatica9#916]
### Modpack Version

1.20.1

### Describe your issue.

The "Occult Materials" Occultism mod quest in E9E requests Otherworld Ashes, which is unotainable and has no recipes in the pack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TheUnnamed44** [comment]
Oak Sapling -- Purple Fire -> Occultism "Oak Sapling" (Otherwood Sapling in disguise)
Eat Demon's Dream Fruit to harvest Otherwood, then burn in purple fire

**Comment by MuteTiefling** [comment]
Thanks for the report! While it is obtainable, there's no sense keeping a quest for an item that's never used. I've gone ahead and removed the reference from the quest.
