### ISSUE TITLE
Add other drying racks to Hexerei Drying Rack quest

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#918]
### Describe your suggestion

The "Drying Rack" quest in the Hexerei chapter only accepts `hexerei:herb_drying_rack` when `hexerei:mahogany_drying_rack`, `hexerei:willow_drying_rack`, and `hexerei:witch_hazel_drying_rack` have the same functionality and are not accepted by the quest (looks to me like this is the case for both the e9 and e9e quests)

### Why would you like this added/changed?

I don't want to have to make the one that hangs from the ceiling if I don't have to lmao

**Comment by MuteTiefling** [comment]
Thanks for the report!
