### ISSUE TITLE
Regarding the Skyseer's Shoes Step Height 2 buff

### ISSUE THREAD

**Issue by Robby9777** [EnigmaticaModpacks/Enigmatica9#919]
### Describe your suggestion

It should be either toggle-able or entirely replaced by a better step-up ability such as Apotheosis Affixes.

### Why would you like this added/changed?

It's really annoying how the buff doesn't respect sneaking and cannot be toggled, you literally cannot enter the tree of life chamber while wearing the armor for example.

**Comment by MuteTiefling** [comment]
Thanks for the report!
