### ISSUE TITLE
Tablet of Awakening Quest requires Amethyst Golem charm

### ISSUE THREAD

**Issue by Unarelith** [EnigmaticaModpacks/Enigmatica9#924]
### Modpack Version

1.20.1

### Describe your issue.

Title.

Using Tablet of Awakening to create a golem doesn't provide a charm, it changes a budding Amethyst block into a golem.

I could use Dispel on the golem to get the charm, but why would this be required for the quest?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

unarelith

**Comment by MuteTiefling** [comment]
Thanks for the report! I'll go ahead and get that removed from there.
