### ISSUE TITLE
Crafting Mekanism Teleporter Frames only provides 8 instead of 9 blocks

### ISSUE THREAD

**Issue by Unarelith** [EnigmaticaModpacks/Enigmatica9#925]
### Modpack Version

1.20.1

### Describe your issue.

Title.

Mekanism teleporter is, unless I missed anything in the recent updates, a multi-block composed of 9 Teleporter Frames and 1 teleporter, in the following pattern:

```
FFF
F F
F F
FTF
```

However, the crafting recipe only provides 8 blocks.
Even though the teleporter will still work when it's missing a block, I'm not sure this is normal, hence this ticket.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

unarelith

**Comment by MuteTiefling** [comment]
Thanks for the report!
