### ISSUE TITLE
Ars Nouveau Questline Tweaks

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#927]
### Describe your suggestion

There currently do not exist quests for the Amethyst Golem Charm or Bound Script: Amethyst Golem in the Ars Nouveau quest chapter. There probably should be, given that there are quests for all the other charms and familiars.
Also, the "Starbuncle Logistics" quest requires Starbuncle Shards, which are harder to come by than the charms by themselves, at least in expert mode.

### Why would you like this added/changed?

quest nitpicks are my passion :)

**Comment by MuteTiefling** [comment]
Thanks for the suggestion!
