### ISSUE TITLE
E9E Expert PnC Quest Assembly Table description needs updating

### ISSUE THREAD

**Issue by superfluke** [EnigmaticaModpacks/Enigmatica9#929]
### Modpack Version

1.19.1

### Describe your issue.

Assembly Table quest in the Pneumatic Craft tab references easier recipes for circuits. However, these recipes are not available in the expert version of the pack. 

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/20022336/ddaa1f88-0364-42ad-89f6-e5bc2a1ef3e6)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks for the report!
