### ISSUE TITLE
No Certus quartz being spawned in game.

### ISSUE THREAD

**Issue by gzcwnk** [EnigmaticaModpacks/Enigmatica9#93]
### Modpack Version

1.0.2

### Describe your issue.

Unable to find any certus quartz what so ever, not even one.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
This is normal 😋 AE2 changed the way you get Certus, and the only way is to farm it with certus quartz puddles from Meteors. If those puddles didn't spawn there... then we have a problem.
