### ISSUE TITLE
Unable to empty Honey Bucket into Tank(s)

### ISSUE THREAD

**Issue by andr9528** [EnigmaticaModpacks/Enigmatica9#934]
### Modpack Version

v1.20.1

### Describe your issue.

The Honey bucket from Bumblezone cannot as far as i have tried be emptied into a tank.
Have tried to empty it into a Little Logistics' Fluid Hopper, and a Thermal Series' Fluid Cell.
Also tried to empty with Create's Item Drain.

Bumblezone adds a Honey fluid, which can be placed into the world with the bucket.
Machines/Tanks that already have the Honey fluid inside them, have no issue moving it into the same tanks tested with.

### Have you modified the modpack?

Yes

### User Modifications

Have...

- Re-enabled Sophisticated Backpacks/Storage Feeding upgrade
- Reset Entangled's config to default.
- Set Quark to not sort player inventory, when sorting chests.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

WolfDK@2337

**Comment by MuteTiefling** [comment]
Thanks for the report. I'm able to reproduce the issue and it seems that the buckets from BZ are just broken entirely. Even on the latest BZ version. 

I'll run some more tests shortly, but have relayed the issue to BZ in any case.

**Comment by MuteTiefling** [comment]
Confirmed fixed in Bumblezone 6.9.11
