### ISSUE TITLE
Consider adding Roots and Liveroots to Ars Nouveau Fell Tag

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#935]
### Describe your suggestion

Consider adding `twilightforest:root` and `twilightforest:liveroot_block` to `ars_nouveau:harvest/fellable`. This would make it so that roots and liveroots are harvested when using Fell on Twilight Forest trees that have connected roots.
If you do this, maybe also put something in the questbook to ward off "my tree left an ugly hole in the ground" comments?

### Why would you like this added/changed?

Convenience, also consistency with Mangrove Roots

**Comment by MuteTiefling** [comment]
Seems reasonable! I'll look into adding it for the next update.
