### ISSUE TITLE
BYG Saplings show up twice in Market

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#936]
### Modpack Version

E9E 1.20.1

### Describe your issue.

Oh The Biomes You'll Go Saplings are listed twice in the Farming for Blockheads Market. My guess is this is probably a holdover from a prior fix when the mods didn't add the saplings themselves.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

frogthejamunchained

**Comment by MuteTiefling** [comment]
Thanks for the report!
