### ISSUE TITLE
Amethyst Recipe in Crystallizer

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#937]
### Describe your suggestion

Make a recipe that turns Amethyst Dust (+ 500 or 1000mb Water) into Amethyst in the Thermal Crystallizer

### Why would you like this added/changed?

While it does add some nice consistency with some of the other dust -> crystal recipes in the pack, it really just bothered me that there are no recipes that use Amethyst Dust at all.

**Comment by MelodyCube** [comment]
Also, it seems there are some recipes that are of a similar dust -> crystal nature in the Mekanism Enrichment Chamber but some are missing.
From `forge:gems`, if the gem has a corresponding dust:
```
crystal     | EnCh | Crystallizer (water amount)
------------+------+-------
coal        | Y    | N
charcoal    | Y    | N
diamond     | Y    | 2000mb
emerald     | Y    | 2000mb
lapis       | Y    | 2000mb
quartz      | Y    | 2000mb
amethyst    | N    | N
certus      | N    | N
fluix       | N    | N
sulfur      | N*   | 500mb
fluorite    | Y    | 1000/2000mb**
niter       | Y    | 500mb
cinnabar    | Y    | 500mb
apatite     | Y    | 500mb
coal coke   | N    | N
subzero     | Y    | 1000mb
therium     | Y    | 1000mb
dimensional | Y    | 1000mb
```
Water amounts are in case someone wanted to equalize them.
\* If this recipe is added, someone would need to get rid of the sulfur dust -> gunpowder recipe that already exists.
\*\* This recipe seems to be shown twice, once with 1000 and once with 2000mb water required.

**Comment by MuteTiefling** [comment]
Thanks for the info. I've gone ahead and added recipes for dust>crystal for certus, fluix, and amethyst. Coal, charcoal, and coal coke aren't really crystalline, however, so I've left them out.
