### ISSUE TITLE
Fire Resistance Potion from Sushi Go Crafting Wasabi Root

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#938]
### Describe your suggestion

I was thinking it would be cool if some crops from Sushi Go Crafting could used as potion ingredients (just like some other crops in the pack) but I could really only come up with Wasabi, because it gives fire resistance when used in sushi anyway.

### Why would you like this added/changed?

it'd be cool idk

**Comment by MuteTiefling** [comment]
Thanks for the suggestion! Sounds like fun :D
