### ISSUE TITLE
Mod options

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica9#94]
### URL

https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption

### Why would you like the mod added?

Mod allows to quickly change mod options

**Comment by MuteTiefling** [comment]
Thank you for the suggestion, but this is a feature already offered by Create. We don't need a duplicate mod for the features.
![image](https://user-images.githubusercontent.com/9543430/196040399-01e7ff4c-0ef1-4972-a627-3c2c90738c2d.png)
![image](https://user-images.githubusercontent.com/9543430/196040407-f497808f-e70a-4ed3-802a-228e3c6bad02.png)
![image](https://user-images.githubusercontent.com/9543430/196040413-78260c50-170c-42f3-8469-ed129343d3b0.png)
