### ISSUE TITLE
Add Compressed Creativity for integration between Create and PneumaticCraft

### ISSUE THREAD

**Issue by pollyzoid** [EnigmaticaModpacks/Enigmatica9#941]
### URL

[Compressed Creativity](https://www.curseforge.com/minecraft/mc-mods/compressedcreativity)

### Why would you like the mod added?

Adding interactions between Create & PC:R would be nice, as they're both unconventional tech mods (in that they don't use FE) and (vaguely) thematically fitting together.

**Comment by NielsPilgaard** [comment]
Looks interesting, but it might be a too big change to introduce at this point 🤔 
Thoughts @MuteTiefling?

**Comment by MuteTiefling** [comment]
Could probably work it in without too much issue. It only has a handful of blocks that would need to be added to quests. 

I'd need some time though or its default recipes would gate it to the point of uselessness in Expert.

**Comment by NielsPilgaard** [comment]
But is it an addition that you would actually like? :D

**Comment by MuteTiefling** [comment]
Sure!

**Comment by NielsPilgaard** [comment]
Alright, I'm in 😄 I'll add it in-dev
