### ISSUE TITLE
Some Custom Potion Suggestions

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#944]
### Describe your suggestion

Since it is now possible, here are some suggestions for some custom potions for preexisting effects.

- Third Eye (Occultism): Not hugely necessary, but there is an easy recipe for it with Demon's Dream Fruit.

- Multi-Jump (Occultism): It would be cool to have this as a movement option early on and without the slow fall of the Drikwing. Since most jumpy things are used for Jump Boost, I was thinking perhaps Twilight Forest clouds would be good as an ingredient? (Terraria reference if for nothing else) The cloud recipe might need to be nerfed if so, though, because you can get a _lot_ of clouds. (also it would be cool if the Quark cloud in a bottle had a Twilight Forest cloud recipe too :) )

- Sundered (CoFH Core): Different from Apotheosis Sundering which just increases damage, CoFH Core Sundered reduces armor and is inflicted by Basalz. This would be a nice option against high armor enemies, but it might necessitate a name change from one or the other.

- Wrenched! (CoFH Core): This one would just be funny. It spins you around. :) Maybe it could be a Fermented Spider Eye/Mandrake Root plus a Potion of Stability as like an "inversion", or Polished/Rose Quartz for the Create connection (Create implies spinning). I was thinking gears or wrenches but nothing I found that is known to spin seems particularly alchemical. (this also might need a rename, maybe to like... dizziness?)

- Frost Resistance (CoFH Core): Like Fire Resistance. Maybe Arctic Fur as an ingredient? Protects from cold.

- Blast Resistance (CoFH Core): Like Fire Resistance. Not sure what to use as ingredients. Burnt Otherstone? Kind of like magical cement or something, maybe?

- Shock Resistance (CoFH Core): Like Fire Resistance. Maybe Living Root as ingredient? Has to do with being grounded.

- Lifesteal (Occultism): Would be cool to have as a potion. Not sure what to use as ingredients. Blood, maybe?

- Hidden (Bumblezone): Would be a cool early game utility (and an interesting alternative to Invisible). Maybe infused fabric? Something that conceals

- Love (CoFH Core): I just thought it would be fitting if you could get this from Spirit of Birthing or something.

- Bad Omen (Minecraft): If Love is from Spirit of Birthing, this could be from Spirit of Calling (because you're "calling" on pillagers to attack you or something?)
Not sure what to do with Spirit of Devotion though. I was thinking Panacea (CoFH Core) but that might be too powerful.

Okay, I kind of ran out of steam at some point but those are a few ideas. I might have more later. Feel free to take or leave whatever you want, of course!

### Why would you like this added/changed?

Cool

**Comment by MuteTiefling** [comment]
Nice list. I'll go ahead and add a few of these, but I'm not sure all of them are suitable. 

- Third Eye (Occultism): You get it from eating the fruit, and even in normal only need it like once or twice tops. Feels excessive to have in potion form. 
- Multi-Jump (Occultism): Added. I can appreciate wanting a source of this decoupled from slowfall from the drikwing.
- Sundered (CoFH Core): Added. 
- Wrenched! (CoFH Core): Seems very... niche. And probably more abusive on multiplayer than anything.
- Frost Resistance (CoFH Core): On the fence. This seems so niche that it might never be useful.
- Blast Resistance (CoFH Core): Probably best left to armor enchants. 
- Shock Resistance (CoFH Core): Similar to Frost, this would really only apply to attacks from Blitz
- Lifesteal (Occultism): I think this one I'll keep exclusive to how Occultism grants it, which is a permanent buff when using an upgraded familiar.
- Hidden (Bumblezone): There's already a nice source of this in game with a certain armor set ^_~
- Love (CoFH Core): Not sure this one even works. Didn't seem to the last time I tested it. 
- Bad Omen (Minecraft): 
- Panacea (CoFH Core): Way too powerful :D
