### ISSUE TITLE
Motes currently craft by 3 and should probably craft by 4

### ISSUE THREAD

**Issue by Unarelith** [EnigmaticaModpacks/Enigmatica9#946]
### Modpack Version

1.20.1

### Describe your issue.

Mote crafts give 3 items, but we'll use 4 stacks of them and that's their only use.

Currently we need 86 potions and we have 2 motes left after using the 4 stacks for the shard.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

unarelith

**Comment by MuteTiefling** [comment]
Considering these have had a rather massive cost reduction recently (no longer needing lingering), I think the best route would be to just balance it out to craft 1:1.

**Comment by Unarelith** [comment]
I agree with this idea!

However, what is the intended way to craft those potions?

Crafting with Wixie is possible, but will require filling potions by hand afaik
Crafting with Create is possible, but if done in a single basin adding glowstone will create Thick Potion with the water instead of adding it to the existing potion (is this fixable btw?)

**Comment by MuteTiefling** [comment]
There are multiple ways. With Create, you generally use multiple basins, however, allowing the output to flow from one basin to become the input in the next.

There are things that can do the right clicking for you to bottle from potion jars or hexerei cauldrons.

Or industrial foregoing has a nice brewer to help with the process.
