### ISSUE TITLE
[Expert] Alternate Recipes for Some Items that Require Iron

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#948]
### Describe your suggestion

Here are a few items and blocks that would be nice to have available earlier than Chapter 2 without having to rely on quest rewards. I doubt these will affect progression, but these are of course only suggestions.

Utility
- Wrench (Thermal Series)
- Slot Seal (Thermal Series)
- Signalum Security Lock (Thermal Series)
- Remote Detonator (Thermal Series)
- Attachment: Filter (Thermal Series)
- Bulk Item Filter (Modular Routers)
- Framed Key (FramedBlocks)
- Skillet (Farmer's Delight)
- Goblet (Supplementaries)
- Cage (Supplementaries)
- Wind Vane (Supplementaries)
- Basic Lever (Redstone Pen)
- Basic Button (Redstone Pen)
- Basic Pulse Button (Redstone Pen)
- Metal Barrel (Immersive Engineering)
- Jerrycan (Immersive Engineering)

Decoration
- Ornate Iron Window (Create)
- Lantern (Immersive Engineering)
- Big Chain (Decorative Blocks)
- Chain (Minecraft)\*
- Metal Bar (Engineer's Decor)
- Metal Sliding Door (Engineer's Decor)
- Dye Crafting Table (ManyIdeas Core)
- Candelabra (Hexerei)

\* May have the knock-on effect of allowing the Glyph of Chaining _slightly_ earlier. Probably doesn't matter.

Here are some that I figured I'd put here but probably don't matter much.
- Wrench (Powah)
Not very useful in this pack.
- Bubble Blower (Supplementaries)
Not very useful in general. Quark's Cloud in a Bottle covers its use case.
- Iron Gate (Supplementaries)
Might be nice with Iron Bars, but you have to scavenge for those anyway.
- Rope and Nail (Comforts)
By the time a Hammock becomes useful, you have access to iron.
- Charged Staff (Applied Energistics 2)
Maybe just for parity with the Entropy Manipulator.
- Lock Block (Supplementaries)
- Spring Launcher (Supplementaries)
- Relayer (Supplementaries)
- Pulley (Supplementaries)
Redstone devices that (to me) don't serve much decorative purpose.

Finally, I figured the Sophisticated Storage/Backpacks upgrades and the Functional Storage Simple/Compacting Drawers requiring iron are explicit design choices, but it'd be nice to have those too.
(looking at how long this list is honestly if you wanted i could just try to design the recipes myself lol)

### Why would you like this added/changed?

Wouldn't have to progress too far (or scour for iron in lich towers) to get some of these decorations and utilities.

**Comment by MuteTiefling** [comment]
Thanks for the list! Many of these seem perfectly reasonable. I'll have a more thorough look through later and see where things fall.
