### ISSUE TITLE
Ash Brick Has No Recipe

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#949]
### Modpack Version

E9E 1.21.0

### Describe your issue.

`supplementaries:ash_brick` has no recipe. Usually it is made from cooking `supplementaries:ash` in a furnace, so I assume it was an oversight related to removing `#forge/ingot` output recipes.
Also, since it is part of `#forge:ingots/brick`, it can be transformed into clay in the Mekanism Chemical Injection Chamber. It probably doesn't break anything, but I figured I'd make a note of it. (same is true of the Red Nether Brick)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

frogthejamunchained

**Comment by MuteTiefling** [comment]
Thanks for the report! We'll get that fixed up shortly.
