### ISSUE TITLE
Crimsite does not seem to spawn in the Twilight Forest

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#955]
### Modpack Version

1.21.0

### Describe your issue.

I looked around (a lot) and when I couldn't find any I went to see and it looks like it is missing from the configs [here](https://github.com/EnigmaticaModpacks/Enigmatica9/tree/master/config/configswapper/expert/config/emendatusenigmatica/deposit/dense/stone) (and in the [default](https://github.com/EnigmaticaModpacks/Enigmatica9/tree/master/config/emendatusenigmatica/deposit/dense/stone) and [normal mode](https://github.com/EnigmaticaModpacks/Enigmatica9/tree/master/config/configswapper/normal/config/emendatusenigmatica/deposit/dense/stone) configs as well).

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

frogthejamunchained

**Comment by MuteTiefling** [comment]
I'm hesitant to add this to the Twilight Forest generation, tbh. It was clearly missed before, but including it now will almost certainly cause world generation to change in established worlds, leading to hard borders between new and old chunks. Not a world ending issue, but certainly ugly for established worlds. 

I think instead, I'll just introduce some conversion recipes using manipulation essence, along the lines of what Ars Nouveau already does for vanilla stones.

**Comment by NielsPilgaard** [comment]
Good call imo 👍
