### ISSUE TITLE
Remove erroneous Skyseeker's step assist reference in quests

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#957]
### Describe your suggestion

The Skyseeker's Equipment quest in the Nature's Aura chapter of the Learning chapter group still states "When wearing a full set, grants ... the ability to step up one block", even though that functionality was removed.

### Why would you like this added/changed?

i didnt know whether or not to put this as a suggestion or a bug lol

**Comment by MuteTiefling** [comment]
Technically, the armor is supposed to have this by default but due to a bug it doesn't work. Our addition was to fix the bug, but I think it ultimately was just too much. I'll adjust the quest. People can always get step height on there with apotheosis if they want it.
