### ISSUE TITLE
Misspelled word in quests

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#959]
### Describe your suggestion

In "Dimensional Storage Actuator" in Chapter 2 of the Expert Mode quests, "wonderous" should be "wondrous".

### Why would you like this added/changed?

someone misspelled a word in the group chat!! let's get 'em!!

**Comment by MelodyCube** [comment]
oops so it looks like the same misspelling appears in "Certus Farming" in Chapter 1 and "ME Controller" in Chapter 2. I guess I should have looked harder the first time lol

**Comment by MuteTiefling** [comment]
Thanks. Did a broad search and found two more. No more Wonderous quests
