### ISSUE TITLE
Journey map

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica9#96]
### URL

https://www.curseforge.com/minecraft/mc-mods/journeymap

### Why would you like the mod added?

Allows to quickly add waypoints and better locating yourself in game world

**Comment by Gcat101** [comment]
oh boi here we go again

**Comment by Kanzaji** [comment]
We already have map mod in the pack 😛 One is enough.

**Comment by Gcat101** [comment]
There are two camps. People who like xearos and people who like journey. Nobody likes ftb chunks.

**Comment by NickyMB** [comment]
In Enigmatica 8 i believe u have both of them without any trouble

**Comment by Kanzaji** [comment]
That is true, but we prefer to have one this time 😋 Two are useless, and if you want, you can add it yourself.

**Comment by Gcat101** [comment]
> In Enigmatica 8 i believe u have both of them without any trouble

They're making a "lite" modpack this time. Whatever that means

**Comment by NickyMB** [comment]
U can also prefer to have "better" one

**Comment by MuteTiefling** [comment]
> > In Enigmatica 8 i believe u have both of them without any trouble
> 
> They're making a "lite" modpack this time. Whatever that means
> 

It means that, unsurprisingly, the pack is not a democratic endeavor. While we're happy to listen to requests, the final decision rests with us. 

Certain mods have already been picked out as desired and will be added as they become available. 

Others have been excluded as undesirable. 

There's still room for other mods that we may be unaware of, but journey map does not fall into that category.

We've decided to leave the map as ftb, which is sufficient. If you wish to change this after downloading the pack, you are, of course, welcome to. Changing the map mod will not impact your ability to play, either single player or on a server. If you do encounter issues, however, be sure to remove your alterations before reporting them.
