### ISSUE TITLE
Add Polymorphic Energistics for Polymorph recipe support in AE2

### ISSUE THREAD

**Issue by pollyzoid** [EnigmaticaModpacks/Enigmatica9#965]
### URL

https://www.curseforge.com/minecraft/mc-mods/polymorphic-energistics

### Why would you like the mod added?

AE2 compatibility for the few items that still rely on conflicting recipes.

**Comment by MuteTiefling** [comment]
I'd rather just fix the conflicts. It's been a while since I ran a report with polymorph, but if you're seeing conflicts please let us know what they are.

**Comment by pollyzoid** [comment]
Makes sense. I already generated a report for testing the mod out, here's a few picks I spotted from it:

Mutually exclusive conflict (can't transform between each other):
- `immersiveengineering:crafting/sawdust, thermal:storage/sawdust_block`

One-way conflict (can transform to more generic version):
- `minecraft:crafting_table, byg:zelkova_crafting_table`
- `quark:building/crafting/furnaces/cobblestone_furnace, quark:building/crafting/furnaces/deepslate_furnace`
- Maybe `quark:building/crafting/chests/mixed_chest, quark:building/crafting/chests/oak_chest` (idk what `mixed_chest` is)

Compat conflict (generated compat variants vs. original mod provided)
- Lots of Ars Scalaes Sourcestone auto-generated compat variants conflicting with Ars Nouveau versions

Full report: https://gist.github.com/pollyzoid/4c4faf65483eb24277c003607d10409f

**Comment by MuteTiefling** [comment]
Going to set this as won't fix since the mod won't be added. However the above PR does resolve the recipe conflicts themselves.
