### ISSUE TITLE
[Expert] Thermal Series Crystallizer can make one ore shard to 27x ore crystal

### ISSUE THREAD

**Issue by Frenqy** [EnigmaticaModpacks/Enigmatica9#967]
### Modpack Version

1.21.0

### Recipe In JEI
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/28777951/fe4f0c95-69db-45ab-b52e-377d0e7137f8)
recipe in JEI: 9 ore shard + 1 dimensional dust => 27 ore crystal

### EXPECT
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/28777951/160216d8-f3c9-4980-b934-6c66c4beb285)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/28777951/7385f493-4014-4590-8a9b-e5b2d43a3c6b)
it work

### ACTUAL
but if i swap the ore shard and dimensional dust
9 dimensional dust + 1 ore shard => 27 ore crystal
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/28777951/051083ab-6c30-4881-9c35-a9229082edb9)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/28777951/d0481ae3-aaaf-42e0-a72c-a7bd72aae770)

it also work!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Thanks for the report! I'll get those recipes fixed here.

**Comment by MuteTiefling** [comment]
Reported here so the underlying issue gets resolved: https://discord.com/channels/399037120930512897/434101214548852746/1234872017493299270
