### ISSUE TITLE
Apotheotic Boss configs for Ars Elemental mages are invalid

### ISSUE THREAD

**Issue by pollyzoid** [EnigmaticaModpacks/Enigmatica9#970]
### Modpack Version

1.21.0

### Describe your issue.

On a fresh install, after clicking `Singleplayer` in the main menu, and waiting for MC to load its resources, in the logs errors like the following can be seen:

```
[17:44:02] [Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing bosses file apotheosis:overworld/water_mage.
[17:44:02] [Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception: 
java.lang.RuntimeException: No key step in MapLike[{"min":2,"max":7}]; No key steps in MapLike[{"min":2,"max":7}]; No key step in MapLike[{"min":2,"max":7}]; No key steps in MapLike[{"min":2,"max":7}]; No key step in MapLike[{"min":2,"max":3}]; No key steps in MapLike[{"min":2,"max":3}] missed input: {"mythic":{"enchant_chance":1,"enchantment_levels":[36.0,30.0,100.0,85.0],"effects":[{"effect":"ars_nouveau:shielding","amplifier":{"min":2,"max":3},"chance":1},{"effect":"ars_nouveau:spell_damage","amplifier":{"min":2,"max":7},"chance":1},{"effect":"ars_nouveau:mana_regen","amplifier":{"min":2,"max":7},"chance":1}],"attribute_modifiers":[{"attribute":"minecraft:generic.max_health","operation":"ADDITION","value":{"min":60,"steps":40,"step":2}},{"attribute":"minecraft:generic.movement_speed","operation":"MULTIPLY_BASE","value":{"min":0.2,"steps":20,"step":0.01}},{"attribute":"minecraft:generic.attack_damage","operation":"MULTIPLY_BASE","value":{"min":0.35,"steps":35,"step":0.01}},{"attribute":"minecraft:generic.knockback_resistance","operation":"ADDITION","value":0.5},{"attribute":"minecraft:generic.armor","operation":"ADDITION","value":4},{"attribute":"minecraft:generic.armor_toughness","operation":"ADDITION","value":2}]}}
```
(repeated for different elements and dimensions)
Confirmed that these appear in my dedicated server logs as well.

Issue seems to be that mage boss effects are defined as such:
```json
{ effect: 'ars_nouveau:shielding', amplifier: { min: 2, max: 3 }, chance: 1 }
```

while Apotheosis/placebo expect `amplifier` to have keys `step` and `steps` (doc: https://github.com/Shadows-of-Fire/Placebo/blob/1a6dbc2ba56bd563cdd3b3cbde4eb70a717790ba/schema/StepFunction.md). These appear in both `normal` and `expert` kubejs scripts.

(Maybe this is the reason I don't recall seeing any mage enemies in my ~250 hours?)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

pollyzoid

**Comment by MuteTiefling** [comment]
Thanks for the report! I'll get that fixed up soon

**Comment by MommyHeather** [comment]
This is something.. I'm too used to errors just being part of modded Minecraft that despite seeing the errors mentioned here, I just... *ignored* them.
