### ISSUE TITLE
Add BYG Nether Tree-mushroom Saplings to Market

### ISSUE THREAD

**Issue by Teylahime** [EnigmaticaModpacks/Enigmatica9#974]
### Describe your suggestion

BYG has a couple mushrooms from their End/Nether biomes that act as trees and have logs/planks instead of just spawning mushroom stems. The End ones are a bit funky (Bulbis needs the BYG End mycelium equivalents, Imparius can only grow in the End proper). The Nether ones though seem to grow just fine on any dirt.

The ones that grow with wood equivalents are:
- Sythian Fungus
- Embur Wart

I don't think it would mess up anything if they were available. Embur can get pretty big from my testing in creative, but so can some of the other BYG trees.

### Why would you like this added/changed?

Embur in particular has a really cool looking wood that I think could be fun to build with early on or in Expert without having to go to the Nether first. It's a shame the End ones are End locked, their planks are nice colors.

**Comment by MuteTiefling** [comment]
Thanks for the suggestion! I think we can make this happen. I'll look into it soon.
