### ISSUE TITLE
Furnace recipe doesn't work

### ISSUE THREAD

**Issue by scmcgowen** [EnigmaticaModpacks/Enigmatica9#976]
### Modpack Version

1.22.0

### Describe your issue.

Any vanilla furnace recipes don't work at all.
This includes the vanilla 8 cobblestone in a ring pattern recipe, as well as any custom datapack recipes that make vanilla furnaces. The vanilla recipe shows in EMI, but furnaces can't be crafted at all
Deepslate furnaces from Quark are craftable but can't be used in most recipes

### Have you modified the modpack?

Yes

### User Modifications

During the debugging process of this bug, I created a datapack to add a furnace recipe, but it didn't work. No other modifications were made.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

herrkatze0658

**Comment by scmcgowen** [comment]
Just found a solution: Reverting commit `[c8bb93d](https://github.com/EnigmaticaModpacks/Enigmatica9/pull/966/commits/c8bb93d692e9811f077ac53952c36fded616afb0)` fixes the issue

**Comment by NielsPilgaard** [comment]
1.22.1 has the fix and is pending approval now 😊
