### ISSUE TITLE
Crash on startup without doing anything

### ISSUE THREAD

**Issue by EnderDrag0n** [EnigmaticaModpacks/Enigmatica9#982]
### Modpack Version

1.22.1

### Describe your issue.

I downloaded E9E first time and it crashes on startup. The main thing is that i didn't even got to main menu.

### Crash Report

https://gist.github.com/EnderDrag0n/fd43dcd4aaf5a1c22e483d3bf7a2eef3

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MommyHeather** [comment]
You're using the wrong java version. You need java 17.
