### ISSUE TITLE
 Spellbound Air Blower Bulk Blowing recipes show default name

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#983]
### Describe your suggestion

 In EMI the Bulk Blasting, Haunting, Smoking, and Washing recipes display the Spellbound Air Blower as "Industrial Air Blower behind [thing]". I assume it is unchanged from the default name. Hopefully an easy fix. 1.22.1

### Why would you like this added/changed?

goofy nitpick. would make the pack look a little more polished.

**Comment by Kanzaji** [comment]
@MuteTiefling Same here 😄
