### ISSUE TITLE
Steel Plates are automatically rewarded upon completion of Metal Press Quest in Expert Mode

### ISSUE THREAD

**Issue by MelodyCube** [EnigmaticaModpacks/Enigmatica9#984]
### Describe your suggestion

Title. If they were not auto-rewarded, it would be consistent with all other quest rewards. They make more sense to be auto-rewarded in Normal mode, in case someone were to need them to make press molds or steel sheetmetal, but these either do not have the same recipe or do not have the same relevance in Expert.

### Why would you like this added/changed?

consistency. this one is really the most nitpicky of nitpicks that i only figured out about because i am trying to do a playthrough without collecting any quest rewards lol

**Comment by Kanzaji** [comment]
@MuteTiefling I think this one can be closed 😄
