### ISSUE TITLE
Server not starting. Could not find main class....

### ISSUE THREAD

**Issue by Roadrunner1971** [EnigmaticaModpacks/Enigmatica9#985]
### Modpack Version

1.22.1

### Describe your issue.

Try to run sevrer through startserver.bat file and once it downloads and extracts all files needed it and accepting eula it says this 

Error: Could not find or load main class @libraries.net.minecraftforge.forge.1.19.2-43.2.14.win_args.txt

Any help would be appreciated
thanks

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Kanzaji** [comment]
You need Java 17 for Minecraft 1.19.2 😅
