### ISSUE TITLE
GRAVEL TO IRON NUGGET RECIPE GONE

### ISSUE THREAD

**Issue by nekomi1** [EnigmaticaModpacks/Enigmatica9#986]
### Modpack Version

1.22.1

### Describe your issue.

the gravel to iron nugget recipe is gone

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Kanzaji** [comment]
Hey there, thanks for the report, however removal of that recipe is intentional 😅
