### ISSUE TITLE
Add ancient wood slabs under the #minecraft:wooden_slabs tag

### ISSUE THREAD

**Issue by ENDvious** [EnigmaticaModpacks/Enigmatica9#987]
### Describe your suggestion

Add ancient wood slabs from Natures aura under the #minecraft:wooden_slabs tag Since it

### Why would you like this added/changed?

Its a wood type that otherwise doesnt have much use after your first half stack of ancient wood

**Comment by MuteTiefling** [comment]
Thanks for the suggestion. I've gone ahead and added the slabs/stairs to their appropriate wooden slab/stairs tags, matching other wooden slabs and stairs.
