### ISSUE TITLE
Game is not loading previously generated world

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica9#99]
### Modpack Version

1.0.2

### Describe your issue.

Yesterday I've generated world and play a little on it, today I can't get in to it. Just saying reading world data for 20 minutes and nothing happen. When I click on screen game stops working 

### Latest Log

<script src="https://gist.github.com/NickyMB/fe6b465c283cafe74a26e8544b03263f.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Szef#2794

**Comment by hofmannk69** [comment]
This happens to me everytime I create a new world in E9.  Killing it and restating the game and then the previously newly created world will then load.
