### ISSUE TITLE
[E9:E] - wrong link in Questbook

### ISSUE THREAD

**Issue by flece** [EnigmaticaModpacks/Enigmatica9#990]
### Modpack Version

1.22.1

### Describe your issue.

that link to AE2 Wiki is outdated,
new link: https://guide.appliedenergistics.org/1.19.2/features/me-network/quantum-bridge

![2024-07-28_16 19 16](https://github.com/user-attachments/assets/e5369235-fac0-4606-893e-1b447c217ed6)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Awesome, thanks for the updated link!

**Comment by flece** [comment]
these Quests are also effected:
* ME P2P Tunnels
* 1k ME Fluid Storage Cell
* 1k ME Item Storage Cell
* 1k ME Chemical Storage Cell

**Comment by MuteTiefling** [comment]
Thanks, I'll get those too.
