### ISSUE TITLE
AE2 Annihilation plane ignoring storage bus filters

### ISSUE THREAD

**Issue by Nova1545** [EnigmaticaModpacks/Enigmatica9#994]
### Modpack Version

1.22.1

### Describe your issue.

https://github.com/user-attachments/assets/c3826536-d0b2-4e40-b709-2a3553231491

When using a annihilation plane on Certus Quartz Blocks (Flawed, Flawless, etc) the plane ignores any filter set on a storage bus. Picking up any and all certus quartz blocks
(Video showing exactly what I mean)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

supernova157854

**Comment by MommyHeather** [comment]
Is the plane enchanted with silk touch, as stated as required in the guidebook?

**Comment by MuteTiefling** [comment]
Indeed, silk touch is the answer. I can reproduce this without silk touch, but it works as expected with silk touch, which seems to be intended.
