### ISSUE TITLE
Add ExtendedAE

### ISSUE THREAD

**Issue by Snakedon** [EnigmaticaModpacks/Enigmatica9#995]
### URL

https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider

### Why would you like the mod added?

The mod adds the ability to put more templates into the template provider, which will allow you to make not 8+ mechanisms, but fit everything into 1, mechanisms will take up less space, more space in general, and more convenience.

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion, but we will not be adding ExtendedAE at this time. Please see our reasoning in this suggestion on Enigmatica 10's tracker: https://github.com/EnigmaticaModpacks/Enigmatica10/issues/62
