### ISSUE TITLE
Server won't start (first start)

### ISSUE THREAD

**Issue by DavidFrings** [EnigmaticaModpacks/Enigmatica9#999]
### Modpack Version

1.22.1

### Describe your issue.

Server won't start (first start) 

### Crash Report

[Log](https://gist.github.com/DavidFrings/29a6eabef7a61ae73b0f85a661f3c76b)

### Have you modified the modpack?

Yes

### User Modifications

I modified the start-server.sh script to match the path for my Java 17 installation and also updated the server.properties file.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

DevOpsDavid

**Comment by MommyHeather** [comment]
The script is not using your java 17 installation.

Don't edit the script, there's a config value for it in the yaml file.

**Comment by DavidFrings** [comment]
OH ok
I will try it

**Comment by DavidFrings** [comment]
Now in the config there is:
```
forcedJavaPath: '/usr/lib/jvm/java-1.17.0-openjdk-amd64/bin/java'
```
but now I have this Issue:
[latest.log](https://github.com/user-attachments/files/16647946/latest.log)

**Comment by NielsPilgaard** [comment]
I recommend that you reinstall the modpack and modify your `PATH` environment variable to point to your Java 17.
Guide: https://www.java.com/en/download/help/path.html

**Comment by DavidFrings** [comment]
> 👋 @DavidFrings, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our [support channel on our Discord](https://discord.gg/kZ7RdrD) to get help with the project.
Sorry... https://discord.com/channels/195234321836146688/1274652287545114726
